from typing import Any, Callable, Iterable

class DefaultFilter:
    def __init__(
        self,
        query: Any | Callable[[], Any] | None = ...,
        query_parser: Callable[[Any], Any] | None = ...,
    ) -> None: ...
    @property
    def query(self) -> Any: ...
    def __get__(self, obj: Any, objtype: type | None) -> Any: ...

class MinShouldMatch(str):
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...

class BaseRecordsSearch:
    class Meta:
        index: str | None
        fields: tuple[str, ...]
        facets: dict[str, Any]
        default_filter: Any | None

    query: Any

    def __init__(self, **kwargs: Any) -> None: ...
    def get_record(self, id_: Any) -> "BaseRecordsSearch": ...
    def get_records(self, ids: Iterable[Any]) -> "BaseRecordsSearch": ...
    @classmethod
    def faceted_search(
        cls,
        query: Any | None = ...,
        filters: dict[str, Any] | None = ...,
        search: "BaseRecordsSearch" | None = ...,
    ) -> Any: ...
    def with_preference_param(self) -> "BaseRecordsSearch": ...
    def _get_user_agent(self) -> str: ...
    def _get_user_hash(self) -> str | None: ...

class PrefixedIndexList(list[str]): ...

class PrefixedSearchMixin:
    def prefix_index(
        self, index: str | list[str] | tuple[str, ...]
    ) -> str | list[str]: ...
    def _clone(self) -> Any: ...

class BaseRecordsSearchV2:
    query: Any

    def __init__(
        self,
        fields: tuple[str, ...] = ("*",),
        default_filter: Any | None = None,
        **kwargs: Any,
    ) -> None: ...
    def get_record(self, id_: Any) -> "BaseRecordsSearchV2": ...
    def get_records(self, ids: Iterable[Any]) -> "BaseRecordsSearchV2": ...
    def with_preference_param(
        self, preference: str | None = ...
    ) -> "BaseRecordsSearchV2": ...

class RecordsSearch(PrefixedSearchMixin, BaseRecordsSearch):
    def __init__(self, **kwargs: Any) -> None: ...

class RecordsSearchV2(PrefixedSearchMixin, BaseRecordsSearchV2):
    def __init__(self, **kwargs: Any) -> None: ...

UnPrefixedRecordsSearch = BaseRecordsSearch
UnPrefixedRecordsSearchV2 = BaseRecordsSearchV2
