def ascents(image: tuple[int, ...]) -> list[int]: ...
def call_ont_int(image: tuple[int, ...], idx: int) -> int: ...
def call_on_str(image: tuple[int, ...], string: str) -> str: ...
def descents(image: tuple[int, ...]) -> list[int]: ...
def exceedances(image: tuple[int, ...], weakly: bool) -> list[int]: ...
def int_repr(image: tuple[int, ...]) -> int: ...
def inversions(image: tuple[int, ...]) -> list[tuple[int, int]]: ...
def is_derangement(image: tuple[int, ...]) -> bool: ...
def lehmer_code(image: tuple[int, ...]) -> list[int]: ...
def lexicographic_rank(image: tuple[int, ...]) -> int: ...
def repr(image: tuple[int, ...]) -> str: ...
def records(image: tuple[int, ...]) -> list[int]: ...
def multiplication(lhs: tuple[int, ...], rhs: tuple[int, ...]) -> tuple[int, ...]: ...
def support(image: tuple[int, ...]) -> set[int]: ...
