depends = ('ITKPyBase', 'ITKTransform', 'ITKOptimizers', 'ITKImageGrid', 'ITKDisplacementField', 'ITKCommon', )
templates = (  ('vnl_nonlinear_minimizer', 'vnl_nonlinear_minimizer', 'vnl_nonlinear_minimizer', False),
  ('vnl_lbfgs', 'vnl_lbfgs', 'vnl_lbfgs', False),
  ('vnl_lbfgsb', 'vnl_lbfgsb', 'vnl_lbfgsb', False),
  ('LBFGSOptimizerBaseHelperv4', 'itk::LBFGSOptimizerBaseHelperv4', 'itkLBFGSOptimizerBaseHelperv4vnl_lbfgs', False, 'vnl_lbfgs'),
  ('LBFGSOptimizerBaseHelperv4', 'itk::LBFGSOptimizerBaseHelperv4', 'itkLBFGSOptimizerBaseHelperv4vnl_lbfgsb', False, 'vnl_lbfgsb'),
  ('LBFGSOptimizerBasev4', 'itk::LBFGSOptimizerBasev4', 'itkLBFGSOptimizerBasev4vnl_lbfgs', True, 'vnl_lbfgs'),
  ('LBFGSOptimizerBasev4', 'itk::LBFGSOptimizerBasev4', 'itkLBFGSOptimizerBasev4vnl_lbfgsb', True, 'vnl_lbfgsb'),
  ('LBFGSBOptimizerv4', 'itk::LBFGSBOptimizerv4', 'itkLBFGSBOptimizerv4', True),
  ('LBFGSOptimizerv4', 'itk::LBFGSOptimizerv4', 'itkLBFGSOptimizerv4', True),
  ('AmoebaOptimizerv4', 'itk::AmoebaOptimizerv4', 'itkAmoebaOptimizerv4', True),
  ('GradientDescentLineSearchOptimizerv4Template', 'itk::GradientDescentLineSearchOptimizerv4Template', 'itkGradientDescentLineSearchOptimizerv4TemplateD', False, 'double'),
  ('GradientDescentLineSearchOptimizerv4Template', 'itk::GradientDescentLineSearchOptimizerv4Template', 'itkGradientDescentLineSearchOptimizerv4TemplateF', False, 'float'),
  ('ConjugateGradientLineSearchOptimizerv4Template', 'itk::ConjugateGradientLineSearchOptimizerv4Template', 'itkConjugateGradientLineSearchOptimizerv4TemplateD', False, 'double'),
  ('ConjugateGradientLineSearchOptimizerv4Template', 'itk::ConjugateGradientLineSearchOptimizerv4Template', 'itkConjugateGradientLineSearchOptimizerv4TemplateF', False, 'float'),
  ('ExhaustiveOptimizerv4', 'itk::ExhaustiveOptimizerv4', 'itkExhaustiveOptimizerv4F', True, 'float'),
  ('ExhaustiveOptimizerv4', 'itk::ExhaustiveOptimizerv4', 'itkExhaustiveOptimizerv4D', True, 'double'),
  ('MultiGradientOptimizerv4Template', 'itk::MultiGradientOptimizerv4Template', 'itkMultiGradientOptimizerv4TemplateD', False, 'double'),
  ('MultiGradientOptimizerv4Template', 'itk::MultiGradientOptimizerv4Template', 'itkMultiGradientOptimizerv4TemplateF', False, 'float'),
  ('MultiStartOptimizerv4Template', 'itk::MultiStartOptimizerv4Template', 'itkMultiStartOptimizerv4TemplateD', False, 'double'),
  ('MultiStartOptimizerv4Template', 'itk::MultiStartOptimizerv4Template', 'itkMultiStartOptimizerv4TemplateF', False, 'float'),
  ('PowellOptimizerv4', 'itk::PowellOptimizerv4', 'itkPowellOptimizerv4D', True, 'double'),
  ('PowellOptimizerv4', 'itk::PowellOptimizerv4', 'itkPowellOptimizerv4F', True, 'float'),
  ('QuasiNewtonOptimizerv4Template', 'itk::QuasiNewtonOptimizerv4Template', 'itkQuasiNewtonOptimizerv4TemplateD', False, 'double'),
  ('QuasiNewtonOptimizerv4Template', 'itk::QuasiNewtonOptimizerv4Template', 'itkQuasiNewtonOptimizerv4TemplateF', False, 'float'),
  ('QuasiNewtonOptimizerv4', 'itk::QuasiNewtonOptimizerv4', 'itkQuasiNewtonOptimizerv4', True),
  ('RegularStepGradientDescentOptimizerv4', 'itk::RegularStepGradientDescentOptimizerv4', 'itkRegularStepGradientDescentOptimizerv4D', True, 'double'),
  ('RegularStepGradientDescentOptimizerv4', 'itk::RegularStepGradientDescentOptimizerv4', 'itkRegularStepGradientDescentOptimizerv4F', True, 'float'),
  ('OnePlusOneEvolutionaryOptimizerv4', 'itk::OnePlusOneEvolutionaryOptimizerv4', 'itkOnePlusOneEvolutionaryOptimizerv4D', True, 'double'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkAmoebaOptimizerv4', True, 'itk::AmoebaOptimizerv4'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkLBFGSOptimizerv4', True, 'itk::LBFGSOptimizerv4'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkLBFGSBOptimizerv4', True, 'itk::LBFGSBOptimizerv4'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkConjugateGradientLineSearchOptimizerv4TemplateD', True, 'itk::ConjugateGradientLineSearchOptimizerv4Template< double >'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkConjugateGradientLineSearchOptimizerv4TemplateF', True, 'itk::ConjugateGradientLineSearchOptimizerv4Template< float >'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkExhaustiveOptimizerv4D', True, 'itk::ExhaustiveOptimizerv4< double >'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkExhaustiveOptimizerv4F', True, 'itk::ExhaustiveOptimizerv4< float >'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkGradientDescentLineSearchOptimizerv4TemplateD', True, 'itk::GradientDescentLineSearchOptimizerv4Template< double >'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkGradientDescentLineSearchOptimizerv4TemplateF', True, 'itk::GradientDescentLineSearchOptimizerv4Template< float >'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkMultiGradientOptimizerv4TemplateD', True, 'itk::MultiGradientOptimizerv4Template< double >'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkMultiGradientOptimizerv4TemplateF', True, 'itk::MultiGradientOptimizerv4Template< float >'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkMultiStartOptimizerv4TemplateD', True, 'itk::MultiStartOptimizerv4Template< double >'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkMultiStartOptimizerv4TemplateF', True, 'itk::MultiStartOptimizerv4Template< float >'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkPowellOptimizerv4D', True, 'itk::PowellOptimizerv4< double >'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkPowellOptimizerv4F', True, 'itk::PowellOptimizerv4< float >'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkQuasiNewtonOptimizerv4TemplateD', True, 'itk::QuasiNewtonOptimizerv4Template< double >'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkQuasiNewtonOptimizerv4TemplateF', True, 'itk::QuasiNewtonOptimizerv4Template< float >'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkRegularStepGradientDescentOptimizerv4D', True, 'itk::RegularStepGradientDescentOptimizerv4< double >'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkRegularStepGradientDescentOptimizerv4F', True, 'itk::RegularStepGradientDescentOptimizerv4< float >'),
  ('CommandIterationUpdatev4', 'itk::CommandIterationUpdatev4', 'itkCommandIterationUpdatev4itkOnePlusOneEvolutionaryOptimizerv4D', True, 'itk::OnePlusOneEvolutionaryOptimizerv4< double >'),
  ('GradientDescentOptimizerBasev4Template', 'itk::GradientDescentOptimizerBasev4Template', 'itkGradientDescentOptimizerBasev4TemplateD', False, 'double'),
  ('GradientDescentOptimizerBasev4Template', 'itk::GradientDescentOptimizerBasev4Template', 'itkGradientDescentOptimizerBasev4TemplateF', False, 'float'),
  ('GradientDescentOptimizerv4Template', 'itk::GradientDescentOptimizerv4Template', 'itkGradientDescentOptimizerv4TemplateD', False, 'double'),
  ('GradientDescentOptimizerv4Template', 'itk::GradientDescentOptimizerv4Template', 'itkGradientDescentOptimizerv4TemplateF', False, 'float'),
  ('GradientDescentOptimizerv4', 'itk::GradientDescentOptimizerv4', 'itkGradientDescentOptimizerv4', True),
  ('LBFGS2Optimizerv4Enums', 'itk::LBFGS2Optimizerv4Enums', 'itkLBFGS2Optimizerv4Enums', False),
  ('LBFGS2Optimizerv4Template', 'itk::LBFGS2Optimizerv4Template', 'itkLBFGS2Optimizerv4TemplateD', False, 'double'),
  ('ObjectToObjectMetric', 'itk::ObjectToObjectMetric', 'itkObjectToObjectMetric22', True, '2,2'),
  ('ObjectToObjectMetric', 'itk::ObjectToObjectMetric', 'itkObjectToObjectMetric33', True, '3,3'),
  ('ObjectToObjectMetric', 'itk::ObjectToObjectMetric', 'itkObjectToObjectMetric44', True, '4,4'),
  ('ObjectToObjectMetricBaseTemplateEnums', 'itk::ObjectToObjectMetricBaseTemplateEnums', 'itkObjectToObjectMetricBaseTemplateEnums', False),
  ('ObjectToObjectMetricBaseTemplate', 'itk::ObjectToObjectMetricBaseTemplate', 'itkObjectToObjectMetricBaseTemplateD', False, 'double'),
  ('ObjectToObjectMetricBaseTemplate', 'itk::ObjectToObjectMetricBaseTemplate', 'itkObjectToObjectMetricBaseTemplateF', False, 'float'),
  ('ObjectToObjectOptimizerBaseTemplateEnums', 'itk::ObjectToObjectOptimizerBaseTemplateEnums', 'itkObjectToObjectOptimizerBaseTemplateEnums', False),
  ('ObjectToObjectOptimizerBaseTemplate', 'itk::ObjectToObjectOptimizerBaseTemplate', 'itkObjectToObjectOptimizerBaseTemplateF', False, 'float'),
  ('ObjectToObjectOptimizerBaseTemplate', 'itk::ObjectToObjectOptimizerBaseTemplate', 'itkObjectToObjectOptimizerBaseTemplateD', False, 'double'),
  ('OptimizerParameterScalesEstimatorTemplate', 'itk::OptimizerParameterScalesEstimatorTemplate', 'itkOptimizerParameterScalesEstimatorTemplateD', False, 'double'),
  ('OptimizerParameterScalesEstimatorTemplate', 'itk::OptimizerParameterScalesEstimatorTemplate', 'itkOptimizerParameterScalesEstimatorTemplateF', False, 'float'),
  ('SingleValuedCostFunctionv4Template', 'itk::SingleValuedCostFunctionv4Template', 'itkSingleValuedCostFunctionv4TemplateD', False, 'double'),
  ('SingleValuedCostFunctionv4Template', 'itk::SingleValuedCostFunctionv4Template', 'itkSingleValuedCostFunctionv4TemplateF', False, 'float'),
  ('SingleValuedNonLinearVnlOptimizerv4', 'itk::SingleValuedNonLinearVnlOptimizerv4', 'itkSingleValuedNonLinearVnlOptimizerv4', True),
)
factories = ()
