"""Camino AI Python SDK for location intelligence and spatial reasoning."""

from .client import CaminoAI
from .models import (
    Coordinate,
    TransportMode,
    QueryRequest,
    QueryResult,
    QueryResponse,
    Pagination,
    SearchRequest,
    SearchResult,
    SearchResponse,
    RelationshipRequest,
    RelationshipResponse,
    RouteSegmentInfo,
    RelationshipAnalysis,
    LocationWithPurpose,
    ContextRequest,
    ContextResponse,
    Waypoint,
    JourneyRequest,
    RouteSegment,
    JourneyResponse,
    RouteRequest,
    RouteSummary,
    RouteResponse,
    CaminoError,
    APIError,
    AuthenticationError,
    RateLimitError,
)
from .workflows import AreaExplorer, QuickChain, WorkflowPOI, WorkflowResult

__version__ = "0.1.0"
__all__ = [
    "CaminoAI",
    "Coordinate",
    "TransportMode",
    "QueryRequest",
    "QueryResult",
    "QueryResponse",
    "Pagination",
    "SearchRequest",
    "SearchResult",
    "SearchResponse",
    "RelationshipRequest",
    "RelationshipResponse",
    "RouteSegmentInfo",
    "RelationshipAnalysis",
    "LocationWithPurpose",
    "ContextRequest",
    "ContextResponse",
    "Waypoint",
    "JourneyRequest",
    "RouteSegment",
    "JourneyResponse",
    "RouteRequest",
    "RouteSummary",
    "RouteResponse",
    "CaminoError",
    "APIError",
    "AuthenticationError",
    "RateLimitError",
    # Workflow helpers
    "AreaExplorer",
    "QuickChain", 
    "WorkflowPOI",
    "WorkflowResult",
]