key = """-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIB4G7kExRZtRu6M6HH5/PqwojNIcP7apDm/QQHj81RiAoAoGCCqGSM49
AwEHoUQDQgAEoXMd0pBKPpzVnFc7CLEhr6Phmqgp4O4xivXhkNHF5Fp/n8uTgArg
DTXJqFSTrspgIR8gwnEnoQxqGPlJPN58/A==
-----END EC PRIVATE KEY-----
"""

cert = """-----BEGIN CERTIFICATE-----
MIIB6DCCAY8CFEYTiQLHe/7hOvoWmezEU7gOTdzEMAoGCCqGSM49BAMCMHcxCzAJ
BgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UE
CgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25hbCBVbml0MRQw
EgYDVQQDDAtDb21tb24gTmFtZTAeFw0yNTA5MjQwODE4MDlaFw0zNTA5MjIwODE4
MDlaMHcxCzAJBgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0
eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25h
bCBVbml0MRQwEgYDVQQDDAtDb21tb24gTmFtZTBZMBMGByqGSM49AgEGCCqGSM49
AwEHA0IABKFzHdKQSj6c1ZxXOwixIa+j4ZqoKeDuMYr14ZDRxeRaf5/Lk4AK4A01
yahUk67KYCEfIMJxJ6EMahj5STzefPwwCgYIKoZIzj0EAwIDRwAwRAIgHg8ZOmAd
xMqMAjvjQLL6uBBZTjcfsjGPL3jOcoo+AE4CIBmpWGdV8L3gS6ZMSoGgSZ34GYEt
NgsMG0dOOWzz6v/p
-----END CERTIFICATE-----
"""