depends = ('ITKPyBase', 'ITKImageGrid', 'ITKCommon', )
templates = (  ('Inverse1DFFTImageFilter', 'itk::Inverse1DFFTImageFilter', 'itkInverse1DFFTImageFilterICF2IF2', True, 'itk::Image< std::complex< float >,2 >, itk::Image< float,2 >'),
  ('Inverse1DFFTImageFilter', 'itk::Inverse1DFFTImageFilter', 'itkInverse1DFFTImageFilterICD2ID2', True, 'itk::Image< std::complex< double >,2 >, itk::Image< double,2 >'),
  ('Inverse1DFFTImageFilter', 'itk::Inverse1DFFTImageFilter', 'itkInverse1DFFTImageFilterICF3IF3', True, 'itk::Image< std::complex< float >,3 >, itk::Image< float,3 >'),
  ('Inverse1DFFTImageFilter', 'itk::Inverse1DFFTImageFilter', 'itkInverse1DFFTImageFilterICD3ID3', True, 'itk::Image< std::complex< double >,3 >, itk::Image< double,3 >'),
  ('Inverse1DFFTImageFilter', 'itk::Inverse1DFFTImageFilter', 'itkInverse1DFFTImageFilterICF4IF4', True, 'itk::Image< std::complex< float >,4 >, itk::Image< float,4 >'),
  ('Inverse1DFFTImageFilter', 'itk::Inverse1DFFTImageFilter', 'itkInverse1DFFTImageFilterICD4ID4', True, 'itk::Image< std::complex< double >,4 >, itk::Image< double,4 >'),
  ('Forward1DFFTImageFilter', 'itk::Forward1DFFTImageFilter', 'itkForward1DFFTImageFilterIF2ICF2', True, 'itk::Image< float,2 >, itk::Image< std::complex< float >,2 >'),
  ('Forward1DFFTImageFilter', 'itk::Forward1DFFTImageFilter', 'itkForward1DFFTImageFilterID2ICD2', True, 'itk::Image< double,2 >, itk::Image< std::complex< double >,2 >'),
  ('Forward1DFFTImageFilter', 'itk::Forward1DFFTImageFilter', 'itkForward1DFFTImageFilterIF3ICF3', True, 'itk::Image< float,3 >, itk::Image< std::complex< float >,3 >'),
  ('Forward1DFFTImageFilter', 'itk::Forward1DFFTImageFilter', 'itkForward1DFFTImageFilterID3ICD3', True, 'itk::Image< double,3 >, itk::Image< std::complex< double >,3 >'),
  ('Forward1DFFTImageFilter', 'itk::Forward1DFFTImageFilter', 'itkForward1DFFTImageFilterIF4ICF4', True, 'itk::Image< float,4 >, itk::Image< std::complex< float >,4 >'),
  ('Forward1DFFTImageFilter', 'itk::Forward1DFFTImageFilter', 'itkForward1DFFTImageFilterID4ICD4', True, 'itk::Image< double,4 >, itk::Image< std::complex< double >,4 >'),
  ('InverseFFTImageFilter', 'itk::InverseFFTImageFilter', 'itkInverseFFTImageFilterICF2IF2', True, 'itk::Image< std::complex< float >,2 >, itk::Image< float,2 >'),
  ('InverseFFTImageFilter', 'itk::InverseFFTImageFilter', 'itkInverseFFTImageFilterICD2ID2', True, 'itk::Image< std::complex< double >,2 >, itk::Image< double,2 >'),
  ('InverseFFTImageFilter', 'itk::InverseFFTImageFilter', 'itkInverseFFTImageFilterICF3IF3', True, 'itk::Image< std::complex< float >,3 >, itk::Image< float,3 >'),
  ('InverseFFTImageFilter', 'itk::InverseFFTImageFilter', 'itkInverseFFTImageFilterICD3ID3', True, 'itk::Image< std::complex< double >,3 >, itk::Image< double,3 >'),
  ('InverseFFTImageFilter', 'itk::InverseFFTImageFilter', 'itkInverseFFTImageFilterICF4IF4', True, 'itk::Image< std::complex< float >,4 >, itk::Image< float,4 >'),
  ('InverseFFTImageFilter', 'itk::InverseFFTImageFilter', 'itkInverseFFTImageFilterICD4ID4', True, 'itk::Image< std::complex< double >,4 >, itk::Image< double,4 >'),
  ('ForwardFFTImageFilter', 'itk::ForwardFFTImageFilter', 'itkForwardFFTImageFilterIF2ICF2', True, 'itk::Image< float,2 >, itk::Image< std::complex< float >,2 >'),
  ('ForwardFFTImageFilter', 'itk::ForwardFFTImageFilter', 'itkForwardFFTImageFilterID2ICD2', True, 'itk::Image< double,2 >, itk::Image< std::complex< double >,2 >'),
  ('ForwardFFTImageFilter', 'itk::ForwardFFTImageFilter', 'itkForwardFFTImageFilterIF3ICF3', True, 'itk::Image< float,3 >, itk::Image< std::complex< float >,3 >'),
  ('ForwardFFTImageFilter', 'itk::ForwardFFTImageFilter', 'itkForwardFFTImageFilterID3ICD3', True, 'itk::Image< double,3 >, itk::Image< std::complex< double >,3 >'),
  ('ForwardFFTImageFilter', 'itk::ForwardFFTImageFilter', 'itkForwardFFTImageFilterIF4ICF4', True, 'itk::Image< float,4 >, itk::Image< std::complex< float >,4 >'),
  ('ForwardFFTImageFilter', 'itk::ForwardFFTImageFilter', 'itkForwardFFTImageFilterID4ICD4', True, 'itk::Image< double,4 >, itk::Image< std::complex< double >,4 >'),
  ('ComplexToComplex1DFFTImageFilter', 'itk::ComplexToComplex1DFFTImageFilter', 'itkComplexToComplex1DFFTImageFilterICD2', True, 'itk::Image< std::complex< double >,2 >'),
  ('ComplexToComplex1DFFTImageFilter', 'itk::ComplexToComplex1DFFTImageFilter', 'itkComplexToComplex1DFFTImageFilterICD3', True, 'itk::Image< std::complex< double >,3 >'),
  ('ComplexToComplex1DFFTImageFilter', 'itk::ComplexToComplex1DFFTImageFilter', 'itkComplexToComplex1DFFTImageFilterICD4', True, 'itk::Image< std::complex< double >,4 >'),
  ('ComplexToComplex1DFFTImageFilter', 'itk::ComplexToComplex1DFFTImageFilter', 'itkComplexToComplex1DFFTImageFilterICF2', True, 'itk::Image< std::complex< float >,2 >'),
  ('ComplexToComplex1DFFTImageFilter', 'itk::ComplexToComplex1DFFTImageFilter', 'itkComplexToComplex1DFFTImageFilterICF3', True, 'itk::Image< std::complex< float >,3 >'),
  ('ComplexToComplex1DFFTImageFilter', 'itk::ComplexToComplex1DFFTImageFilter', 'itkComplexToComplex1DFFTImageFilterICF4', True, 'itk::Image< std::complex< float >,4 >'),
  ('ComplexToComplexFFTImageFilterEnums', 'itk::ComplexToComplexFFTImageFilterEnums', 'itkComplexToComplexFFTImageFilterEnums', False),
  ('ComplexToComplexFFTImageFilter', 'itk::ComplexToComplexFFTImageFilter', 'itkComplexToComplexFFTImageFilterICD2', True, 'itk::Image< std::complex< double >,2 >'),
  ('ComplexToComplexFFTImageFilter', 'itk::ComplexToComplexFFTImageFilter', 'itkComplexToComplexFFTImageFilterICD3', True, 'itk::Image< std::complex< double >,3 >'),
  ('ComplexToComplexFFTImageFilter', 'itk::ComplexToComplexFFTImageFilter', 'itkComplexToComplexFFTImageFilterICD4', True, 'itk::Image< std::complex< double >,4 >'),
  ('ComplexToComplexFFTImageFilter', 'itk::ComplexToComplexFFTImageFilter', 'itkComplexToComplexFFTImageFilterICF2', True, 'itk::Image< std::complex< float >,2 >'),
  ('ComplexToComplexFFTImageFilter', 'itk::ComplexToComplexFFTImageFilter', 'itkComplexToComplexFFTImageFilterICF3', True, 'itk::Image< std::complex< float >,3 >'),
  ('ComplexToComplexFFTImageFilter', 'itk::ComplexToComplexFFTImageFilter', 'itkComplexToComplexFFTImageFilterICF4', True, 'itk::Image< std::complex< float >,4 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIRGBUC2', True, 'itk::Image< itk::RGBPixel< unsigned char >,2 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIRGBUC3', True, 'itk::Image< itk::RGBPixel< unsigned char >,3 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIRGBUC4', True, 'itk::Image< itk::RGBPixel< unsigned char >,4 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIRGBAUC2', True, 'itk::Image< itk::RGBAPixel< unsigned char >,2 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIRGBAUC3', True, 'itk::Image< itk::RGBAPixel< unsigned char >,3 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIRGBAUC4', True, 'itk::Image< itk::RGBAPixel< unsigned char >,4 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIVF22', True, 'itk::Image< itk::Vector< float,2 >,2 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIVF23', True, 'itk::Image< itk::Vector< float,2 >,3 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIVF24', True, 'itk::Image< itk::Vector< float,2 >,4 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIVF32', True, 'itk::Image< itk::Vector< float,3 >,2 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIVF33', True, 'itk::Image< itk::Vector< float,3 >,3 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIVF34', True, 'itk::Image< itk::Vector< float,3 >,4 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIVF42', True, 'itk::Image< itk::Vector< float,4 >,2 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIVF43', True, 'itk::Image< itk::Vector< float,4 >,3 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIVF44', True, 'itk::Image< itk::Vector< float,4 >,4 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterICVF22', True, 'itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterICVF23', True, 'itk::Image< itk::CovariantVector< float,2 >,3 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterICVF24', True, 'itk::Image< itk::CovariantVector< float,2 >,4 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterICVF32', True, 'itk::Image< itk::CovariantVector< float,3 >,2 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterICVF33', True, 'itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterICVF34', True, 'itk::Image< itk::CovariantVector< float,3 >,4 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterICVF42', True, 'itk::Image< itk::CovariantVector< float,4 >,2 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterICVF43', True, 'itk::Image< itk::CovariantVector< float,4 >,3 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterICVF44', True, 'itk::Image< itk::CovariantVector< float,4 >,4 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterISS2', True, 'itk::Image< signed short,2 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterISS3', True, 'itk::Image< signed short,3 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterISS4', True, 'itk::Image< signed short,4 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIUC2', True, 'itk::Image< unsigned char,2 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIUC3', True, 'itk::Image< unsigned char,3 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIUC4', True, 'itk::Image< unsigned char,4 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIUS2', True, 'itk::Image< unsigned short,2 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIUS3', True, 'itk::Image< unsigned short,3 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIUS4', True, 'itk::Image< unsigned short,4 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIF2', True, 'itk::Image< float,2 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIF3', True, 'itk::Image< float,3 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterIF4', True, 'itk::Image< float,4 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterID2', True, 'itk::Image< double,2 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterID3', True, 'itk::Image< double,3 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterID4', True, 'itk::Image< double,4 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterICD2', True, 'itk::Image< std::complex< double >,2 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterICD3', True, 'itk::Image< std::complex< double >,3 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterICD4', True, 'itk::Image< std::complex< double >,4 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterICF2', True, 'itk::Image< std::complex< float >,2 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterICF3', True, 'itk::Image< std::complex< float >,3 >'),
  ('FFTPadImageFilter', 'itk::FFTPadImageFilter', 'itkFFTPadImageFilterICF4', True, 'itk::Image< std::complex< float >,4 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIRGBUC2IRGBUC2', True, 'itk::Image< itk::RGBPixel< unsigned char >,2 >, itk::Image< itk::RGBPixel< unsigned char >,2 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIRGBUC3IRGBUC3', True, 'itk::Image< itk::RGBPixel< unsigned char >,3 >, itk::Image< itk::RGBPixel< unsigned char >,3 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIRGBUC4IRGBUC4', True, 'itk::Image< itk::RGBPixel< unsigned char >,4 >, itk::Image< itk::RGBPixel< unsigned char >,4 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIRGBAUC2IRGBAUC2', True, 'itk::Image< itk::RGBAPixel< unsigned char >,2 >, itk::Image< itk::RGBAPixel< unsigned char >,2 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIRGBAUC3IRGBAUC3', True, 'itk::Image< itk::RGBAPixel< unsigned char >,3 >, itk::Image< itk::RGBAPixel< unsigned char >,3 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIRGBAUC4IRGBAUC4', True, 'itk::Image< itk::RGBAPixel< unsigned char >,4 >, itk::Image< itk::RGBAPixel< unsigned char >,4 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIVF22IVF22', True, 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< itk::Vector< float,2 >,2 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIVF23IVF23', True, 'itk::Image< itk::Vector< float,2 >,3 >, itk::Image< itk::Vector< float,2 >,3 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIVF24IVF24', True, 'itk::Image< itk::Vector< float,2 >,4 >, itk::Image< itk::Vector< float,2 >,4 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIVF32IVF32', True, 'itk::Image< itk::Vector< float,3 >,2 >, itk::Image< itk::Vector< float,3 >,2 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIVF33IVF33', True, 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< itk::Vector< float,3 >,3 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIVF34IVF34', True, 'itk::Image< itk::Vector< float,3 >,4 >, itk::Image< itk::Vector< float,3 >,4 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIVF42IVF42', True, 'itk::Image< itk::Vector< float,4 >,2 >, itk::Image< itk::Vector< float,4 >,2 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIVF43IVF43', True, 'itk::Image< itk::Vector< float,4 >,3 >, itk::Image< itk::Vector< float,4 >,3 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIVF44IVF44', True, 'itk::Image< itk::Vector< float,4 >,4 >, itk::Image< itk::Vector< float,4 >,4 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterICVF22ICVF22', True, 'itk::Image< itk::CovariantVector< float,2 >,2 >, itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterICVF23ICVF23', True, 'itk::Image< itk::CovariantVector< float,2 >,3 >, itk::Image< itk::CovariantVector< float,2 >,3 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterICVF24ICVF24', True, 'itk::Image< itk::CovariantVector< float,2 >,4 >, itk::Image< itk::CovariantVector< float,2 >,4 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterICVF32ICVF32', True, 'itk::Image< itk::CovariantVector< float,3 >,2 >, itk::Image< itk::CovariantVector< float,3 >,2 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterICVF33ICVF33', True, 'itk::Image< itk::CovariantVector< float,3 >,3 >, itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterICVF34ICVF34', True, 'itk::Image< itk::CovariantVector< float,3 >,4 >, itk::Image< itk::CovariantVector< float,3 >,4 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterICVF42ICVF42', True, 'itk::Image< itk::CovariantVector< float,4 >,2 >, itk::Image< itk::CovariantVector< float,4 >,2 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterICVF43ICVF43', True, 'itk::Image< itk::CovariantVector< float,4 >,3 >, itk::Image< itk::CovariantVector< float,4 >,3 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterICVF44ICVF44', True, 'itk::Image< itk::CovariantVector< float,4 >,4 >, itk::Image< itk::CovariantVector< float,4 >,4 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIUC4IUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned char,4 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIUS4IUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterICD2ICD2', True, 'itk::Image< std::complex< double >,2 >, itk::Image< std::complex< double >,2 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterICD3ICD3', True, 'itk::Image< std::complex< double >,3 >, itk::Image< std::complex< double >,3 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterICD4ICD4', True, 'itk::Image< std::complex< double >,4 >, itk::Image< std::complex< double >,4 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterICF2ICF2', True, 'itk::Image< std::complex< float >,2 >, itk::Image< std::complex< float >,2 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterICF3ICF3', True, 'itk::Image< std::complex< float >,3 >, itk::Image< std::complex< float >,3 >'),
  ('FFTShiftImageFilter', 'itk::FFTShiftImageFilter', 'itkFFTShiftImageFilterICF4ICF4', True, 'itk::Image< std::complex< float >,4 >, itk::Image< std::complex< float >,4 >'),
  ('FullToHalfHermitianImageFilter', 'itk::FullToHalfHermitianImageFilter', 'itkFullToHalfHermitianImageFilterICD2', True, 'itk::Image< std::complex< double >,2 >'),
  ('FullToHalfHermitianImageFilter', 'itk::FullToHalfHermitianImageFilter', 'itkFullToHalfHermitianImageFilterICD3', True, 'itk::Image< std::complex< double >,3 >'),
  ('FullToHalfHermitianImageFilter', 'itk::FullToHalfHermitianImageFilter', 'itkFullToHalfHermitianImageFilterICD4', True, 'itk::Image< std::complex< double >,4 >'),
  ('FullToHalfHermitianImageFilter', 'itk::FullToHalfHermitianImageFilter', 'itkFullToHalfHermitianImageFilterICF2', True, 'itk::Image< std::complex< float >,2 >'),
  ('FullToHalfHermitianImageFilter', 'itk::FullToHalfHermitianImageFilter', 'itkFullToHalfHermitianImageFilterICF3', True, 'itk::Image< std::complex< float >,3 >'),
  ('FullToHalfHermitianImageFilter', 'itk::FullToHalfHermitianImageFilter', 'itkFullToHalfHermitianImageFilterICF4', True, 'itk::Image< std::complex< float >,4 >'),
  ('HalfHermitianToRealInverseFFTImageFilter', 'itk::HalfHermitianToRealInverseFFTImageFilter', 'itkHalfHermitianToRealInverseFFTImageFilterICF2IF2', True, 'itk::Image< std::complex< float >,2 >, itk::Image< float,2 >'),
  ('HalfHermitianToRealInverseFFTImageFilter', 'itk::HalfHermitianToRealInverseFFTImageFilter', 'itkHalfHermitianToRealInverseFFTImageFilterICD2ID2', True, 'itk::Image< std::complex< double >,2 >, itk::Image< double,2 >'),
  ('HalfHermitianToRealInverseFFTImageFilter', 'itk::HalfHermitianToRealInverseFFTImageFilter', 'itkHalfHermitianToRealInverseFFTImageFilterICF3IF3', True, 'itk::Image< std::complex< float >,3 >, itk::Image< float,3 >'),
  ('HalfHermitianToRealInverseFFTImageFilter', 'itk::HalfHermitianToRealInverseFFTImageFilter', 'itkHalfHermitianToRealInverseFFTImageFilterICD3ID3', True, 'itk::Image< std::complex< double >,3 >, itk::Image< double,3 >'),
  ('HalfHermitianToRealInverseFFTImageFilter', 'itk::HalfHermitianToRealInverseFFTImageFilter', 'itkHalfHermitianToRealInverseFFTImageFilterICF4IF4', True, 'itk::Image< std::complex< float >,4 >, itk::Image< float,4 >'),
  ('HalfHermitianToRealInverseFFTImageFilter', 'itk::HalfHermitianToRealInverseFFTImageFilter', 'itkHalfHermitianToRealInverseFFTImageFilterICD4ID4', True, 'itk::Image< std::complex< double >,4 >, itk::Image< double,4 >'),
  ('HalfToFullHermitianImageFilter', 'itk::HalfToFullHermitianImageFilter', 'itkHalfToFullHermitianImageFilterICD2', True, 'itk::Image< std::complex< double >,2 >'),
  ('HalfToFullHermitianImageFilter', 'itk::HalfToFullHermitianImageFilter', 'itkHalfToFullHermitianImageFilterICD3', True, 'itk::Image< std::complex< double >,3 >'),
  ('HalfToFullHermitianImageFilter', 'itk::HalfToFullHermitianImageFilter', 'itkHalfToFullHermitianImageFilterICD4', True, 'itk::Image< std::complex< double >,4 >'),
  ('HalfToFullHermitianImageFilter', 'itk::HalfToFullHermitianImageFilter', 'itkHalfToFullHermitianImageFilterICF2', True, 'itk::Image< std::complex< float >,2 >'),
  ('HalfToFullHermitianImageFilter', 'itk::HalfToFullHermitianImageFilter', 'itkHalfToFullHermitianImageFilterICF3', True, 'itk::Image< std::complex< float >,3 >'),
  ('HalfToFullHermitianImageFilter', 'itk::HalfToFullHermitianImageFilter', 'itkHalfToFullHermitianImageFilterICF4', True, 'itk::Image< std::complex< float >,4 >'),
  ('RealToHalfHermitianForwardFFTImageFilter', 'itk::RealToHalfHermitianForwardFFTImageFilter', 'itkRealToHalfHermitianForwardFFTImageFilterIF2ICF2', True, 'itk::Image< float,2 >, itk::Image< std::complex< float >,2 >'),
  ('RealToHalfHermitianForwardFFTImageFilter', 'itk::RealToHalfHermitianForwardFFTImageFilter', 'itkRealToHalfHermitianForwardFFTImageFilterID2ICD2', True, 'itk::Image< double,2 >, itk::Image< std::complex< double >,2 >'),
  ('RealToHalfHermitianForwardFFTImageFilter', 'itk::RealToHalfHermitianForwardFFTImageFilter', 'itkRealToHalfHermitianForwardFFTImageFilterIF3ICF3', True, 'itk::Image< float,3 >, itk::Image< std::complex< float >,3 >'),
  ('RealToHalfHermitianForwardFFTImageFilter', 'itk::RealToHalfHermitianForwardFFTImageFilter', 'itkRealToHalfHermitianForwardFFTImageFilterID3ICD3', True, 'itk::Image< double,3 >, itk::Image< std::complex< double >,3 >'),
  ('RealToHalfHermitianForwardFFTImageFilter', 'itk::RealToHalfHermitianForwardFFTImageFilter', 'itkRealToHalfHermitianForwardFFTImageFilterIF4ICF4', True, 'itk::Image< float,4 >, itk::Image< std::complex< float >,4 >'),
  ('RealToHalfHermitianForwardFFTImageFilter', 'itk::RealToHalfHermitianForwardFFTImageFilter', 'itkRealToHalfHermitianForwardFFTImageFilterID4ICD4', True, 'itk::Image< double,4 >, itk::Image< std::complex< double >,4 >'),
  ('VnlComplexToComplex1DFFTImageFilter', 'itk::VnlComplexToComplex1DFFTImageFilter', 'itkVnlComplexToComplex1DFFTImageFilterICD2', True, 'itk::Image< std::complex< double >,2 >'),
  ('VnlComplexToComplex1DFFTImageFilter', 'itk::VnlComplexToComplex1DFFTImageFilter', 'itkVnlComplexToComplex1DFFTImageFilterICD3', True, 'itk::Image< std::complex< double >,3 >'),
  ('VnlComplexToComplex1DFFTImageFilter', 'itk::VnlComplexToComplex1DFFTImageFilter', 'itkVnlComplexToComplex1DFFTImageFilterICD4', True, 'itk::Image< std::complex< double >,4 >'),
  ('VnlComplexToComplex1DFFTImageFilter', 'itk::VnlComplexToComplex1DFFTImageFilter', 'itkVnlComplexToComplex1DFFTImageFilterICF2', True, 'itk::Image< std::complex< float >,2 >'),
  ('VnlComplexToComplex1DFFTImageFilter', 'itk::VnlComplexToComplex1DFFTImageFilter', 'itkVnlComplexToComplex1DFFTImageFilterICF3', True, 'itk::Image< std::complex< float >,3 >'),
  ('VnlComplexToComplex1DFFTImageFilter', 'itk::VnlComplexToComplex1DFFTImageFilter', 'itkVnlComplexToComplex1DFFTImageFilterICF4', True, 'itk::Image< std::complex< float >,4 >'),
  ('VnlComplexToComplexFFTImageFilter', 'itk::VnlComplexToComplexFFTImageFilter', 'itkVnlComplexToComplexFFTImageFilterICD2', True, 'itk::Image< std::complex< double >,2 >'),
  ('VnlComplexToComplexFFTImageFilter', 'itk::VnlComplexToComplexFFTImageFilter', 'itkVnlComplexToComplexFFTImageFilterICD3', True, 'itk::Image< std::complex< double >,3 >'),
  ('VnlComplexToComplexFFTImageFilter', 'itk::VnlComplexToComplexFFTImageFilter', 'itkVnlComplexToComplexFFTImageFilterICD4', True, 'itk::Image< std::complex< double >,4 >'),
  ('VnlComplexToComplexFFTImageFilter', 'itk::VnlComplexToComplexFFTImageFilter', 'itkVnlComplexToComplexFFTImageFilterICF2', True, 'itk::Image< std::complex< float >,2 >'),
  ('VnlComplexToComplexFFTImageFilter', 'itk::VnlComplexToComplexFFTImageFilter', 'itkVnlComplexToComplexFFTImageFilterICF3', True, 'itk::Image< std::complex< float >,3 >'),
  ('VnlComplexToComplexFFTImageFilter', 'itk::VnlComplexToComplexFFTImageFilter', 'itkVnlComplexToComplexFFTImageFilterICF4', True, 'itk::Image< std::complex< float >,4 >'),
  ('VnlFFTImageFilterInitFactory', 'itk::VnlFFTImageFilterInitFactory', 'itkVnlFFTImageFilterInitFactory', True),
  ('VnlForward1DFFTImageFilter', 'itk::VnlForward1DFFTImageFilter', 'itkVnlForward1DFFTImageFilterIF2ICF2', True, 'itk::Image< float,2 >, itk::Image< std::complex< float >,2 >'),
  ('VnlForward1DFFTImageFilter', 'itk::VnlForward1DFFTImageFilter', 'itkVnlForward1DFFTImageFilterID2ICD2', True, 'itk::Image< double,2 >, itk::Image< std::complex< double >,2 >'),
  ('VnlForward1DFFTImageFilter', 'itk::VnlForward1DFFTImageFilter', 'itkVnlForward1DFFTImageFilterIF3ICF3', True, 'itk::Image< float,3 >, itk::Image< std::complex< float >,3 >'),
  ('VnlForward1DFFTImageFilter', 'itk::VnlForward1DFFTImageFilter', 'itkVnlForward1DFFTImageFilterID3ICD3', True, 'itk::Image< double,3 >, itk::Image< std::complex< double >,3 >'),
  ('VnlForward1DFFTImageFilter', 'itk::VnlForward1DFFTImageFilter', 'itkVnlForward1DFFTImageFilterIF4ICF4', True, 'itk::Image< float,4 >, itk::Image< std::complex< float >,4 >'),
  ('VnlForward1DFFTImageFilter', 'itk::VnlForward1DFFTImageFilter', 'itkVnlForward1DFFTImageFilterID4ICD4', True, 'itk::Image< double,4 >, itk::Image< std::complex< double >,4 >'),
  ('VnlForwardFFTImageFilter', 'itk::VnlForwardFFTImageFilter', 'itkVnlForwardFFTImageFilterIF2ICF2', True, 'itk::Image< float,2 >, itk::Image< std::complex< float >,2 >'),
  ('VnlForwardFFTImageFilter', 'itk::VnlForwardFFTImageFilter', 'itkVnlForwardFFTImageFilterID2ICD2', True, 'itk::Image< double,2 >, itk::Image< std::complex< double >,2 >'),
  ('VnlForwardFFTImageFilter', 'itk::VnlForwardFFTImageFilter', 'itkVnlForwardFFTImageFilterIF3ICF3', True, 'itk::Image< float,3 >, itk::Image< std::complex< float >,3 >'),
  ('VnlForwardFFTImageFilter', 'itk::VnlForwardFFTImageFilter', 'itkVnlForwardFFTImageFilterID3ICD3', True, 'itk::Image< double,3 >, itk::Image< std::complex< double >,3 >'),
  ('VnlForwardFFTImageFilter', 'itk::VnlForwardFFTImageFilter', 'itkVnlForwardFFTImageFilterIF4ICF4', True, 'itk::Image< float,4 >, itk::Image< std::complex< float >,4 >'),
  ('VnlForwardFFTImageFilter', 'itk::VnlForwardFFTImageFilter', 'itkVnlForwardFFTImageFilterID4ICD4', True, 'itk::Image< double,4 >, itk::Image< std::complex< double >,4 >'),
  ('VnlHalfHermitianToRealInverseFFTImageFilter', 'itk::VnlHalfHermitianToRealInverseFFTImageFilter', 'itkVnlHalfHermitianToRealInverseFFTImageFilterICF2IF2', True, 'itk::Image< std::complex< float >,2 >, itk::Image< float,2 >'),
  ('VnlHalfHermitianToRealInverseFFTImageFilter', 'itk::VnlHalfHermitianToRealInverseFFTImageFilter', 'itkVnlHalfHermitianToRealInverseFFTImageFilterICD2ID2', True, 'itk::Image< std::complex< double >,2 >, itk::Image< double,2 >'),
  ('VnlHalfHermitianToRealInverseFFTImageFilter', 'itk::VnlHalfHermitianToRealInverseFFTImageFilter', 'itkVnlHalfHermitianToRealInverseFFTImageFilterICF3IF3', True, 'itk::Image< std::complex< float >,3 >, itk::Image< float,3 >'),
  ('VnlHalfHermitianToRealInverseFFTImageFilter', 'itk::VnlHalfHermitianToRealInverseFFTImageFilter', 'itkVnlHalfHermitianToRealInverseFFTImageFilterICD3ID3', True, 'itk::Image< std::complex< double >,3 >, itk::Image< double,3 >'),
  ('VnlHalfHermitianToRealInverseFFTImageFilter', 'itk::VnlHalfHermitianToRealInverseFFTImageFilter', 'itkVnlHalfHermitianToRealInverseFFTImageFilterICF4IF4', True, 'itk::Image< std::complex< float >,4 >, itk::Image< float,4 >'),
  ('VnlHalfHermitianToRealInverseFFTImageFilter', 'itk::VnlHalfHermitianToRealInverseFFTImageFilter', 'itkVnlHalfHermitianToRealInverseFFTImageFilterICD4ID4', True, 'itk::Image< std::complex< double >,4 >, itk::Image< double,4 >'),
  ('VnlInverse1DFFTImageFilter', 'itk::VnlInverse1DFFTImageFilter', 'itkVnlInverse1DFFTImageFilterICF2IF2', True, 'itk::Image< std::complex< float >,2 >, itk::Image< float,2 >'),
  ('VnlInverse1DFFTImageFilter', 'itk::VnlInverse1DFFTImageFilter', 'itkVnlInverse1DFFTImageFilterICD2ID2', True, 'itk::Image< std::complex< double >,2 >, itk::Image< double,2 >'),
  ('VnlInverse1DFFTImageFilter', 'itk::VnlInverse1DFFTImageFilter', 'itkVnlInverse1DFFTImageFilterICF3IF3', True, 'itk::Image< std::complex< float >,3 >, itk::Image< float,3 >'),
  ('VnlInverse1DFFTImageFilter', 'itk::VnlInverse1DFFTImageFilter', 'itkVnlInverse1DFFTImageFilterICD3ID3', True, 'itk::Image< std::complex< double >,3 >, itk::Image< double,3 >'),
  ('VnlInverse1DFFTImageFilter', 'itk::VnlInverse1DFFTImageFilter', 'itkVnlInverse1DFFTImageFilterICF4IF4', True, 'itk::Image< std::complex< float >,4 >, itk::Image< float,4 >'),
  ('VnlInverse1DFFTImageFilter', 'itk::VnlInverse1DFFTImageFilter', 'itkVnlInverse1DFFTImageFilterICD4ID4', True, 'itk::Image< std::complex< double >,4 >, itk::Image< double,4 >'),
  ('VnlInverseFFTImageFilter', 'itk::VnlInverseFFTImageFilter', 'itkVnlInverseFFTImageFilterICF2IF2', True, 'itk::Image< std::complex< float >,2 >, itk::Image< float,2 >'),
  ('VnlInverseFFTImageFilter', 'itk::VnlInverseFFTImageFilter', 'itkVnlInverseFFTImageFilterICD2ID2', True, 'itk::Image< std::complex< double >,2 >, itk::Image< double,2 >'),
  ('VnlInverseFFTImageFilter', 'itk::VnlInverseFFTImageFilter', 'itkVnlInverseFFTImageFilterICF3IF3', True, 'itk::Image< std::complex< float >,3 >, itk::Image< float,3 >'),
  ('VnlInverseFFTImageFilter', 'itk::VnlInverseFFTImageFilter', 'itkVnlInverseFFTImageFilterICD3ID3', True, 'itk::Image< std::complex< double >,3 >, itk::Image< double,3 >'),
  ('VnlInverseFFTImageFilter', 'itk::VnlInverseFFTImageFilter', 'itkVnlInverseFFTImageFilterICF4IF4', True, 'itk::Image< std::complex< float >,4 >, itk::Image< float,4 >'),
  ('VnlInverseFFTImageFilter', 'itk::VnlInverseFFTImageFilter', 'itkVnlInverseFFTImageFilterICD4ID4', True, 'itk::Image< std::complex< double >,4 >, itk::Image< double,4 >'),
  ('VnlRealToHalfHermitianForwardFFTImageFilter', 'itk::VnlRealToHalfHermitianForwardFFTImageFilter', 'itkVnlRealToHalfHermitianForwardFFTImageFilterIF2ICF2', True, 'itk::Image< float,2 >, itk::Image< std::complex< float >,2 >'),
  ('VnlRealToHalfHermitianForwardFFTImageFilter', 'itk::VnlRealToHalfHermitianForwardFFTImageFilter', 'itkVnlRealToHalfHermitianForwardFFTImageFilterID2ICD2', True, 'itk::Image< double,2 >, itk::Image< std::complex< double >,2 >'),
  ('VnlRealToHalfHermitianForwardFFTImageFilter', 'itk::VnlRealToHalfHermitianForwardFFTImageFilter', 'itkVnlRealToHalfHermitianForwardFFTImageFilterIF3ICF3', True, 'itk::Image< float,3 >, itk::Image< std::complex< float >,3 >'),
  ('VnlRealToHalfHermitianForwardFFTImageFilter', 'itk::VnlRealToHalfHermitianForwardFFTImageFilter', 'itkVnlRealToHalfHermitianForwardFFTImageFilterID3ICD3', True, 'itk::Image< double,3 >, itk::Image< std::complex< double >,3 >'),
  ('VnlRealToHalfHermitianForwardFFTImageFilter', 'itk::VnlRealToHalfHermitianForwardFFTImageFilter', 'itkVnlRealToHalfHermitianForwardFFTImageFilterIF4ICF4', True, 'itk::Image< float,4 >, itk::Image< std::complex< float >,4 >'),
  ('VnlRealToHalfHermitianForwardFFTImageFilter', 'itk::VnlRealToHalfHermitianForwardFFTImageFilter', 'itkVnlRealToHalfHermitianForwardFFTImageFilterID4ICD4', True, 'itk::Image< double,4 >, itk::Image< std::complex< double >,4 >'),
)
factories = (("FFTImageFilterInit","Vnl"),)
