# Generated by Django 5.1.8 on 2025-08-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_entraid_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='report_recipients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='settings',
            name='report_sender',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
