# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.


import collections

from sys import version_info as _version_info
if _version_info < (3, 7, 0):
    raise RuntimeError("Python 3.7 or later required")

from . import _ITKCommonPython


from . import _ITKQuadEdgeMeshFilteringPython



from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _itkCleanQuadEdgeMeshFilterPython
else:
    import _itkCleanQuadEdgeMeshFilterPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


if _swig_python_version_info[0:2] >= (3, 3):
    import collections.abc
else:
    import collections

import itk.itkQuadEdgeMeshToQuadEdgeMeshFilterPython
import itk.itkQuadEdgeMeshBasePython
import itk.ITKCommonBasePython
import itk.itkMatrixPython
import itk.vnl_matrix_fixedPython
import itk.vnl_matrixPython
import itk.stdcomplexPython
import itk.pyBasePython
import itk.vnl_vectorPython
import itk.itkPointPython
import itk.vnl_vector_refPython
import itk.itkFixedArrayPython
import itk.itkVectorPython
import itk.itkCovariantVectorPython
import itk.itkQuadEdgeMeshPointPython
import itk.itkGeometricalQuadEdgePython
import itk.itkQuadEdgePython
import itk.itkImagePython
import itk.itkIndexPython
import itk.itkOffsetPython
import itk.itkSizePython
import itk.itkImageRegionPython
import itk.itkRGBAPixelPython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkRGBPixelPython
import itk.itkQuadEdgeMeshLineCellPython
import itk.itkArrayPython
import itk.itkQuadEdgeCellTraitsInfoPython
import itk.itkVectorContainerPython
import itk.itkContinuousIndexPython
import itk.itkMapContainerPython

def itkCleanQuadEdgeMeshFilterQEMD2_New():
    return itkCleanQuadEdgeMeshFilterQEMD2.New()

class itkCleanQuadEdgeMeshFilterQEMD2(itk.itkQuadEdgeMeshToQuadEdgeMeshFilterPython.itkQuadEdgeMeshToQuadEdgeMeshFilterQEMD2QEMD2):
    r"""Proxy of C++ itkCleanQuadEdgeMeshFilterQEMD2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkCleanQuadEdgeMeshFilterQEMD2_Pointer"""
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD2___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkCleanQuadEdgeMeshFilterQEMD2_Pointer"""
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD2_Clone(self)

    def SetAbsoluteTolerance(self, _arg):
        r"""
        SetAbsoluteTolerance(self, _arg)

        Parameters
        ----------
        _arg: float

        """
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD2_SetAbsoluteTolerance(self, _arg)

    def GetAbsoluteTolerance(self):
        r"""GetAbsoluteTolerance(self) -> float"""
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD2_GetAbsoluteTolerance(self)

    def SetRelativeTolerance(self, _arg):
        r"""
        SetRelativeTolerance(self, _arg)

        Parameters
        ----------
        _arg: float

        """
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD2_SetRelativeTolerance(self, _arg)

    def GetRelativeTolerance(self):
        r"""GetRelativeTolerance(self) -> float"""
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD2_GetRelativeTolerance(self)
    __swig_destroy__ = _itkCleanQuadEdgeMeshFilterPython.delete_itkCleanQuadEdgeMeshFilterQEMD2

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkCleanQuadEdgeMeshFilterQEMD2

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD2_cast(obj)

    def New(*args, **kargs):
        """New() -> itkCleanQuadEdgeMeshFilterQEMD2

        Create a new object of the class itkCleanQuadEdgeMeshFilterQEMD2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkCleanQuadEdgeMeshFilterQEMD2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkCleanQuadEdgeMeshFilterQEMD2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkCleanQuadEdgeMeshFilterQEMD2.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkCleanQuadEdgeMeshFilterQEMD2 in _itkCleanQuadEdgeMeshFilterPython:
_itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD2_swigregister(itkCleanQuadEdgeMeshFilterQEMD2)

def itkCleanQuadEdgeMeshFilterQEMD3_New():
    return itkCleanQuadEdgeMeshFilterQEMD3.New()

class itkCleanQuadEdgeMeshFilterQEMD3(itk.itkQuadEdgeMeshToQuadEdgeMeshFilterPython.itkQuadEdgeMeshToQuadEdgeMeshFilterQEMD3QEMD3):
    r"""Proxy of C++ itkCleanQuadEdgeMeshFilterQEMD3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkCleanQuadEdgeMeshFilterQEMD3_Pointer"""
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD3___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkCleanQuadEdgeMeshFilterQEMD3_Pointer"""
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD3_Clone(self)

    def SetAbsoluteTolerance(self, _arg):
        r"""
        SetAbsoluteTolerance(self, _arg)

        Parameters
        ----------
        _arg: float

        """
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD3_SetAbsoluteTolerance(self, _arg)

    def GetAbsoluteTolerance(self):
        r"""GetAbsoluteTolerance(self) -> float"""
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD3_GetAbsoluteTolerance(self)

    def SetRelativeTolerance(self, _arg):
        r"""
        SetRelativeTolerance(self, _arg)

        Parameters
        ----------
        _arg: float

        """
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD3_SetRelativeTolerance(self, _arg)

    def GetRelativeTolerance(self):
        r"""GetRelativeTolerance(self) -> float"""
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD3_GetRelativeTolerance(self)
    __swig_destroy__ = _itkCleanQuadEdgeMeshFilterPython.delete_itkCleanQuadEdgeMeshFilterQEMD3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkCleanQuadEdgeMeshFilterQEMD3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD3_cast(obj)

    def New(*args, **kargs):
        """New() -> itkCleanQuadEdgeMeshFilterQEMD3

        Create a new object of the class itkCleanQuadEdgeMeshFilterQEMD3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkCleanQuadEdgeMeshFilterQEMD3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkCleanQuadEdgeMeshFilterQEMD3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkCleanQuadEdgeMeshFilterQEMD3.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkCleanQuadEdgeMeshFilterQEMD3 in _itkCleanQuadEdgeMeshFilterPython:
_itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD3_swigregister(itkCleanQuadEdgeMeshFilterQEMD3)

def itkCleanQuadEdgeMeshFilterQEMD4_New():
    return itkCleanQuadEdgeMeshFilterQEMD4.New()

class itkCleanQuadEdgeMeshFilterQEMD4(itk.itkQuadEdgeMeshToQuadEdgeMeshFilterPython.itkQuadEdgeMeshToQuadEdgeMeshFilterQEMD4QEMD4):
    r"""Proxy of C++ itkCleanQuadEdgeMeshFilterQEMD4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkCleanQuadEdgeMeshFilterQEMD4_Pointer"""
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD4___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkCleanQuadEdgeMeshFilterQEMD4_Pointer"""
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD4_Clone(self)

    def SetAbsoluteTolerance(self, _arg):
        r"""
        SetAbsoluteTolerance(self, _arg)

        Parameters
        ----------
        _arg: float

        """
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD4_SetAbsoluteTolerance(self, _arg)

    def GetAbsoluteTolerance(self):
        r"""GetAbsoluteTolerance(self) -> float"""
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD4_GetAbsoluteTolerance(self)

    def SetRelativeTolerance(self, _arg):
        r"""
        SetRelativeTolerance(self, _arg)

        Parameters
        ----------
        _arg: float

        """
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD4_SetRelativeTolerance(self, _arg)

    def GetRelativeTolerance(self):
        r"""GetRelativeTolerance(self) -> float"""
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD4_GetRelativeTolerance(self)
    __swig_destroy__ = _itkCleanQuadEdgeMeshFilterPython.delete_itkCleanQuadEdgeMeshFilterQEMD4

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkCleanQuadEdgeMeshFilterQEMD4

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD4_cast(obj)

    def New(*args, **kargs):
        """New() -> itkCleanQuadEdgeMeshFilterQEMD4

        Create a new object of the class itkCleanQuadEdgeMeshFilterQEMD4 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkCleanQuadEdgeMeshFilterQEMD4.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkCleanQuadEdgeMeshFilterQEMD4.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkCleanQuadEdgeMeshFilterQEMD4.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkCleanQuadEdgeMeshFilterQEMD4 in _itkCleanQuadEdgeMeshFilterPython:
_itkCleanQuadEdgeMeshFilterPython.itkCleanQuadEdgeMeshFilterQEMD4_swigregister(itkCleanQuadEdgeMeshFilterQEMD4)

from itk.support import helpers
import itk.support.types as itkt
from typing import Union
from collections.abc import Sequence

@helpers.accept_array_like_xarray_torch
def clean_quad_edge_mesh_filter(*args: itkt.Mesh,  absolute_tolerance: float=..., relative_tolerance: float=..., output: itkt.QuadEdgeMesh=...,**kwargs)-> itkt.MeshSourceReturn:
    """Functional interface for CleanQuadEdgeMeshFilter"""
    import itk

    kwarg_typehints = { 'absolute_tolerance':absolute_tolerance,'relative_tolerance':relative_tolerance,'output':output }
    specified_kwarg_typehints = { k:v for (k,v) in kwarg_typehints.items() if kwarg_typehints[k] is not ... }
    kwargs.update(specified_kwarg_typehints)


    instance = itk.CleanQuadEdgeMeshFilter.New(*args, **kwargs)

    return instance.__internal_call__()

def clean_quad_edge_mesh_filter_init_docstring():
    import itk
    from itk.support import template_class

    filter_class = itk.ITKQuadEdgeMeshFiltering.CleanQuadEdgeMeshFilter
    clean_quad_edge_mesh_filter.process_object = filter_class
    is_template = isinstance(filter_class, template_class.itkTemplate)
    if is_template:
        filter_object = filter_class.values()[0]
    else:
        filter_object = filter_class

    clean_quad_edge_mesh_filter.__doc__ = filter_object.__doc__



