"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kintsugi_tax_platform_sdk.types import BaseModel
from kintsugi_tax_platform_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetCustomerByExternalIDV1CustomersExternalExternalIDGetRequestTypedDict(
    TypedDict
):
    external_id: str
    r"""The external identifier of the customer to retrieve."""


class GetCustomerByExternalIDV1CustomersExternalExternalIDGetRequest(BaseModel):
    external_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The external identifier of the customer to retrieve."""
