"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .creditnotecreate import CreditNoteCreate, CreditNoteCreateTypedDict
from kintsugi_tax_platform_sdk.types import BaseModel
from kintsugi_tax_platform_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from typing_extensions import Annotated, TypedDict


class PUTUpdateCreditNoteByTransactionIDRequestTypedDict(TypedDict):
    original_transaction_id: str
    credit_note_id: str
    credit_note_create: CreditNoteCreateTypedDict


class PUTUpdateCreditNoteByTransactionIDRequest(BaseModel):
    original_transaction_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    credit_note_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    credit_note_create: Annotated[
        CreditNoteCreate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
