"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class RegistrationTypeEnum(str, Enum):
    EU_OSS = "EU_OSS"
    OTHER = "OTHER"
