import { EventEmitter } from '../../stencil-public-runtime';
import { LimeWebComponentPlatform, LimeWebComponentContext } from '@limetech/lime-web-components';
import { ISession } from '../../types/Session';
import { ICustomField } from '../../types/CustomField';
import { IListItem } from '../../types/ListItem';
import { ITemplateRole } from "../../types/TemplateRole";
export declare class LayoutSelectFile {
    platform: LimeWebComponentPlatform;
    context: LimeWebComponentContext;
    session: ISession;
    selectedTemplate: IListItem;
    selectedLimeDocument: IListItem;
    customFields: ICustomField[];
    templateRoles: ITemplateRole[];
    setCustomFields: EventEmitter;
    setTemplateRoles: EventEmitter;
    private errorHandler;
    private isLoadingTemplates;
    private isLoadingProps;
    private templates;
    private isLoadingFields;
    private isLoadingLimeDocuments;
    private limeDocuments;
    private openSection;
    private tableData;
    private currentTab;
    private gaMergeFields;
    constructor();
    render(): any[];
    componentWillLoad(): Promise<void>;
    private onChangeSection;
    private loadTemplates;
    private loadLimeDocuments;
    private onChange;
    private loadTemplateFields;
    private loadObjectProps;
    private loadTemplateRoles;
    private setAvailableFields;
    private setFields;
    private setRoles;
    onChangeTemplate(data: IListItem): void;
    private setTemplates;
    onChangeDocument(data: IListItem): void;
    private mapField;
    private setLimeDocuments;
    private getSelectedListItems;
    updateFieldValue(event: any): void;
    private onActivateRow;
    private copyToClipboard;
}
