from setuptools import setup, find_packages

setup(
    name="rrai",
    version="1.0.0",
    description="A Python library",
    long_description="Yes you are thinking right!",
    long_description_content_type="text/plain",
    author="Manny",
    author_email="rrai@example.com",
    url="https://github.com/rrai",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Education",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research", 
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Education",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    python_requires=">=3.6",
    install_requires=[],
    project_urls={
        "Bug Reports": "https://github.com/rrai/issues",
        "Source": "https://github.com/rrai",
    },
)