# pylint: disable=unused-argument
# pylint: disable=too-many-public-methods
# pylint: disable=missing-function-docstring
# pylint: disable=missing-module-docstring
# pylint: disable=missing-class-docstring
from typing import Any, Dict, List, Optional, Union

class Colors:
    BLACK: str
    RED: str
    GREEN: str
    BROWN: str
    BLUE: str
    PURPLE: str
    CYAN: str
    LIGHT_GRAY: str
    DARK_GRAY: str
    LIGHT_RED: str
    LIGHT_GREEN: str
    YELLOW: str
    LIGHT_BLUE: str
    LIGHT_PURPLE: str
    LIGHT_CYAN: str
    LIGHT_WHITE: str
    BOLD: str
    FAINT: str
    ITALIC: str
    UNDERLINE: str
    BLINK: str
    NEGATIVE: str
    CROSSED: str

    CYAN_BG: str
    RED_BG: str
    MAGENTA_BG: str
    RESET: str

    all_colors: List[str]

    @staticmethod
    def black(text: str) -> str: ...
    @staticmethod
    def red(text: str) -> str: ...
    @staticmethod
    def green(text: str) -> str: ...
    @staticmethod
    def brown(text: str) -> str: ...
    @staticmethod
    def blue(text: str) -> str: ...
    @staticmethod
    def purple(text: str) -> str: ...
    @staticmethod
    def cyan(text: str) -> str: ...
    @staticmethod
    def light_gray(text: str) -> str: ...
    @staticmethod
    def dark_gray(text: str) -> str: ...
    @staticmethod
    def light_red(text: str) -> str: ...
    @staticmethod
    def light_green(text: str) -> str: ...
    @staticmethod
    def yellow(text: str) -> str: ...
    @staticmethod
    def light_blue(text: str) -> str: ...
    @staticmethod
    def light_purple(text: str) -> str: ...
    @staticmethod
    def light_cyan(text: str) -> str: ...
    @staticmethod
    def light_white(text: str) -> str: ...
    @staticmethod
    def bold(text: str) -> str: ...
    @staticmethod
    def faint(text: str) -> str: ...
    @staticmethod
    def italic(text: str) -> str: ...
    @staticmethod
    def underline(text: str) -> str: ...
    @staticmethod
    def blink(text: str) -> str: ...
    @staticmethod
    def negative(text: str) -> str: ...
    @staticmethod
    def crossed(text: str) -> str: ...
    @staticmethod
    def cyan_bg(text: str) -> str: ...
    @staticmethod
    def red_bg(text: str) -> str: ...
    @staticmethod
    def magenta_bg(text: str) -> str: ...
    @staticmethod
    def reset(text: str) -> str: ...
    @staticmethod
    def render(text: Union[str, Any], style: Union[str, List[str]]) -> str: ...
    @staticmethod
    def _create_class_methods() -> None: ...

def render(text: Union[str, Any], styles: Union[str, List[str]]) -> str: ...
def print_diff(
    title: str, labels: Dict[str, Any], label_colors: Optional[List[str]] = None, title_color: Optional[str] = None
): ...
def zip_render(labels: Dict[str, Any], label_colors: List[str], diff_labels: Optional[List[str]] = None): ...
