"""
biosim-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from biosim_client.api.biosim.models.hdf5_group import HDF5Group


class TestHDF5Group(unittest.TestCase):
    """HDF5Group unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HDF5Group:
        """Test HDF5Group
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `HDF5Group`
        """
        model = HDF5Group()
        if include_optional:
            return HDF5Group(
                name = '',
                attributes = [
                    biosim_client.api.biosim.models.hdf5_attribute.HDF5Attribute(
                        key = '',
                        value = null, )
                    ],
                datasets = [
                    biosim_client.api.biosim.models.hdf5_dataset.HDF5Dataset(
                        name = '',
                        shape = [
                            56
                            ],
                        attributes = [
                            biosim_client.api.biosim.models.hdf5_attribute.HDF5Attribute(
                                key = '',
                                value = null, )
                            ], )
                    ]
            )
        else:
            return HDF5Group(
                name = '',
                attributes = [
                    biosim_client.api.biosim.models.hdf5_attribute.HDF5Attribute(
                        key = '',
                        value = null, )
                    ],
                datasets = [
                    biosim_client.api.biosim.models.hdf5_dataset.HDF5Dataset(
                        name = '',
                        shape = [
                            56
                            ],
                        attributes = [
                            biosim_client.api.biosim.models.hdf5_attribute.HDF5Attribute(
                                key = '',
                                value = null, )
                            ], )
                    ],
        )
        """

    def testHDF5Group(self):
        """Test HDF5Group"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
