depends = ('ITKPyBase', 'ITKNarrowBand', 'ITKImageLabel', 'ITKBinaryMathematicalMorphology', )
templates = (  ('ApproximateSignedDistanceMapImageFilter', 'itk::ApproximateSignedDistanceMapImageFilter', 'itkApproximateSignedDistanceMapImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('ApproximateSignedDistanceMapImageFilter', 'itk::ApproximateSignedDistanceMapImageFilter', 'itkApproximateSignedDistanceMapImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('ApproximateSignedDistanceMapImageFilter', 'itk::ApproximateSignedDistanceMapImageFilter', 'itkApproximateSignedDistanceMapImageFilterISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('ApproximateSignedDistanceMapImageFilter', 'itk::ApproximateSignedDistanceMapImageFilter', 'itkApproximateSignedDistanceMapImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('ApproximateSignedDistanceMapImageFilter', 'itk::ApproximateSignedDistanceMapImageFilter', 'itkApproximateSignedDistanceMapImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('ApproximateSignedDistanceMapImageFilter', 'itk::ApproximateSignedDistanceMapImageFilter', 'itkApproximateSignedDistanceMapImageFilterIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('ApproximateSignedDistanceMapImageFilter', 'itk::ApproximateSignedDistanceMapImageFilter', 'itkApproximateSignedDistanceMapImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('ApproximateSignedDistanceMapImageFilter', 'itk::ApproximateSignedDistanceMapImageFilter', 'itkApproximateSignedDistanceMapImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('ApproximateSignedDistanceMapImageFilter', 'itk::ApproximateSignedDistanceMapImageFilter', 'itkApproximateSignedDistanceMapImageFilterID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterIUC2IF2', True, 'itk::Image< unsigned char,2 >, itk::Image< float,2 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterIUC3IF3', True, 'itk::Image< unsigned char,3 >, itk::Image< float,3 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterIUC4IF4', True, 'itk::Image< unsigned char,4 >, itk::Image< float,4 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterIUC2ID2', True, 'itk::Image< unsigned char,2 >, itk::Image< double,2 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterIUC3ID3', True, 'itk::Image< unsigned char,3 >, itk::Image< double,3 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterIUC4ID4', True, 'itk::Image< unsigned char,4 >, itk::Image< double,4 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterIUS2IF2', True, 'itk::Image< unsigned short,2 >, itk::Image< float,2 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterIUS3IF3', True, 'itk::Image< unsigned short,3 >, itk::Image< float,3 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterIUS4IF4', True, 'itk::Image< unsigned short,4 >, itk::Image< float,4 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterIUS2ID2', True, 'itk::Image< unsigned short,2 >, itk::Image< double,2 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterIUS3ID3', True, 'itk::Image< unsigned short,3 >, itk::Image< double,3 >'),
  ('ContourDirectedMeanDistanceImageFilter', 'itk::ContourDirectedMeanDistanceImageFilter', 'itkContourDirectedMeanDistanceImageFilterIUS4ID4', True, 'itk::Image< unsigned short,4 >, itk::Image< double,4 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterIUC2IF2', True, 'itk::Image< unsigned char,2 >, itk::Image< float,2 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterIUC3IF3', True, 'itk::Image< unsigned char,3 >, itk::Image< float,3 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterIUC4IF4', True, 'itk::Image< unsigned char,4 >, itk::Image< float,4 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterIUC2ID2', True, 'itk::Image< unsigned char,2 >, itk::Image< double,2 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterIUC3ID3', True, 'itk::Image< unsigned char,3 >, itk::Image< double,3 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterIUC4ID4', True, 'itk::Image< unsigned char,4 >, itk::Image< double,4 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterIUS2IF2', True, 'itk::Image< unsigned short,2 >, itk::Image< float,2 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterIUS3IF3', True, 'itk::Image< unsigned short,3 >, itk::Image< float,3 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterIUS4IF4', True, 'itk::Image< unsigned short,4 >, itk::Image< float,4 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterIUS2ID2', True, 'itk::Image< unsigned short,2 >, itk::Image< double,2 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterIUS3ID3', True, 'itk::Image< unsigned short,3 >, itk::Image< double,3 >'),
  ('ContourMeanDistanceImageFilter', 'itk::ContourMeanDistanceImageFilter', 'itkContourMeanDistanceImageFilterIUS4ID4', True, 'itk::Image< unsigned short,4 >, itk::Image< double,4 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUC4IUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned char,4 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUS4IUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUC2IF2', True, 'itk::Image< unsigned char,2 >, itk::Image< float,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUC3IF3', True, 'itk::Image< unsigned char,3 >, itk::Image< float,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUC4IF4', True, 'itk::Image< unsigned char,4 >, itk::Image< float,4 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUC2ID2', True, 'itk::Image< unsigned char,2 >, itk::Image< double,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUC3ID3', True, 'itk::Image< unsigned char,3 >, itk::Image< double,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUC4ID4', True, 'itk::Image< unsigned char,4 >, itk::Image< double,4 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUS2IF2', True, 'itk::Image< unsigned short,2 >, itk::Image< float,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUS3IF3', True, 'itk::Image< unsigned short,3 >, itk::Image< float,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUS4IF4', True, 'itk::Image< unsigned short,4 >, itk::Image< float,4 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUS2ID2', True, 'itk::Image< unsigned short,2 >, itk::Image< double,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUS3ID3', True, 'itk::Image< unsigned short,3 >, itk::Image< double,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUS4ID4', True, 'itk::Image< unsigned short,4 >, itk::Image< double,4 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterIUC2IF2', True, 'itk::Image< unsigned char,2 >, itk::Image< float,2 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterIUC3IF3', True, 'itk::Image< unsigned char,3 >, itk::Image< float,3 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterIUC4IF4', True, 'itk::Image< unsigned char,4 >, itk::Image< float,4 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterIUC2ID2', True, 'itk::Image< unsigned char,2 >, itk::Image< double,2 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterIUC3ID3', True, 'itk::Image< unsigned char,3 >, itk::Image< double,3 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterIUC4ID4', True, 'itk::Image< unsigned char,4 >, itk::Image< double,4 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterIUS2IF2', True, 'itk::Image< unsigned short,2 >, itk::Image< float,2 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterIUS3IF3', True, 'itk::Image< unsigned short,3 >, itk::Image< float,3 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterIUS4IF4', True, 'itk::Image< unsigned short,4 >, itk::Image< float,4 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterIUS2ID2', True, 'itk::Image< unsigned short,2 >, itk::Image< double,2 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterIUS3ID3', True, 'itk::Image< unsigned short,3 >, itk::Image< double,3 >'),
  ('DirectedHausdorffDistanceImageFilter', 'itk::DirectedHausdorffDistanceImageFilter', 'itkDirectedHausdorffDistanceImageFilterIUS4ID4', True, 'itk::Image< unsigned short,4 >, itk::Image< double,4 >'),
  ('FastChamferDistanceImageFilter', 'itk::FastChamferDistanceImageFilter', 'itkFastChamferDistanceImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('FastChamferDistanceImageFilter', 'itk::FastChamferDistanceImageFilter', 'itkFastChamferDistanceImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('FastChamferDistanceImageFilter', 'itk::FastChamferDistanceImageFilter', 'itkFastChamferDistanceImageFilterISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('FastChamferDistanceImageFilter', 'itk::FastChamferDistanceImageFilter', 'itkFastChamferDistanceImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('FastChamferDistanceImageFilter', 'itk::FastChamferDistanceImageFilter', 'itkFastChamferDistanceImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('FastChamferDistanceImageFilter', 'itk::FastChamferDistanceImageFilter', 'itkFastChamferDistanceImageFilterIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('FastChamferDistanceImageFilter', 'itk::FastChamferDistanceImageFilter', 'itkFastChamferDistanceImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('FastChamferDistanceImageFilter', 'itk::FastChamferDistanceImageFilter', 'itkFastChamferDistanceImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('FastChamferDistanceImageFilter', 'itk::FastChamferDistanceImageFilter', 'itkFastChamferDistanceImageFilterID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterIUC2IF2', True, 'itk::Image< unsigned char,2 >, itk::Image< float,2 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterIUC3IF3', True, 'itk::Image< unsigned char,3 >, itk::Image< float,3 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterIUC4IF4', True, 'itk::Image< unsigned char,4 >, itk::Image< float,4 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterIUC2ID2', True, 'itk::Image< unsigned char,2 >, itk::Image< double,2 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterIUC3ID3', True, 'itk::Image< unsigned char,3 >, itk::Image< double,3 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterIUC4ID4', True, 'itk::Image< unsigned char,4 >, itk::Image< double,4 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterIUS2IF2', True, 'itk::Image< unsigned short,2 >, itk::Image< float,2 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterIUS3IF3', True, 'itk::Image< unsigned short,3 >, itk::Image< float,3 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterIUS4IF4', True, 'itk::Image< unsigned short,4 >, itk::Image< float,4 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterIUS2ID2', True, 'itk::Image< unsigned short,2 >, itk::Image< double,2 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterIUS3ID3', True, 'itk::Image< unsigned short,3 >, itk::Image< double,3 >'),
  ('HausdorffDistanceImageFilter', 'itk::HausdorffDistanceImageFilter', 'itkHausdorffDistanceImageFilterIUS4ID4', True, 'itk::Image< unsigned short,4 >, itk::Image< double,4 >'),
  ('IsoContourDistanceImageFilter', 'itk::IsoContourDistanceImageFilter', 'itkIsoContourDistanceImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('IsoContourDistanceImageFilter', 'itk::IsoContourDistanceImageFilter', 'itkIsoContourDistanceImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('IsoContourDistanceImageFilter', 'itk::IsoContourDistanceImageFilter', 'itkIsoContourDistanceImageFilterIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('IsoContourDistanceImageFilter', 'itk::IsoContourDistanceImageFilter', 'itkIsoContourDistanceImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('IsoContourDistanceImageFilter', 'itk::IsoContourDistanceImageFilter', 'itkIsoContourDistanceImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('IsoContourDistanceImageFilter', 'itk::IsoContourDistanceImageFilter', 'itkIsoContourDistanceImageFilterID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterISS2IF2', True, 'itk::Image< signed short,2 >, itk::Image< float,2 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterISS3IF3', True, 'itk::Image< signed short,3 >, itk::Image< float,3 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterISS4IF4', True, 'itk::Image< signed short,4 >, itk::Image< float,4 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterISS2ID2', True, 'itk::Image< signed short,2 >, itk::Image< double,2 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterISS3ID3', True, 'itk::Image< signed short,3 >, itk::Image< double,3 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterISS4ID4', True, 'itk::Image< signed short,4 >, itk::Image< double,4 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUC2IF2', True, 'itk::Image< unsigned char,2 >, itk::Image< float,2 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUC3IF3', True, 'itk::Image< unsigned char,3 >, itk::Image< float,3 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUC4IF4', True, 'itk::Image< unsigned char,4 >, itk::Image< float,4 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUC2ID2', True, 'itk::Image< unsigned char,2 >, itk::Image< double,2 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUC3ID3', True, 'itk::Image< unsigned char,3 >, itk::Image< double,3 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUC4ID4', True, 'itk::Image< unsigned char,4 >, itk::Image< double,4 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUS2IF2', True, 'itk::Image< unsigned short,2 >, itk::Image< float,2 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUS3IF3', True, 'itk::Image< unsigned short,3 >, itk::Image< float,3 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUS4IF4', True, 'itk::Image< unsigned short,4 >, itk::Image< float,4 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUS2ID2', True, 'itk::Image< unsigned short,2 >, itk::Image< double,2 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUS3ID3', True, 'itk::Image< unsigned short,3 >, itk::Image< double,3 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUS4ID4', True, 'itk::Image< unsigned short,4 >, itk::Image< double,4 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIF2ID2', True, 'itk::Image< float,2 >, itk::Image< double,2 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIF3ID3', True, 'itk::Image< float,3 >, itk::Image< double,3 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIF4ID4', True, 'itk::Image< float,4 >, itk::Image< double,4 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterID2IF2', True, 'itk::Image< double,2 >, itk::Image< float,2 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterID3IF3', True, 'itk::Image< double,3 >, itk::Image< float,3 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterID4IF4', True, 'itk::Image< double,4 >, itk::Image< float,4 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterISS2IF2', True, 'itk::Image< signed short,2 >, itk::Image< float,2 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterISS3IF3', True, 'itk::Image< signed short,3 >, itk::Image< float,3 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterISS4IF4', True, 'itk::Image< signed short,4 >, itk::Image< float,4 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterISS2ID2', True, 'itk::Image< signed short,2 >, itk::Image< double,2 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterISS3ID3', True, 'itk::Image< signed short,3 >, itk::Image< double,3 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterISS4ID4', True, 'itk::Image< signed short,4 >, itk::Image< double,4 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUC2IF2', True, 'itk::Image< unsigned char,2 >, itk::Image< float,2 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUC3IF3', True, 'itk::Image< unsigned char,3 >, itk::Image< float,3 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUC4IF4', True, 'itk::Image< unsigned char,4 >, itk::Image< float,4 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUC2ID2', True, 'itk::Image< unsigned char,2 >, itk::Image< double,2 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUC3ID3', True, 'itk::Image< unsigned char,3 >, itk::Image< double,3 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUC4ID4', True, 'itk::Image< unsigned char,4 >, itk::Image< double,4 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUS2IF2', True, 'itk::Image< unsigned short,2 >, itk::Image< float,2 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUS3IF3', True, 'itk::Image< unsigned short,3 >, itk::Image< float,3 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUS4IF4', True, 'itk::Image< unsigned short,4 >, itk::Image< float,4 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUS2ID2', True, 'itk::Image< unsigned short,2 >, itk::Image< double,2 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUS3ID3', True, 'itk::Image< unsigned short,3 >, itk::Image< double,3 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUS4ID4', True, 'itk::Image< unsigned short,4 >, itk::Image< double,4 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIF2ID2', True, 'itk::Image< float,2 >, itk::Image< double,2 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIF3ID3', True, 'itk::Image< float,3 >, itk::Image< double,3 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIF4ID4', True, 'itk::Image< float,4 >, itk::Image< double,4 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterID2IF2', True, 'itk::Image< double,2 >, itk::Image< float,2 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterID3IF3', True, 'itk::Image< double,3 >, itk::Image< float,3 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterID4IF4', True, 'itk::Image< double,4 >, itk::Image< float,4 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
)
factories = ()
