# -*- coding: utf-8 -*-
# =============================================================================
# Copyright (2025) Dynamic Graphics, Inc. Lafayette, CA, USA.
#
# This DGPY library (the "Software") may not be used except in connection with
# the Licensees use of the Dynamic Graphics' software pursuant to an
# Agreement (defined below) between Licensee (defined below) and
# Dynamic Graphics, Inc. ("DGI"). This Software shall be deemed part of the
# Licensed Software under the Agreement. Licensees use of the Software must
# comply at all times with any restrictions applicable to the Licensed
# Software, generally, and must be used in accordance with applicable
# documentation. If you have not agreed to an Agreement or otherwise do not
# agree to these terms, you may not use the Software. This license terminates
# automatically upon the termination of the Agreement or Licensees breach of
# these terms.
#
# DEFINITIONS:
#  - Agreement: The software product license agreement, as amended, executed
#               between DGI and Licensee governing the use of the DGI software.
#  - Licensee: The user of the Software, or, if the Software is being used on
#              behalf of a company, the company.
# =============================================================================
"""cv exe wrapper functions"""

from __future__ import annotations

from dgpy.core.exe import ExeFunction, ExeFunctionAsync

__all__: list[str]
__FUNCTIONS__: dict[str, ExeFunction | ExeFunctionAsync]

# coviz
coviz: ExeFunction
coviz_async: ExeFunctionAsync

# Sync functions
_2grid2shape: ExeFunction
_2grid: ExeFunction
_2mindist: ExeFunction
_2trend: ExeFunction
_3dxml: ExeFunction
_3grd2segy: ExeFunction
_3grid: ExeFunction
_3index: ExeFunction
_3mindist: ExeFunction
_3trend: ExeFunction
_4dvaddattr: ExeFunction
_4dvbakint: ExeFunction
_4dvcurtain: ExeFunction
_4dvedit: ExeFunction
_4dvensemblesum: ExeFunction
_4dvmerge: ExeFunction
_4dvtoim: ExeFunction
_4dvtrim: ExeFunction
CummTotals: ExeFunction
addpath: ExeFunction
addpathinterval: ExeFunction
ahm: ExeFunction
annotate: ExeFunction
append: ExeFunction
arrow: ExeFunction
attrbitmap: ExeFunction
avetoinst: ExeFunction
avftopdat: ExeFunction
bakint: ExeFunction
bakintzone: ExeFunction
bil: ExeFunction
bubblemap: ExeFunction
buildv0kmodel: ExeFunction
bwdedit: ExeFunction
c3grdensemblesum: ExeFunction
caliper4dv: ExeFunction
cellattrimport: ExeFunction
cellattrprobe: ExeFunction
cellbakint: ExeFunction
celldump: ExeFunction
celleclipseimport: ExeFunction
celleclipsekeywords: ExeFunction
celleclipsestreamline: ExeFunction
celledit: ExeFunction
cellexport: ExeFunction
cellgridxsec: ExeFunction
cellimport: ExeFunction
cellpetimport: ExeFunction
cellplanesection: ExeFunction
cellrescueexport: ExeFunction
cellrescueimport: ExeFunction
cellstat: ExeFunction
celltogrid: ExeFunction
celltrim: ExeFunction
cellvdbdump: ExeFunction
cellvdbimport: ExeFunction
cellvdbstreamline: ExeFunction
cellvdbtracer: ExeFunction
cellvolcalc: ExeFunction
cfc: ExeFunction
cl2import: ExeFunction
clean: ExeFunction
clipfaces: ExeFunction
clmimport: ExeFunction
cluster: ExeFunction
completion: ExeFunction
completionn: ExeFunction
contour: ExeFunction
corpexport: ExeFunction
corpimport: ExeFunction
ct: ExeFunction
d2b: ExeFunction
d2bgridding: ExeFunction
dasimport: ExeFunction
datcombine: ExeFunction
datsplit: ExeFunction
decimate: ExeFunction
declusterlidardata: ExeFunction
deleteSWseismicO11: ExeFunction
deleteSWseismicR510: ExeFunction
dem: ExeFunction
depth2el: ExeFunction
dicomto3grd: ExeFunction
dip: ExeFunction
dist2surf: ExeFunction
drutil: ExeFunction
dtsimport: ExeFunction
dumbbell: ExeFunction
dumgrid: ExeFunction
dump: ExeFunction
dxf: ExeFunction
dxfexport: ExeFunction
eclipsefluids: ExeFunction
eclipseprod: ExeFunction
el2depth: ExeFunction
ev2gocad: ExeFunction
ev2zycorgrid: ExeFunction
export: ExeFunction
exportlidardata: ExeFunction
extract: ExeFunction
facedump: ExeFunction
facescut: ExeFunction
facesedit: ExeFunction
facestostl: ExeFunction
facestox3d: ExeFunction
faultgrid: ExeFunction
field: ExeFunction
fieldedit: ExeFunction
filedump: ExeFunction
fill: ExeFunction
filter: ExeFunction
flip: ExeFunction
flttic: ExeFunction
fp: ExeFunction
geertsma: ExeFunction
getQueryDetail: ExeFunction
getSWdataO11: ExeFunction
getSWdataR510: ExeFunction
getSWfaultDataO11: ExeFunction
getdataO11: ExeFunction
getmapdataO11: ExeFunction
gpimport: ExeFunction
gravity: ExeFunction
gravsoft: ExeFunction
grid2im: ExeFunction
gridconvolve: ExeFunction
gridcurtain: ExeFunction
gridedit: ExeFunction
gridto4dv: ExeFunction
gridtoimage: ExeFunction
gridtostl: ExeFunction
gridtrim: ExeFunction
gsurf2grd: ExeFunction
ht2gd: ExeFunction
ht2sh: ExeFunction
ikontetimport: ExeFunction
imagedelta: ExeFunction
imageplt: ExeFunction
imagexsec: ExeFunction
_import: ExeFunction
imregtotfw: ExeFunction
insttoave: ExeFunction
inter: ExeFunction
interpolate: ExeFunction
intimport: ExeFunction
iwdplothelper: ExeFunction
kml: ExeFunction
krig: ExeFunction
label: ExeFunction
legend: ExeFunction
lgd: ExeFunction
license: ExeFunction
linemake: ExeFunction
lineplot: ExeFunction
linepost: ExeFunction
listplot: ExeFunction
makelidardata: ExeFunction
makevsnip: ExeFunction
maplabel: ExeFunction
merge: ExeFunction
merge4dvx: ExeFunction
mergevelgrids: ExeFunction
mgridedit: ExeFunction
mgridexport: ExeFunction
mgridimport: ExeFunction
mgridinfo: ExeFunction
minmax2pivotrange: ExeFunction
nearestneighbors: ExeFunction
nexuspltprod: ExeFunction
nids: ExeFunction
nodepost: ExeFunction
noisegen: ExeFunction
objimport: ExeFunction
package: ExeFunction
pathexport: ExeFunction
pause: ExeFunction
pdat2bwd: ExeFunction
pdat2plt: ExeFunction
petblob: ExeFunction
petdump: ExeFunction
pet2012dump: ExeFunction
petpoints: ExeFunction
pet2012points: ExeFunction
petpolygons: ExeFunction
pet2012polygons: ExeFunction
petraimport: ExeFunction
petseismic: ExeFunction
pet2012seismic: ExeFunction
petsurf: ExeFunction
pet2012surf: ExeFunction
pettargets: ExeFunction
pet2012targets: ExeFunction
petwelllogs: ExeFunction
pet2012welllogs: ExeFunction
petwells: ExeFunction
pet2012wells: ExeFunction
petwelltops: ExeFunction
pet2012welltops: ExeFunction
pick: ExeFunction
piechart: ExeFunction
plotserver: ExeFunction
pltconvert: ExeFunction
plyarea: ExeFunction
plybld: ExeFunction
plybop: ExeFunction
ply2ann: ExeFunction
plyhull: ExeFunction
post: ExeFunction
prodimport: ExeFunction
prodreport: ExeFunction
ptinpoly: ExeFunction
putSWseismicO11: ExeFunction
putSWseismicR510: ExeFunction
putmapdataO11: ExeFunction
rangepoly: ExeFunction
rdbimport: ExeFunction
reportprogress: ExeFunction
resample3d: ExeFunction
resqmlexport: ExeFunction
resqmlimport: ExeFunction
retilelidardata: ExeFunction
reverseSlash: ExeFunction
rmsimport: ExeFunction
rnslem: ExeFunction
safimport: ExeFunction
scale: ExeFunction
sec: ExeFunction
segy2ev: ExeFunction
segyimport: ExeFunction
seq2avgrd: ExeFunction
seq2igrd: ExeFunction
seqbuild: ExeFunction
seqedit: ExeFunction
sgrid2pdat: ExeFunction
shapeexport: ExeFunction
shapeimport: ExeFunction
sim2pem: ExeFunction
slice: ExeFunction
smooth: ExeFunction
sort: ExeFunction
splitlidardata: ExeFunction
sqlitetest: ExeFunction
stat: ExeFunction
std4dvolumes: ExeFunction
stimplanimport: ExeFunction
surfclip: ExeFunction
surfer: ExeFunction
surfhide: ExeFunction
synth: ExeFunction
synth_turbo: ExeFunction
sysinfo: ExeFunction
t2d: ExeFunction
tetrabakint: ExeFunction
tfwtoimreg: ExeFunction
tsd: ExeFunction
tsolidto4dv: ExeFunction
tsurf4dv: ExeFunction
tunface: ExeFunction
ulpcmp: ExeFunction
umbra: ExeFunction
vario: ExeFunction
vdbensemblesum: ExeFunction
vdbprod: ExeFunction
vect2grid: ExeFunction
vecto4dv: ExeFunction
velmodelclean: ExeFunction
viewclient: ExeFunction
viewipc: ExeFunction
viewlauncher: ExeFunction
viewserver: ExeFunction
viewserverik: ExeFunction
voxet2grd: ExeFunction
vs2pdat: ExeFunction
vtimport: ExeFunction
waveletgen: ExeFunction
wellDataPlot: ExeFunction
wellpath: ExeFunction
wellspec: ExeFunction
wellstrc: ExeFunction
wellsurvey: ExeFunction
welltube: ExeFunction
wl2path: ExeFunction
wlgtoimage: ExeFunction
wmlimport: ExeFunction
wms: ExeFunction
wp2igrd: ExeFunction
wvlpharot: ExeFunction
x2face: ExeFunction
xsec: ExeFunction
zgfimport: ExeFunction
zmapgridimport: ExeFunction
zonlin: ExeFunction
zonply: ExeFunction
zonpnt: ExeFunction

# Async functions
_2grid2shape_async: ExeFunctionAsync
_2grid_async: ExeFunctionAsync
_2mindist_async: ExeFunctionAsync
_2trend_async: ExeFunctionAsync
_3dxml_async: ExeFunctionAsync
_3grd2segy_async: ExeFunctionAsync
_3grid_async: ExeFunctionAsync
_3index_async: ExeFunctionAsync
_3mindist_async: ExeFunctionAsync
_3trend_async: ExeFunctionAsync
_4dvaddattr_async: ExeFunctionAsync
_4dvbakint_async: ExeFunctionAsync
_4dvcurtain_async: ExeFunctionAsync
_4dvedit_async: ExeFunctionAsync
_4dvensemblesum_async: ExeFunctionAsync
_4dvmerge_async: ExeFunctionAsync
_4dvtoim_async: ExeFunctionAsync
_4dvtrim_async: ExeFunctionAsync
CummTotals_async: ExeFunctionAsync
addpath_async: ExeFunctionAsync
addpathinterval_async: ExeFunctionAsync
ahm_async: ExeFunctionAsync
annotate_async: ExeFunctionAsync
append_async: ExeFunctionAsync
arrow_async: ExeFunctionAsync
attrbitmap_async: ExeFunctionAsync
avetoinst_async: ExeFunctionAsync
avftopdat_async: ExeFunctionAsync
bakint_async: ExeFunctionAsync
bakintzone_async: ExeFunctionAsync
bil_async: ExeFunctionAsync
bubblemap_async: ExeFunctionAsync
buildv0kmodel_async: ExeFunctionAsync
bwdedit_async: ExeFunctionAsync
c3grdensemblesum_async: ExeFunctionAsync
caliper4dv_async: ExeFunctionAsync
cellattrimport_async: ExeFunctionAsync
cellattrprobe_async: ExeFunctionAsync
cellbakint_async: ExeFunctionAsync
celldump_async: ExeFunctionAsync
celleclipseimport_async: ExeFunctionAsync
celleclipsekeywords_async: ExeFunctionAsync
celleclipsestreamline_async: ExeFunctionAsync
celledit_async: ExeFunctionAsync
cellexport_async: ExeFunctionAsync
cellgridxsec_async: ExeFunctionAsync
cellimport_async: ExeFunctionAsync
cellpetimport_async: ExeFunctionAsync
cellplanesection_async: ExeFunctionAsync
cellrescueexport_async: ExeFunctionAsync
cellrescueimport_async: ExeFunctionAsync
cellstat_async: ExeFunctionAsync
celltogrid_async: ExeFunctionAsync
celltrim_async: ExeFunctionAsync
cellvdbdump_async: ExeFunctionAsync
cellvdbimport_async: ExeFunctionAsync
cellvdbstreamline_async: ExeFunctionAsync
cellvdbtracer_async: ExeFunctionAsync
cellvolcalc_async: ExeFunctionAsync
cfc_async: ExeFunctionAsync
cl2import_async: ExeFunctionAsync
clean_async: ExeFunctionAsync
clipfaces_async: ExeFunctionAsync
clmimport_async: ExeFunctionAsync
cluster_async: ExeFunctionAsync
completion_async: ExeFunctionAsync
completionn_async: ExeFunctionAsync
contour_async: ExeFunctionAsync
corpexport_async: ExeFunctionAsync
corpimport_async: ExeFunctionAsync
ct_async: ExeFunctionAsync
d2b_async: ExeFunctionAsync
d2bgridding_async: ExeFunctionAsync
dasimport_async: ExeFunctionAsync
datcombine_async: ExeFunctionAsync
datsplit_async: ExeFunctionAsync
decimate_async: ExeFunctionAsync
declusterlidardata_async: ExeFunctionAsync
deleteSWseismicO11_async: ExeFunctionAsync
deleteSWseismicR510_async: ExeFunctionAsync
dem_async: ExeFunctionAsync
depth2el_async: ExeFunctionAsync
dicomto3grd_async: ExeFunctionAsync
dip_async: ExeFunctionAsync
dist2surf_async: ExeFunctionAsync
drutil_async: ExeFunctionAsync
dtsimport_async: ExeFunctionAsync
dumbbell_async: ExeFunctionAsync
dumgrid_async: ExeFunctionAsync
dump_async: ExeFunctionAsync
dxf_async: ExeFunctionAsync
dxfexport_async: ExeFunctionAsync
eclipsefluids_async: ExeFunctionAsync
eclipseprod_async: ExeFunctionAsync
el2depth_async: ExeFunctionAsync
ev2gocad_async: ExeFunctionAsync
ev2zycorgrid_async: ExeFunctionAsync
export_async: ExeFunctionAsync
exportlidardata_async: ExeFunctionAsync
extract_async: ExeFunctionAsync
facedump_async: ExeFunctionAsync
facescut_async: ExeFunctionAsync
facesedit_async: ExeFunctionAsync
facestostl_async: ExeFunctionAsync
facestox3d_async: ExeFunctionAsync
faultgrid_async: ExeFunctionAsync
field_async: ExeFunctionAsync
fieldedit_async: ExeFunctionAsync
filedump_async: ExeFunctionAsync
fill_async: ExeFunctionAsync
filter_async: ExeFunctionAsync
flip_async: ExeFunctionAsync
flttic_async: ExeFunctionAsync
fp_async: ExeFunctionAsync
geertsma_async: ExeFunctionAsync
getQueryDetail_async: ExeFunctionAsync
getSWdataO11_async: ExeFunctionAsync
getSWdataR510_async: ExeFunctionAsync
getSWfaultDataO11_async: ExeFunctionAsync
getdataO11_async: ExeFunctionAsync
getmapdataO11_async: ExeFunctionAsync
gpimport_async: ExeFunctionAsync
gravity_async: ExeFunctionAsync
gravsoft_async: ExeFunctionAsync
grid2im_async: ExeFunctionAsync
gridconvolve_async: ExeFunctionAsync
gridcurtain_async: ExeFunctionAsync
gridedit_async: ExeFunctionAsync
gridto4dv_async: ExeFunctionAsync
gridtoimage_async: ExeFunctionAsync
gridtostl_async: ExeFunctionAsync
gridtrim_async: ExeFunctionAsync
gsurf2grd_async: ExeFunctionAsync
ht2gd_async: ExeFunctionAsync
ht2sh_async: ExeFunctionAsync
ikontetimport_async: ExeFunctionAsync
imagedelta_async: ExeFunctionAsync
imageplt_async: ExeFunctionAsync
imagexsec_async: ExeFunctionAsync
_import_async: ExeFunctionAsync
imregtotfw_async: ExeFunctionAsync
insttoave_async: ExeFunctionAsync
inter_async: ExeFunctionAsync
interpolate_async: ExeFunctionAsync
intimport_async: ExeFunctionAsync
iwdplothelper_async: ExeFunctionAsync
kml_async: ExeFunctionAsync
krig_async: ExeFunctionAsync
label_async: ExeFunctionAsync
legend_async: ExeFunctionAsync
lgd_async: ExeFunctionAsync
license_async: ExeFunctionAsync
linemake_async: ExeFunctionAsync
lineplot_async: ExeFunctionAsync
linepost_async: ExeFunctionAsync
listplot_async: ExeFunctionAsync
makelidardata_async: ExeFunctionAsync
makevsnip_async: ExeFunctionAsync
maplabel_async: ExeFunctionAsync
merge_async: ExeFunctionAsync
merge4dvx_async: ExeFunctionAsync
mergevelgrids_async: ExeFunctionAsync
mgridedit_async: ExeFunctionAsync
mgridexport_async: ExeFunctionAsync
mgridimport_async: ExeFunctionAsync
mgridinfo_async: ExeFunctionAsync
minmax2pivotrange_async: ExeFunctionAsync
nearestneighbors_async: ExeFunctionAsync
nexuspltprod_async: ExeFunctionAsync
nids_async: ExeFunctionAsync
nodepost_async: ExeFunctionAsync
noisegen_async: ExeFunctionAsync
objimport_async: ExeFunctionAsync
package_async: ExeFunctionAsync
pathexport_async: ExeFunctionAsync
pause_async: ExeFunctionAsync
pdat2bwd_async: ExeFunctionAsync
pdat2plt_async: ExeFunctionAsync
petblob_async: ExeFunctionAsync
petdump_async: ExeFunctionAsync
pet2012dump_async: ExeFunctionAsync
petpoints_async: ExeFunctionAsync
pet2012points_async: ExeFunctionAsync
petpolygons_async: ExeFunctionAsync
pet2012polygons_async: ExeFunctionAsync
petraimport_async: ExeFunctionAsync
petseismic_async: ExeFunctionAsync
pet2012seismic_async: ExeFunctionAsync
petsurf_async: ExeFunctionAsync
pet2012surf_async: ExeFunctionAsync
pettargets_async: ExeFunctionAsync
pet2012targets_async: ExeFunctionAsync
petwelllogs_async: ExeFunctionAsync
pet2012welllogs_async: ExeFunctionAsync
petwells_async: ExeFunctionAsync
pet2012wells_async: ExeFunctionAsync
petwelltops_async: ExeFunctionAsync
pet2012welltops_async: ExeFunctionAsync
pick_async: ExeFunctionAsync
piechart_async: ExeFunctionAsync
plotserver_async: ExeFunctionAsync
pltconvert_async: ExeFunctionAsync
plyarea_async: ExeFunctionAsync
plybld_async: ExeFunctionAsync
plybop_async: ExeFunctionAsync
ply2ann_async: ExeFunctionAsync
plyhull_async: ExeFunctionAsync
post_async: ExeFunctionAsync
prodimport_async: ExeFunctionAsync
prodreport_async: ExeFunctionAsync
ptinpoly_async: ExeFunctionAsync
putSWseismicO11_async: ExeFunctionAsync
putSWseismicR510_async: ExeFunctionAsync
putmapdataO11_async: ExeFunctionAsync
rangepoly_async: ExeFunctionAsync
rdbimport_async: ExeFunctionAsync
reportprogress_async: ExeFunctionAsync
resample3d_async: ExeFunctionAsync
resqmlexport_async: ExeFunctionAsync
resqmlimport_async: ExeFunctionAsync
retilelidardata_async: ExeFunctionAsync
reverseSlash_async: ExeFunctionAsync
rmsimport_async: ExeFunctionAsync
rnslem_async: ExeFunctionAsync
safimport_async: ExeFunctionAsync
scale_async: ExeFunctionAsync
sec_async: ExeFunctionAsync
segy2ev_async: ExeFunctionAsync
segyimport_async: ExeFunctionAsync
seq2avgrd_async: ExeFunctionAsync
seq2igrd_async: ExeFunctionAsync
seqbuild_async: ExeFunctionAsync
seqedit_async: ExeFunctionAsync
sgrid2pdat_async: ExeFunctionAsync
shapeexport_async: ExeFunctionAsync
shapeimport_async: ExeFunctionAsync
sim2pem_async: ExeFunctionAsync
slice_async: ExeFunctionAsync
smooth_async: ExeFunctionAsync
sort_async: ExeFunctionAsync
splitlidardata_async: ExeFunctionAsync
sqlitetest_async: ExeFunctionAsync
stat_async: ExeFunctionAsync
std4dvolumes_async: ExeFunctionAsync
stimplanimport_async: ExeFunctionAsync
surfclip_async: ExeFunctionAsync
surfer_async: ExeFunctionAsync
surfhide_async: ExeFunctionAsync
synth_async: ExeFunctionAsync
synth_turbo_async: ExeFunctionAsync
sysinfo_async: ExeFunctionAsync
t2d_async: ExeFunctionAsync
tetrabakint_async: ExeFunctionAsync
tfwtoimreg_async: ExeFunctionAsync
tsd_async: ExeFunctionAsync
tsolidto4dv_async: ExeFunctionAsync
tsurf4dv_async: ExeFunctionAsync
tunface_async: ExeFunctionAsync
ulpcmp_async: ExeFunctionAsync
umbra_async: ExeFunctionAsync
vario_async: ExeFunctionAsync
vdbensemblesum_async: ExeFunctionAsync
vdbprod_async: ExeFunctionAsync
vect2grid_async: ExeFunctionAsync
vecto4dv_async: ExeFunctionAsync
velmodelclean_async: ExeFunctionAsync
viewclient_async: ExeFunctionAsync
viewipc_async: ExeFunctionAsync
viewlauncher_async: ExeFunctionAsync
viewserver_async: ExeFunctionAsync
viewserverik_async: ExeFunctionAsync
voxet2grd_async: ExeFunctionAsync
vs2pdat_async: ExeFunctionAsync
vtimport_async: ExeFunctionAsync
waveletgen_async: ExeFunctionAsync
wellDataPlot_async: ExeFunctionAsync
wellpath_async: ExeFunctionAsync
wellspec_async: ExeFunctionAsync
wellstrc_async: ExeFunctionAsync
wellsurvey_async: ExeFunctionAsync
welltube_async: ExeFunctionAsync
wl2path_async: ExeFunctionAsync
wlgtoimage_async: ExeFunctionAsync
wmlimport_async: ExeFunctionAsync
wms_async: ExeFunctionAsync
wp2igrd_async: ExeFunctionAsync
wvlpharot_async: ExeFunctionAsync
x2face_async: ExeFunctionAsync
xsec_async: ExeFunctionAsync
zgfimport_async: ExeFunctionAsync
zmapgridimport_async: ExeFunctionAsync
zonlin_async: ExeFunctionAsync
zonply_async: ExeFunctionAsync
zonpnt_async: ExeFunctionAsync
