# -*- coding: utf-8 -*-
# =============================================================================
# Copyright (2025) Dynamic Graphics, Inc. Lafayette, CA, USA.
#
# This DGPY library (the "Software") may not be used except in connection with
# the Licensees use of the Dynamic Graphics' software pursuant to an
# Agreement (defined below) between Licensee (defined below) and
# Dynamic Graphics, Inc. ("DGI"). This Software shall be deemed part of the
# Licensed Software under the Agreement. Licensees use of the Software must
# comply at all times with any restrictions applicable to the Licensed
# Software, generally, and must be used in accordance with applicable
# documentation. If you have not agreed to an Agreement or otherwise do not
# agree to these terms, you may not use the Software. This license terminates
# automatically upon the termination of the Agreement or Licensees breach of
# these terms.
#
# DEFINITIONS:
#  - Agreement: The software product license agreement, as amended, executed
#               between DGI and Licensee governing the use of the DGI software.
#  - Licensee: The user of the Software, or, if the Software is being used on
#              behalf of a company, the company.
# =============================================================================
"""ev exe wrapper functions"""

from __future__ import annotations

from dgpy.core.exe import ExeFunction, ExeFunctionAsync

__all__: list[str]
__FUNCTIONS__: dict[str, ExeFunction | ExeFunctionAsync]

# Sync functions
_2dfply: ExeFunction
_2grid2shape: ExeFunction
_2grid: ExeFunction
_2mindist: ExeFunction
_2trend: ExeFunction
_3grd2segy: ExeFunction
_3grid: ExeFunction
_3index: ExeFunction
_3mindist: ExeFunction
_3trend: ExeFunction
_4dvaddattr: ExeFunction
_4dvcurtain: ExeFunction
_4dvedit: ExeFunction
_4dvtrim: ExeFunction
addpath: ExeFunction
addpathinterval: ExeFunction
annotate: ExeFunction
append: ExeFunction
arrow: ExeFunction
attrbitmap: ExeFunction
avetoinst: ExeFunction
bakint: ExeFunction
bakintzone: ExeFunction
bil: ExeFunction
bubblemap: ExeFunction
bwdedit: ExeFunction
cellIndexTOIJK: ExeFunction
cellattrimport: ExeFunction
cellattrprobe: ExeFunction
cellcavity: ExeFunction
celldump: ExeFunction
celleclipseimport: ExeFunction
celledit: ExeFunction
cellexport: ExeFunction
cellgridxsec: ExeFunction
cellhdrtag: ExeFunction
cellimport: ExeFunction
cellklayer: ExeFunction
cellmakefileedit: ExeFunction
cellpetimport: ExeFunction
cellplanesection: ExeFunction
cellrangepoly: ExeFunction
cellrescueexport: ExeFunction
cellrescueimport: ExeFunction
cellstat: ExeFunction
celltrim: ExeFunction
celltube: ExeFunction
cellupscale: ExeFunction
cellvdbdump: ExeFunction
cellvdbimport: ExeFunction
cellvdbstreamline: ExeFunction
cellvdbtracer: ExeFunction
cfc: ExeFunction
check_az_inc: ExeFunction
clean: ExeFunction
clipfaces: ExeFunction
clmimport: ExeFunction
cluster: ExeFunction
completion: ExeFunction
completionn: ExeFunction
contour: ExeFunction
ct: ExeFunction
dat2wlist: ExeFunction
datcombine: ExeFunction
datsplit: ExeFunction
decimate: ExeFunction
deleteSWseismicO11: ExeFunction
deleteSWseismicR510: ExeFunction
depth2el: ExeFunction
dip: ExeFunction
dist2surf: ExeFunction
distribute: ExeFunction
drawtree: ExeFunction
dumgrid: ExeFunction
dump: ExeFunction
dxf: ExeFunction
dxfexport: ExeFunction
dxfscale: ExeFunction
el2depth: ExeFunction
ev2gocad: ExeFunction
ev2zycorgrid: ExeFunction
export: ExeFunction
extendavgrd: ExeFunction
extendwell: ExeFunction
extract: ExeFunction
facedump: ExeFunction
facescut: ExeFunction
facesedit: ExeFunction
facestostl: ExeFunction
facestox3d: ExeFunction
faultgrid: ExeFunction
fgr: ExeFunction
field: ExeFunction
fieldedit: ExeFunction
filedump: ExeFunction
fill: ExeFunction
filter: ExeFunction
flow3grid: ExeFunction
flttic: ExeFunction
dem: ExeFunction
fp: ExeFunction
fpfp2fp: ExeFunction
geoconf: ExeFunction
geodistribute: ExeFunction
getSWdataO11: ExeFunction
getSWdataR510: ExeFunction
getSWfaultDataO11: ExeFunction
getdataO11: ExeFunction
getmapdataO11: ExeFunction
grid2im: ExeFunction
gridcurtain: ExeFunction
gridedit: ExeFunction
gridrangepoly: ExeFunction
gridslice: ExeFunction
gridto4dv: ExeFunction
gridtoimage: ExeFunction
hgadjust: ExeFunction
hgbak: ExeFunction
hgface: ExeFunction
hgfor: ExeFunction
hgframe: ExeFunction
hglabel: ExeFunction
hgmk: ExeFunction
hgrev: ExeFunction
hgspace: ExeFunction
hgthrow: ExeFunction
ht2gd: ExeFunction
ht2sh: ExeFunction
imageplt: ExeFunction
imagexsec: ExeFunction
_import: ExeFunction
imregtotfw: ExeFunction
insttoave: ExeFunction
inter: ExeFunction
interpolate: ExeFunction
irrslice: ExeFunction
isochore: ExeFunction
it2sh: ExeFunction
iwdplothelper: ExeFunction
juxtapos: ExeFunction
kml: ExeFunction
krig: ExeFunction
label: ExeFunction
legend: ExeFunction
lgd: ExeFunction
license: ExeFunction
linemake: ExeFunction
lineplot: ExeFunction
linepost: ExeFunction
listplot: ExeFunction
localgrid: ExeFunction
makedat: ExeFunction
makestitchpts: ExeFunction
maplabel: ExeFunction
merge: ExeFunction
mgridedit: ExeFunction
mgridexport: ExeFunction
mgridimport: ExeFunction
mgridinfo: ExeFunction
minmax2pivotrange: ExeFunction
modquery: ExeFunction
nearestneighbors: ExeFunction
netpay: ExeFunction
new_cps2ev: ExeFunction
nodepost: ExeFunction
package: ExeFunction
paginateVolTxtRpt: ExeFunction
pause: ExeFunction
pick: ExeFunction
piechart: ExeFunction
plotserver: ExeFunction
pltconvert: ExeFunction
ply2ann: ExeFunction
plyarea: ExeFunction
plybld: ExeFunction
plybop: ExeFunction
plyhull: ExeFunction
post: ExeFunction
propbak: ExeFunction
ptinpoly: ExeFunction
putSWseismicO11: ExeFunction
putSWseismicR510: ExeFunction
putmapdataO11: ExeFunction
raft: ExeFunction
rangepoly: ExeFunction
rawdump: ExeFunction
reportprogress: ExeFunction
rerotate: ExeFunction
reverseSlash: ExeFunction
scale: ExeFunction
sec: ExeFunction
segy2ev: ExeFunction
segyimport: ExeFunction
seq2avgrd: ExeFunction
seq2igrd: ExeFunction
seq2wfp: ExeFunction
seqbuild: ExeFunction
seqedit: ExeFunction
seqvol: ExeFunction
sgrid2pdat: ExeFunction
shapeexport: ExeFunction
shapeimport: ExeFunction
slice: ExeFunction
smooth: ExeFunction
sort: ExeFunction
stat: ExeFunction
surfclip: ExeFunction
surfer: ExeFunction
surfhide: ExeFunction
sysinfo: ExeFunction
t2d: ExeFunction
tfwtoimreg: ExeFunction
thickness: ExeFunction
tieline: ExeFunction
tree: ExeFunction
truedip: ExeFunction
truemerge: ExeFunction
tsd: ExeFunction
tst: ExeFunction
tsurf4dv: ExeFunction
tunface: ExeFunction
ulpcmp: ExeFunction
vario: ExeFunction
vect2grid: ExeFunction
viewipc: ExeFunction
volcomp: ExeFunction
volume: ExeFunction
voxet2grd: ExeFunction
vs2pdat: ExeFunction
wellDataPlot: ExeFunction
wellpath: ExeFunction
wellprofile: ExeFunction
wellstrc: ExeFunction
wellsurvey: ExeFunction
welltube: ExeFunction
wfp2seq: ExeFunction
wl2path: ExeFunction
wp2igrd: ExeFunction
x2face: ExeFunction
xformdata: ExeFunction
xsec: ExeFunction
zgfimport: ExeFunction
zmapgridimport: ExeFunction
zonlin: ExeFunction
zonply: ExeFunction
zonpnt: ExeFunction

# Async functions
_2dfply_async: ExeFunctionAsync
_2grid2shape_async: ExeFunctionAsync
_2grid_async: ExeFunctionAsync
_2mindist_async: ExeFunctionAsync
_2trend_async: ExeFunctionAsync
_3grd2segy_async: ExeFunctionAsync
_3grid_async: ExeFunctionAsync
_3index_async: ExeFunctionAsync
_3mindist_async: ExeFunctionAsync
_3trend_async: ExeFunctionAsync
_4dvaddattr_async: ExeFunctionAsync
_4dvcurtain_async: ExeFunctionAsync
_4dvedit_async: ExeFunctionAsync
_4dvtrim_async: ExeFunctionAsync
_import_async: ExeFunctionAsync
addpath_async: ExeFunctionAsync
addpathinterval_async: ExeFunctionAsync
annotate_async: ExeFunctionAsync
append_async: ExeFunctionAsync
arrow_async: ExeFunctionAsync
attrbitmap_async: ExeFunctionAsync
avetoinst_async: ExeFunctionAsync
bakint_async: ExeFunctionAsync
bakintzone_async: ExeFunctionAsync
bil_async: ExeFunctionAsync
bubblemap_async: ExeFunctionAsync
bwdedit_async: ExeFunctionAsync
cellIndexTOIJK_async: ExeFunctionAsync
cellattrimport_async: ExeFunctionAsync
cellattrprobe_async: ExeFunctionAsync
cellcavity_async: ExeFunctionAsync
celldump_async: ExeFunctionAsync
celleclipseimport_async: ExeFunctionAsync
celledit_async: ExeFunctionAsync
cellexport_async: ExeFunctionAsync
cellgridxsec_async: ExeFunctionAsync
cellhdrtag_async: ExeFunctionAsync
cellimport_async: ExeFunctionAsync
cellklayer_async: ExeFunctionAsync
cellmakefileedit_async: ExeFunctionAsync
cellpetimport_async: ExeFunctionAsync
cellplanesection_async: ExeFunctionAsync
cellrangepoly_async: ExeFunctionAsync
cellrescueexport_async: ExeFunctionAsync
cellrescueimport_async: ExeFunctionAsync
cellstat_async: ExeFunctionAsync
celltrim_async: ExeFunctionAsync
celltube_async: ExeFunctionAsync
cellupscale_async: ExeFunctionAsync
cellvdbdump_async: ExeFunctionAsync
cellvdbimport_async: ExeFunctionAsync
cellvdbstreamline_async: ExeFunctionAsync
cellvdbtracer_async: ExeFunctionAsync
cfc_async: ExeFunctionAsync
check_az_inc_async: ExeFunctionAsync
clean_async: ExeFunctionAsync
clipfaces_async: ExeFunctionAsync
clmimport_async: ExeFunctionAsync
cluster_async: ExeFunctionAsync
completion_async: ExeFunctionAsync
completionn_async: ExeFunctionAsync
contour_async: ExeFunctionAsync
ct_async: ExeFunctionAsync
dat2wlist_async: ExeFunctionAsync
datcombine_async: ExeFunctionAsync
datsplit_async: ExeFunctionAsync
decimate_async: ExeFunctionAsync
deleteSWseismicO11_async: ExeFunctionAsync
deleteSWseismicR510_async: ExeFunctionAsync
dem_async: ExeFunctionAsync
depth2el_async: ExeFunctionAsync
dip_async: ExeFunctionAsync
dist2surf_async: ExeFunctionAsync
distribute_async: ExeFunctionAsync
drawtree_async: ExeFunctionAsync
dumgrid_async: ExeFunctionAsync
dump_async: ExeFunctionAsync
dxf_async: ExeFunctionAsync
dxfexport_async: ExeFunctionAsync
dxfscale_async: ExeFunctionAsync
el2depth_async: ExeFunctionAsync
ev2gocad_async: ExeFunctionAsync
ev2zycorgrid_async: ExeFunctionAsync
export_async: ExeFunctionAsync
extendavgrd_async: ExeFunctionAsync
extendwell_async: ExeFunctionAsync
extract_async: ExeFunctionAsync
facedump_async: ExeFunctionAsync
facescut_async: ExeFunctionAsync
facesedit_async: ExeFunctionAsync
facestostl_async: ExeFunctionAsync
facestox3d_async: ExeFunctionAsync
faultgrid_async: ExeFunctionAsync
fgr_async: ExeFunctionAsync
field_async: ExeFunctionAsync
fieldedit_async: ExeFunctionAsync
filedump_async: ExeFunctionAsync
fill_async: ExeFunctionAsync
filter_async: ExeFunctionAsync
flow3grid_async: ExeFunctionAsync
flttic_async: ExeFunctionAsync
fp_async: ExeFunctionAsync
fpfp2fp_async: ExeFunctionAsync
geoconf_async: ExeFunctionAsync
geodistribute_async: ExeFunctionAsync
getSWdataO11_async: ExeFunctionAsync
getSWdataR510_async: ExeFunctionAsync
getSWfaultDataO11_async: ExeFunctionAsync
getdataO11_async: ExeFunctionAsync
getmapdataO11_async: ExeFunctionAsync
grid2im_async: ExeFunctionAsync
gridcurtain_async: ExeFunctionAsync
gridedit_async: ExeFunctionAsync
gridrangepoly_async: ExeFunctionAsync
gridslice_async: ExeFunctionAsync
gridto4dv_async: ExeFunctionAsync
gridtoimage_async: ExeFunctionAsync
hgadjust_async: ExeFunctionAsync
hgbak_async: ExeFunctionAsync
hgface_async: ExeFunctionAsync
hgfor_async: ExeFunctionAsync
hgframe_async: ExeFunctionAsync
hglabel_async: ExeFunctionAsync
hgmk_async: ExeFunctionAsync
hgrev_async: ExeFunctionAsync
hgspace_async: ExeFunctionAsync
hgthrow_async: ExeFunctionAsync
ht2gd_async: ExeFunctionAsync
ht2sh_async: ExeFunctionAsync
imageplt_async: ExeFunctionAsync
imagexsec_async: ExeFunctionAsync
imregtotfw_async: ExeFunctionAsync
insttoave_async: ExeFunctionAsync
inter_async: ExeFunctionAsync
interpolate_async: ExeFunctionAsync
irrslice_async: ExeFunctionAsync
isochore_async: ExeFunctionAsync
it2sh_async: ExeFunctionAsync
iwdplothelper_async: ExeFunctionAsync
juxtapos_async: ExeFunctionAsync
kml_async: ExeFunctionAsync
krig_async: ExeFunctionAsync
label_async: ExeFunctionAsync
legend_async: ExeFunctionAsync
lgd_async: ExeFunctionAsync
license_async: ExeFunctionAsync
linemake_async: ExeFunctionAsync
lineplot_async: ExeFunctionAsync
linepost_async: ExeFunctionAsync
listplot_async: ExeFunctionAsync
localgrid_async: ExeFunctionAsync
makedat_async: ExeFunctionAsync
makestitchpts_async: ExeFunctionAsync
maplabel_async: ExeFunctionAsync
merge_async: ExeFunctionAsync
mgridedit_async: ExeFunctionAsync
mgridexport_async: ExeFunctionAsync
mgridimport_async: ExeFunctionAsync
mgridinfo_async: ExeFunctionAsync
minmax2pivotrange_async: ExeFunctionAsync
modquery_async: ExeFunctionAsync
nearestneighbors_async: ExeFunctionAsync
netpay_async: ExeFunctionAsync
new_cps2ev_async: ExeFunctionAsync
nodepost_async: ExeFunctionAsync
package_async: ExeFunctionAsync
paginateVolTxtRpt_async: ExeFunctionAsync
pause_async: ExeFunctionAsync
pick_async: ExeFunctionAsync
piechart_async: ExeFunctionAsync
plotserver_async: ExeFunctionAsync
pltconvert_async: ExeFunctionAsync
ply2ann_async: ExeFunctionAsync
plyarea_async: ExeFunctionAsync
plybld_async: ExeFunctionAsync
plybop_async: ExeFunctionAsync
plyhull_async: ExeFunctionAsync
post_async: ExeFunctionAsync
propbak_async: ExeFunctionAsync
ptinpoly_async: ExeFunctionAsync
putSWseismicO11_async: ExeFunctionAsync
putSWseismicR510_async: ExeFunctionAsync
putmapdataO11_async: ExeFunctionAsync
raft_async: ExeFunctionAsync
rangepoly_async: ExeFunctionAsync
rawdump_async: ExeFunctionAsync
reportprogress_async: ExeFunctionAsync
rerotate_async: ExeFunctionAsync
reverseSlash_async: ExeFunctionAsync
scale_async: ExeFunctionAsync
sec_async: ExeFunctionAsync
segy2ev_async: ExeFunctionAsync
segyimport_async: ExeFunctionAsync
seq2avgrd_async: ExeFunctionAsync
seq2igrd_async: ExeFunctionAsync
seq2wfp_async: ExeFunctionAsync
seqbuild_async: ExeFunctionAsync
seqedit_async: ExeFunctionAsync
seqvol_async: ExeFunctionAsync
sgrid2pdat_async: ExeFunctionAsync
shapeexport_async: ExeFunctionAsync
shapeimport_async: ExeFunctionAsync
slice_async: ExeFunctionAsync
smooth_async: ExeFunctionAsync
sort_async: ExeFunctionAsync
stat_async: ExeFunctionAsync
surfclip_async: ExeFunctionAsync
surfer_async: ExeFunctionAsync
surfhide_async: ExeFunctionAsync
sysinfo_async: ExeFunctionAsync
t2d_async: ExeFunctionAsync
tfwtoimreg_async: ExeFunctionAsync
thickness_async: ExeFunctionAsync
tieline_async: ExeFunctionAsync
tree_async: ExeFunctionAsync
truedip_async: ExeFunctionAsync
truemerge_async: ExeFunctionAsync
tsd_async: ExeFunctionAsync
tst_async: ExeFunctionAsync
tsurf4dv_async: ExeFunctionAsync
tunface_async: ExeFunctionAsync
ulpcmp_async: ExeFunctionAsync
vario_async: ExeFunctionAsync
vect2grid_async: ExeFunctionAsync
viewipc_async: ExeFunctionAsync
volcomp_async: ExeFunctionAsync
volume_async: ExeFunctionAsync
voxet2grd_async: ExeFunctionAsync
vs2pdat_async: ExeFunctionAsync
wellDataPlot_async: ExeFunctionAsync
wellpath_async: ExeFunctionAsync
wellprofile_async: ExeFunctionAsync
wellstrc_async: ExeFunctionAsync
wellsurvey_async: ExeFunctionAsync
welltube_async: ExeFunctionAsync
wfp2seq_async: ExeFunctionAsync
wl2path_async: ExeFunctionAsync
wp2igrd_async: ExeFunctionAsync
x2face_async: ExeFunctionAsync
xformdata_async: ExeFunctionAsync
xsec_async: ExeFunctionAsync
zgfimport_async: ExeFunctionAsync
zmapgridimport_async: ExeFunctionAsync
zonlin_async: ExeFunctionAsync
zonply_async: ExeFunctionAsync
zonpnt_async: ExeFunctionAsync
