from pathlib import Path
from rich.console import Console

CONTEXT_SETTINGS = {"help_option_names": ["-h", "--help"]}
CLI_NAME = "CodeMie Test Harness"
CONSOLE = Console()

CONFIG_DIR = Path.home() / ".codemie"
CONFIG_FILE = CONFIG_DIR / "test-harness.json"

# Keys (env and config)
KEY_AUTH_SERVER_URL = "AUTH_SERVER_URL"
KEY_AUTH_CLIENT_ID = "AUTH_CLIENT_ID"
KEY_AUTH_CLIENT_SECRET = "AUTH_CLIENT_SECRET"
KEY_AUTH_REALM_NAME = "AUTH_REALM_NAME"
KEY_CODEMIE_API_DOMAIN = "CODEMIE_API_DOMAIN"
KEY_MARKS = "PYTEST_MARKS"
KEY_XDIST_N = "PYTEST_N"
KEY_RERUNS = "PYTEST_RERUNS"

# Integrations / external systems
KEY_GIT_ENV = "GIT_ENV"  # e.g. gitlab or github
# GitLab
KEY_GITLAB_URL = "GITLAB_URL"
KEY_GITLAB_TOKEN = "GITLAB_TOKEN"
KEY_GITLAB_PROJECT = "GITLAB_PROJECT"
KEY_GITLAB_PROJECT_ID = "GITLAB_PROJECT_ID"
# GitHub
KEY_GITHUB_URL = "GITHUB_URL"
KEY_GITHUB_TOKEN = "GITHUB_TOKEN"
KEY_GITHUB_PROJECT = "GITHUB_PROJECT"
# JIRA
KEY_JIRA_URL = "JIRA_URL"
KEY_JIRA_TOKEN = "JIRA_TOKEN"
KEY_JQL = "JQL"
# Confluence
KEY_CONFLUENCE_URL = "CONFLUENCE_URL"
KEY_CONFLUENCE_TOKEN = "CONFLUENCE_TOKEN"
KEY_CQL = "CQL"

DEFAULT_MARKS = "smoke"
DEFAULT_XDIST_N = 8
DEFAULT_RERUNS = 2

AUTH_KEYS = [
    KEY_AUTH_SERVER_URL,
    KEY_AUTH_CLIENT_ID,
    KEY_AUTH_CLIENT_SECRET,
    KEY_AUTH_REALM_NAME,
    KEY_CODEMIE_API_DOMAIN,
]

INTEGRATION_KEYS = [
    KEY_GIT_ENV,
    KEY_GITLAB_URL,
    KEY_GITLAB_TOKEN,
    KEY_GITLAB_PROJECT,
    KEY_GITLAB_PROJECT_ID,
    KEY_GITHUB_URL,
    KEY_GITHUB_TOKEN,
    KEY_GITHUB_PROJECT,
    KEY_JIRA_URL,
    KEY_JIRA_TOKEN,
    KEY_JQL,
    KEY_CONFLUENCE_URL,
    KEY_CONFLUENCE_TOKEN,
    KEY_CQL,
]
