from typing import IO, Any, Callable, TypeVar

F = TypeVar("F", bound=Callable[..., Any])

def abort_if_false(ctx: Any, param: Any, value: Any) -> None: ...
def search_version_check(f: F) -> F: ...

# Click group and commands

def index() -> None: ...
def check() -> None: ...
def init(force: bool) -> None: ...
def destroy(force: bool) -> None: ...
def create(index_name: str, body: IO[str], force: bool, verbose: bool) -> None: ...
def update(index_name: str, check: bool = ...) -> None: ...
def list_cmd(only_active: bool, only_aliases: bool, verbose: bool) -> None: ...
def delete(index_name: str, force: bool, verbose: bool) -> None: ...
def put(
    index_name: str, identifier: str | None, body: IO[str], force: bool, verbose: bool
) -> None: ...
