depends = ('ITKPyBase', 'ITKImageFilterBase', )
templates = (  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterISS2VISS2', True, 'itk::Image< signed short,2 >, itk::VectorImage< signed short,2 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIUC2VIUC2', True, 'itk::Image< unsigned char,2 >, itk::VectorImage< unsigned char,2 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIUS2VIUS2', True, 'itk::Image< unsigned short,2 >, itk::VectorImage< unsigned short,2 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIF2VIF2', True, 'itk::Image< float,2 >, itk::VectorImage< float,2 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterID2VID2', True, 'itk::Image< double,2 >, itk::VectorImage< double,2 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterISS3VISS3', True, 'itk::Image< signed short,3 >, itk::VectorImage< signed short,3 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIUC3VIUC3', True, 'itk::Image< unsigned char,3 >, itk::VectorImage< unsigned char,3 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIUS3VIUS3', True, 'itk::Image< unsigned short,3 >, itk::VectorImage< unsigned short,3 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIF3VIF3', True, 'itk::Image< float,3 >, itk::VectorImage< float,3 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterID3VID3', True, 'itk::Image< double,3 >, itk::VectorImage< double,3 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterISS4VISS4', True, 'itk::Image< signed short,4 >, itk::VectorImage< signed short,4 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIUC4VIUC4', True, 'itk::Image< unsigned char,4 >, itk::VectorImage< unsigned char,4 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIUS4VIUS4', True, 'itk::Image< unsigned short,4 >, itk::VectorImage< unsigned short,4 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIF4VIF4', True, 'itk::Image< float,4 >, itk::VectorImage< float,4 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterID4VID4', True, 'itk::Image< double,4 >, itk::VectorImage< double,4 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIF2ICVF22', True, 'itk::Image< float,2 >, itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIF2ICVF32', True, 'itk::Image< float,2 >, itk::Image< itk::CovariantVector< float,3 >,2 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIF2ICVF42', True, 'itk::Image< float,2 >, itk::Image< itk::CovariantVector< float,4 >,2 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIF3ICVF23', True, 'itk::Image< float,3 >, itk::Image< itk::CovariantVector< float,2 >,3 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIF3ICVF33', True, 'itk::Image< float,3 >, itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIF3ICVF43', True, 'itk::Image< float,3 >, itk::Image< itk::CovariantVector< float,4 >,3 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIF2IVF22', True, 'itk::Image< float,2 >, itk::Image< itk::Vector< float,2 >,2 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIF2IVF32', True, 'itk::Image< float,2 >, itk::Image< itk::Vector< float,3 >,2 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIF2IVF42', True, 'itk::Image< float,2 >, itk::Image< itk::Vector< float,4 >,2 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIF3IVF23', True, 'itk::Image< float,3 >, itk::Image< itk::Vector< float,2 >,3 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIF3IVF33', True, 'itk::Image< float,3 >, itk::Image< itk::Vector< float,3 >,3 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIF3IVF43', True, 'itk::Image< float,3 >, itk::Image< itk::Vector< float,4 >,3 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIUC2IRGBAUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< itk::RGBAPixel< unsigned char >,2 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIUC3IRGBAUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< itk::RGBAPixel< unsigned char >,3 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIUC4IRGBAUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< itk::RGBAPixel< unsigned char >,4 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIUC2IRGBUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< itk::RGBPixel< unsigned char >,2 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIUC3IRGBUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< itk::RGBPixel< unsigned char >,3 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIUC4IRGBUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< itk::RGBPixel< unsigned char >,4 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIF2ICF2', True, 'itk::Image< float,2 >, itk::Image< std::complex< float >,2 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIF3ICF3', True, 'itk::Image< float,3 >, itk::Image< std::complex< float >,3 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterIF4ICF4', True, 'itk::Image< float,4 >, itk::Image< std::complex< float >,4 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterID2ICD2', True, 'itk::Image< double,2 >, itk::Image< std::complex< double >,2 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterID3ICD3', True, 'itk::Image< double,3 >, itk::Image< std::complex< double >,3 >'),
  ('ComposeImageFilter', 'itk::ComposeImageFilter', 'itkComposeImageFilterID4ICD4', True, 'itk::Image< double,4 >, itk::Image< std::complex< double >,4 >'),
  ('JoinSeriesImageFilter', 'itk::JoinSeriesImageFilter', 'itkJoinSeriesImageFilterISS2ISS3', True, 'itk::Image< signed short,2 >,itk::Image< signed short,3 >'),
  ('JoinSeriesImageFilter', 'itk::JoinSeriesImageFilter', 'itkJoinSeriesImageFilterIUC2IUC3', True, 'itk::Image< unsigned char,2 >,itk::Image< unsigned char,3 >'),
  ('JoinSeriesImageFilter', 'itk::JoinSeriesImageFilter', 'itkJoinSeriesImageFilterIUS2IUS3', True, 'itk::Image< unsigned short,2 >,itk::Image< unsigned short,3 >'),
  ('JoinSeriesImageFilter', 'itk::JoinSeriesImageFilter', 'itkJoinSeriesImageFilterIF2IF3', True, 'itk::Image< float,2 >,itk::Image< float,3 >'),
  ('JoinSeriesImageFilter', 'itk::JoinSeriesImageFilter', 'itkJoinSeriesImageFilterID2ID3', True, 'itk::Image< double,2 >,itk::Image< double,3 >'),
  ('JoinSeriesImageFilter', 'itk::JoinSeriesImageFilter', 'itkJoinSeriesImageFilterISS2ISS4', True, 'itk::Image< signed short,2 >,itk::Image< signed short,4 >'),
  ('JoinSeriesImageFilter', 'itk::JoinSeriesImageFilter', 'itkJoinSeriesImageFilterIUC2IUC4', True, 'itk::Image< unsigned char,2 >,itk::Image< unsigned char,4 >'),
  ('JoinSeriesImageFilter', 'itk::JoinSeriesImageFilter', 'itkJoinSeriesImageFilterIUS2IUS4', True, 'itk::Image< unsigned short,2 >,itk::Image< unsigned short,4 >'),
  ('JoinSeriesImageFilter', 'itk::JoinSeriesImageFilter', 'itkJoinSeriesImageFilterIF2IF4', True, 'itk::Image< float,2 >,itk::Image< float,4 >'),
  ('JoinSeriesImageFilter', 'itk::JoinSeriesImageFilter', 'itkJoinSeriesImageFilterID2ID4', True, 'itk::Image< double,2 >,itk::Image< double,4 >'),
  ('JoinSeriesImageFilter', 'itk::JoinSeriesImageFilter', 'itkJoinSeriesImageFilterISS3ISS4', True, 'itk::Image< signed short,3 >,itk::Image< signed short,4 >'),
  ('JoinSeriesImageFilter', 'itk::JoinSeriesImageFilter', 'itkJoinSeriesImageFilterIUC3IUC4', True, 'itk::Image< unsigned char,3 >,itk::Image< unsigned char,4 >'),
  ('JoinSeriesImageFilter', 'itk::JoinSeriesImageFilter', 'itkJoinSeriesImageFilterIUS3IUS4', True, 'itk::Image< unsigned short,3 >,itk::Image< unsigned short,4 >'),
  ('JoinSeriesImageFilter', 'itk::JoinSeriesImageFilter', 'itkJoinSeriesImageFilterIF3IF4', True, 'itk::Image< float,3 >,itk::Image< float,4 >'),
  ('JoinSeriesImageFilter', 'itk::JoinSeriesImageFilter', 'itkJoinSeriesImageFilterID3ID4', True, 'itk::Image< double,3 >,itk::Image< double,4 >'),
)
factories = ()
