depends = ('ITKPyBase', 'ITKTransform', )
templates = (  ('Mesh', 'itk::Mesh', 'itkMeshSS2', True, 'signed short,2'),
  ('Mesh', 'itk::Mesh', 'itkMeshUC2', True, 'unsigned char,2'),
  ('Mesh', 'itk::Mesh', 'itkMeshUS2', True, 'unsigned short,2'),
  ('Mesh', 'itk::Mesh', 'itkMeshF2', True, 'float,2'),
  ('Mesh', 'itk::Mesh', 'itkMeshD2', True, 'double,2'),
  ('Mesh', 'itk::Mesh', 'itkMeshAD2', True, 'itk::Array<double>,2'),
  ('Mesh', 'itk::Mesh', 'itkMeshSS3', True, 'signed short,3'),
  ('Mesh', 'itk::Mesh', 'itkMeshUC3', True, 'unsigned char,3'),
  ('Mesh', 'itk::Mesh', 'itkMeshUS3', True, 'unsigned short,3'),
  ('Mesh', 'itk::Mesh', 'itkMeshF3', True, 'float,3'),
  ('Mesh', 'itk::Mesh', 'itkMeshD3', True, 'double,3'),
  ('Mesh', 'itk::Mesh', 'itkMeshAD3', True, 'itk::Array<double>,3'),
  ('Mesh', 'itk::Mesh', 'itkMeshSS4', True, 'signed short,4'),
  ('Mesh', 'itk::Mesh', 'itkMeshUC4', True, 'unsigned char,4'),
  ('Mesh', 'itk::Mesh', 'itkMeshUS4', True, 'unsigned short,4'),
  ('Mesh', 'itk::Mesh', 'itkMeshF4', True, 'float,4'),
  ('Mesh', 'itk::Mesh', 'itkMeshD4', True, 'double,4'),
  ('Mesh', 'itk::Mesh', 'itkMeshAD4', True, 'itk::Array<double>,4'),
  ('CellTraitsInfo', 'itk::CellTraitsInfo', 'itkCellTraitsInfo2FFULULULPF2MCULPF2', False, '2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::MapContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long >'),
  ('CellTraitsInfo', 'itk::CellTraitsInfo', 'itkCellTraitsInfo2FFULULULPF2VCULPF2', False, '2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::VectorContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long >'),
  ('CellTraitsInfo', 'itk::CellTraitsInfo', 'itkCellTraitsInfo3FFULULULPF3MCULPF3', False, '3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::MapContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long >'),
  ('CellTraitsInfo', 'itk::CellTraitsInfo', 'itkCellTraitsInfo3FFULULULPF3VCULPF3', False, '3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::VectorContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long >'),
  ('CellTraitsInfo', 'itk::CellTraitsInfo', 'itkCellTraitsInfo4FFULULULPF4MCULPF4', False, '4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::MapContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long >'),
  ('CellTraitsInfo', 'itk::CellTraitsInfo', 'itkCellTraitsInfo4FFULULULPF4VCULPF4', False, '4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::VectorContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceSSCTI2FFULULULPF2MCULPF2', False, 'signed short,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::MapContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceSSCTI2FFULULULPF2VCULPF2', False, 'signed short,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::VectorContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceUCCTI2FFULULULPF2MCULPF2', False, 'unsigned char,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::MapContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceUCCTI2FFULULULPF2VCULPF2', False, 'unsigned char,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::VectorContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceUSCTI2FFULULULPF2MCULPF2', False, 'unsigned short,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::MapContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceUSCTI2FFULULULPF2VCULPF2', False, 'unsigned short,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::VectorContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceFCTI2FFULULULPF2MCULPF2', False, 'float,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::MapContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceFCTI2FFULULULPF2VCULPF2', False, 'float,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::VectorContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceDCTI2FFULULULPF2MCULPF2', False, 'double,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::MapContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceDCTI2FFULULULPF2VCULPF2', False, 'double,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::VectorContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceADCTI2FFULULULPF2VCULPF2', False, 'itk::Array< double >,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::VectorContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceSSCTI3FFULULULPF3MCULPF3', False, 'signed short,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::MapContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceSSCTI3FFULULULPF3VCULPF3', False, 'signed short,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::VectorContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceUCCTI3FFULULULPF3MCULPF3', False, 'unsigned char,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::MapContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceUCCTI3FFULULULPF3VCULPF3', False, 'unsigned char,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::VectorContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceUSCTI3FFULULULPF3MCULPF3', False, 'unsigned short,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::MapContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceUSCTI3FFULULULPF3VCULPF3', False, 'unsigned short,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::VectorContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceFCTI3FFULULULPF3MCULPF3', False, 'float,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::MapContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceFCTI3FFULULULPF3VCULPF3', False, 'float,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::VectorContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceDCTI3FFULULULPF3MCULPF3', False, 'double,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::MapContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceDCTI3FFULULULPF3VCULPF3', False, 'double,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::VectorContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceADCTI3FFULULULPF3VCULPF3', False, 'itk::Array< double >,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::VectorContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceSSCTI4FFULULULPF4MCULPF4', False, 'signed short,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::MapContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceSSCTI4FFULULULPF4VCULPF4', False, 'signed short,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::VectorContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceUCCTI4FFULULULPF4MCULPF4', False, 'unsigned char,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::MapContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceUCCTI4FFULULULPF4VCULPF4', False, 'unsigned char,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::VectorContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceUSCTI4FFULULULPF4MCULPF4', False, 'unsigned short,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::MapContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceUSCTI4FFULULULPF4VCULPF4', False, 'unsigned short,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::VectorContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceFCTI4FFULULULPF4MCULPF4', False, 'float,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::MapContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceFCTI4FFULULULPF4VCULPF4', False, 'float,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::VectorContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceDCTI4FFULULULPF4MCULPF4', False, 'double,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::MapContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceDCTI4FFULULULPF4VCULPF4', False, 'double,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::VectorContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceADCTI4FFULULULPF4VCULPF4', False, 'itk::Array< double >,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::VectorContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > >'),
  ('MapContainer', 'itk::MapContainer', 'itkMapContainerULCISSCTI2FFULULULPF2MCULPF2', False, 'unsigned long, itk::CellInterface< signed short,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::MapContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > > > *'),
  ('MapContainer', 'itk::MapContainer', 'itkMapContainerULCIUCCTI2FFULULULPF2MCULPF2', False, 'unsigned long, itk::CellInterface< unsigned char,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::MapContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > > > *'),
  ('MapContainer', 'itk::MapContainer', 'itkMapContainerULCIUSCTI2FFULULULPF2MCULPF2', False, 'unsigned long, itk::CellInterface< unsigned short,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::MapContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > > > *'),
  ('MapContainer', 'itk::MapContainer', 'itkMapContainerULCIFCTI2FFULULULPF2MCULPF2', False, 'unsigned long, itk::CellInterface< float,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::MapContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > > > *'),
  ('MapContainer', 'itk::MapContainer', 'itkMapContainerULCIDCTI2FFULULULPF2MCULPF2', False, 'unsigned long, itk::CellInterface< double,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::MapContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > > > *'),
  ('MapContainer', 'itk::MapContainer', 'itkMapContainerULCISSCTI3FFULULULPF3MCULPF3', False, 'unsigned long, itk::CellInterface< signed short,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::MapContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > > > *'),
  ('MapContainer', 'itk::MapContainer', 'itkMapContainerULCIUCCTI3FFULULULPF3MCULPF3', False, 'unsigned long, itk::CellInterface< unsigned char,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::MapContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > > > *'),
  ('MapContainer', 'itk::MapContainer', 'itkMapContainerULCIUSCTI3FFULULULPF3MCULPF3', False, 'unsigned long, itk::CellInterface< unsigned short,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::MapContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > > > *'),
  ('MapContainer', 'itk::MapContainer', 'itkMapContainerULCIFCTI3FFULULULPF3MCULPF3', False, 'unsigned long, itk::CellInterface< float,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::MapContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > > > *'),
  ('MapContainer', 'itk::MapContainer', 'itkMapContainerULCIDCTI3FFULULULPF3MCULPF3', False, 'unsigned long, itk::CellInterface< double,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::MapContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > > > *'),
  ('MapContainer', 'itk::MapContainer', 'itkMapContainerULCISSCTI4FFULULULPF4MCULPF4', False, 'unsigned long, itk::CellInterface< signed short,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::MapContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > > > *'),
  ('MapContainer', 'itk::MapContainer', 'itkMapContainerULCIUCCTI4FFULULULPF4MCULPF4', False, 'unsigned long, itk::CellInterface< unsigned char,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::MapContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > > > *'),
  ('MapContainer', 'itk::MapContainer', 'itkMapContainerULCIUSCTI4FFULULULPF4MCULPF4', False, 'unsigned long, itk::CellInterface< unsigned short,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::MapContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > > > *'),
  ('MapContainer', 'itk::MapContainer', 'itkMapContainerULCIFCTI4FFULULULPF4MCULPF4', False, 'unsigned long, itk::CellInterface< float,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::MapContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > > > *'),
  ('MapContainer', 'itk::MapContainer', 'itkMapContainerULCIDCTI4FFULULULPF4MCULPF4', False, 'unsigned long, itk::CellInterface< double,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::MapContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > > > *'),
  ('VectorContainer', 'itk::VectorContainer', 'itkVectorContainerULCISSCTI2FFULULULPF2VCULPF2', False, 'unsigned long, itk::CellInterface< signed short,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::VectorContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > > > *'),
  ('VectorContainer', 'itk::VectorContainer', 'itkVectorContainerULCIUCCTI2FFULULULPF2VCULPF2', False, 'unsigned long, itk::CellInterface< unsigned char,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::VectorContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > > > *'),
  ('VectorContainer', 'itk::VectorContainer', 'itkVectorContainerULCIUSCTI2FFULULULPF2VCULPF2', False, 'unsigned long, itk::CellInterface< unsigned short,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::VectorContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > > > *'),
  ('VectorContainer', 'itk::VectorContainer', 'itkVectorContainerULCIFCTI2FFULULULPF2VCULPF2', False, 'unsigned long, itk::CellInterface< float,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::VectorContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > > > *'),
  ('VectorContainer', 'itk::VectorContainer', 'itkVectorContainerULCIDCTI2FFULULULPF2VCULPF2', False, 'unsigned long, itk::CellInterface< double,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::VectorContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > > > *'),
  ('VectorContainer', 'itk::VectorContainer', 'itkVectorContainerULCIADCTI2FFULULULPF2VCULPF2', False, 'unsigned long, itk::CellInterface< itk::Array< double >,itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::VectorContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > > > *'),
  ('VectorContainer', 'itk::VectorContainer', 'itkVectorContainerULCISSCTI3FFULULULPF3VCULPF3', False, 'unsigned long, itk::CellInterface< signed short,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::VectorContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > > > *'),
  ('VectorContainer', 'itk::VectorContainer', 'itkVectorContainerULCIUCCTI3FFULULULPF3VCULPF3', False, 'unsigned long, itk::CellInterface< unsigned char,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::VectorContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > > > *'),
  ('VectorContainer', 'itk::VectorContainer', 'itkVectorContainerULCIUSCTI3FFULULULPF3VCULPF3', False, 'unsigned long, itk::CellInterface< unsigned short,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::VectorContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > > > *'),
  ('VectorContainer', 'itk::VectorContainer', 'itkVectorContainerULCIFCTI3FFULULULPF3VCULPF3', False, 'unsigned long, itk::CellInterface< float,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::VectorContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > > > *'),
  ('VectorContainer', 'itk::VectorContainer', 'itkVectorContainerULCIDCTI3FFULULULPF3VCULPF3', False, 'unsigned long, itk::CellInterface< double,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::VectorContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > > > *'),
  ('VectorContainer', 'itk::VectorContainer', 'itkVectorContainerULCIADCTI3FFULULULPF3VCULPF3', False, 'unsigned long, itk::CellInterface< itk::Array< double >,itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::VectorContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > > > *'),
  ('VectorContainer', 'itk::VectorContainer', 'itkVectorContainerULCISSCTI4FFULULULPF4VCULPF4', False, 'unsigned long, itk::CellInterface< signed short,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::VectorContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > > > *'),
  ('VectorContainer', 'itk::VectorContainer', 'itkVectorContainerULCIUCCTI4FFULULULPF4VCULPF4', False, 'unsigned long, itk::CellInterface< unsigned char,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::VectorContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > > > *'),
  ('VectorContainer', 'itk::VectorContainer', 'itkVectorContainerULCIUSCTI4FFULULULPF4VCULPF4', False, 'unsigned long, itk::CellInterface< unsigned short,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::VectorContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > > > *'),
  ('VectorContainer', 'itk::VectorContainer', 'itkVectorContainerULCIFCTI4FFULULULPF4VCULPF4', False, 'unsigned long, itk::CellInterface< float,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::VectorContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > > > *'),
  ('VectorContainer', 'itk::VectorContainer', 'itkVectorContainerULCIDCTI4FFULULULPF4VCULPF4', False, 'unsigned long, itk::CellInterface< double,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::VectorContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > > > *'),
  ('VectorContainer', 'itk::VectorContainer', 'itkVectorContainerULCIADCTI4FFULULULPF4VCULPF4', False, 'unsigned long, itk::CellInterface< itk::Array< double >,itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::VectorContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > > > *'),
  ('CellInterfaceVisitor', 'itk::CellInterfaceVisitor', 'itkCellInterfaceVisitorSSCTI2FFULULULPF2MCULPF2', False, 'signed short, itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::MapContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > > '),
  ('CellInterfaceVisitor', 'itk::CellInterfaceVisitor', 'itkCellInterfaceVisitorUCCTI2FFULULULPF2MCULPF2', False, 'unsigned char, itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::MapContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > > '),
  ('CellInterfaceVisitor', 'itk::CellInterfaceVisitor', 'itkCellInterfaceVisitorUSCTI2FFULULULPF2MCULPF2', False, 'unsigned short, itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::MapContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > > '),
  ('CellInterfaceVisitor', 'itk::CellInterfaceVisitor', 'itkCellInterfaceVisitorFCTI2FFULULULPF2MCULPF2', False, 'float, itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::MapContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > > '),
  ('CellInterfaceVisitor', 'itk::CellInterfaceVisitor', 'itkCellInterfaceVisitorDCTI2FFULULULPF2MCULPF2', False, 'double, itk::CellTraitsInfo< 2,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,2 >,itk::MapContainer< unsigned long,itk::Point< float,2 > >, std::set< unsigned long > > '),
  ('CellInterfaceVisitor', 'itk::CellInterfaceVisitor', 'itkCellInterfaceVisitorSSCTI3FFULULULPF3MCULPF3', False, 'signed short, itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::MapContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > > '),
  ('CellInterfaceVisitor', 'itk::CellInterfaceVisitor', 'itkCellInterfaceVisitorUCCTI3FFULULULPF3MCULPF3', False, 'unsigned char, itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::MapContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > > '),
  ('CellInterfaceVisitor', 'itk::CellInterfaceVisitor', 'itkCellInterfaceVisitorUSCTI3FFULULULPF3MCULPF3', False, 'unsigned short, itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::MapContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > > '),
  ('CellInterfaceVisitor', 'itk::CellInterfaceVisitor', 'itkCellInterfaceVisitorFCTI3FFULULULPF3MCULPF3', False, 'float, itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::MapContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > > '),
  ('CellInterfaceVisitor', 'itk::CellInterfaceVisitor', 'itkCellInterfaceVisitorDCTI3FFULULULPF3MCULPF3', False, 'double, itk::CellTraitsInfo< 3,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,3 >,itk::MapContainer< unsigned long,itk::Point< float,3 > >, std::set< unsigned long > > '),
  ('CellInterfaceVisitor', 'itk::CellInterfaceVisitor', 'itkCellInterfaceVisitorSSCTI4FFULULULPF4MCULPF4', False, 'signed short, itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::MapContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > > '),
  ('CellInterfaceVisitor', 'itk::CellInterfaceVisitor', 'itkCellInterfaceVisitorUCCTI4FFULULULPF4MCULPF4', False, 'unsigned char, itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::MapContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > > '),
  ('CellInterfaceVisitor', 'itk::CellInterfaceVisitor', 'itkCellInterfaceVisitorUSCTI4FFULULULPF4MCULPF4', False, 'unsigned short, itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::MapContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > > '),
  ('CellInterfaceVisitor', 'itk::CellInterfaceVisitor', 'itkCellInterfaceVisitorFCTI4FFULULULPF4MCULPF4', False, 'float, itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::MapContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > > '),
  ('CellInterfaceVisitor', 'itk::CellInterfaceVisitor', 'itkCellInterfaceVisitorDCTI4FFULULULPF4MCULPF4', False, 'double, itk::CellTraitsInfo< 4,float,float,unsigned long,unsigned long,unsigned long,itk::Point< float,4 >,itk::MapContainer< unsigned long,itk::Point< float,4 > >, std::set< unsigned long > > '),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourcePSSS2', True, 'itk::PointSet< signed short,2 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourceMSS2', True, 'itk::Mesh< signed short,2 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourcePSUC2', True, 'itk::PointSet< unsigned char,2 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourceMUC2', True, 'itk::Mesh< unsigned char,2 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourcePSUS2', True, 'itk::PointSet< unsigned short,2 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourceMUS2', True, 'itk::Mesh< unsigned short,2 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourcePSF2', True, 'itk::PointSet< float,2 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourceMF2', True, 'itk::Mesh< float,2 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourcePSD2', True, 'itk::PointSet< double,2 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourceMD2', True, 'itk::Mesh< double,2 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourcePSSS3', True, 'itk::PointSet< signed short,3 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourceMSS3', True, 'itk::Mesh< signed short,3 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourcePSUC3', True, 'itk::PointSet< unsigned char,3 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourceMUC3', True, 'itk::Mesh< unsigned char,3 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourcePSUS3', True, 'itk::PointSet< unsigned short,3 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourceMUS3', True, 'itk::Mesh< unsigned short,3 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourcePSF3', True, 'itk::PointSet< float,3 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourceMF3', True, 'itk::Mesh< float,3 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourcePSD3', True, 'itk::PointSet< double,3 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourceMD3', True, 'itk::Mesh< double,3 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourcePSSS4', True, 'itk::PointSet< signed short,4 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourceMSS4', True, 'itk::Mesh< signed short,4 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourcePSUC4', True, 'itk::PointSet< unsigned char,4 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourceMUC4', True, 'itk::Mesh< unsigned char,4 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourcePSUS4', True, 'itk::PointSet< unsigned short,4 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourceMUS4', True, 'itk::Mesh< unsigned short,4 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourcePSF4', True, 'itk::PointSet< float,4 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourceMF4', True, 'itk::Mesh< float,4 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourcePSD4', True, 'itk::PointSet< double,4 >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourceMD4', True, 'itk::Mesh< double,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS2MSS2', True, 'itk::Image< signed short,2 >, itk::Mesh< signed short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS2PSSS2', True, 'itk::Image< signed short,2 >, itk::PointSet< signed short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS2MUC2', True, 'itk::Image< signed short,2 >, itk::Mesh< unsigned char,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS2PSUC2', True, 'itk::Image< signed short,2 >, itk::PointSet< unsigned char,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS2MUS2', True, 'itk::Image< signed short,2 >, itk::Mesh< unsigned short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS2PSUS2', True, 'itk::Image< signed short,2 >, itk::PointSet< unsigned short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS2MF2', True, 'itk::Image< signed short,2 >, itk::Mesh< float,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS2PSF2', True, 'itk::Image< signed short,2 >, itk::PointSet< float,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS2MD2', True, 'itk::Image< signed short,2 >, itk::Mesh< double,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS2PSD2', True, 'itk::Image< signed short,2 >, itk::PointSet< double,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC2MSS2', True, 'itk::Image< unsigned char,2 >, itk::Mesh< signed short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC2PSSS2', True, 'itk::Image< unsigned char,2 >, itk::PointSet< signed short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC2MUC2', True, 'itk::Image< unsigned char,2 >, itk::Mesh< unsigned char,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC2PSUC2', True, 'itk::Image< unsigned char,2 >, itk::PointSet< unsigned char,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC2MUS2', True, 'itk::Image< unsigned char,2 >, itk::Mesh< unsigned short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC2PSUS2', True, 'itk::Image< unsigned char,2 >, itk::PointSet< unsigned short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC2MF2', True, 'itk::Image< unsigned char,2 >, itk::Mesh< float,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC2PSF2', True, 'itk::Image< unsigned char,2 >, itk::PointSet< float,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC2MD2', True, 'itk::Image< unsigned char,2 >, itk::Mesh< double,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC2PSD2', True, 'itk::Image< unsigned char,2 >, itk::PointSet< double,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS2MSS2', True, 'itk::Image< unsigned short,2 >, itk::Mesh< signed short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS2PSSS2', True, 'itk::Image< unsigned short,2 >, itk::PointSet< signed short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS2MUC2', True, 'itk::Image< unsigned short,2 >, itk::Mesh< unsigned char,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS2PSUC2', True, 'itk::Image< unsigned short,2 >, itk::PointSet< unsigned char,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS2MUS2', True, 'itk::Image< unsigned short,2 >, itk::Mesh< unsigned short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS2PSUS2', True, 'itk::Image< unsigned short,2 >, itk::PointSet< unsigned short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS2MF2', True, 'itk::Image< unsigned short,2 >, itk::Mesh< float,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS2PSF2', True, 'itk::Image< unsigned short,2 >, itk::PointSet< float,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS2MD2', True, 'itk::Image< unsigned short,2 >, itk::Mesh< double,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS2PSD2', True, 'itk::Image< unsigned short,2 >, itk::PointSet< double,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF2MSS2', True, 'itk::Image< float,2 >, itk::Mesh< signed short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF2PSSS2', True, 'itk::Image< float,2 >, itk::PointSet< signed short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF2MUC2', True, 'itk::Image< float,2 >, itk::Mesh< unsigned char,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF2PSUC2', True, 'itk::Image< float,2 >, itk::PointSet< unsigned char,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF2MUS2', True, 'itk::Image< float,2 >, itk::Mesh< unsigned short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF2PSUS2', True, 'itk::Image< float,2 >, itk::PointSet< unsigned short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF2MF2', True, 'itk::Image< float,2 >, itk::Mesh< float,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF2PSF2', True, 'itk::Image< float,2 >, itk::PointSet< float,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF2MD2', True, 'itk::Image< float,2 >, itk::Mesh< double,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF2PSD2', True, 'itk::Image< float,2 >, itk::PointSet< double,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID2MSS2', True, 'itk::Image< double,2 >, itk::Mesh< signed short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID2PSSS2', True, 'itk::Image< double,2 >, itk::PointSet< signed short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID2MUC2', True, 'itk::Image< double,2 >, itk::Mesh< unsigned char,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID2PSUC2', True, 'itk::Image< double,2 >, itk::PointSet< unsigned char,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID2MUS2', True, 'itk::Image< double,2 >, itk::Mesh< unsigned short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID2PSUS2', True, 'itk::Image< double,2 >, itk::PointSet< unsigned short,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID2MF2', True, 'itk::Image< double,2 >, itk::Mesh< float,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID2PSF2', True, 'itk::Image< double,2 >, itk::PointSet< float,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID2MD2', True, 'itk::Image< double,2 >, itk::Mesh< double,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID2PSD2', True, 'itk::Image< double,2 >, itk::PointSet< double,2 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS3MSS3', True, 'itk::Image< signed short,3 >, itk::Mesh< signed short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS3PSSS3', True, 'itk::Image< signed short,3 >, itk::PointSet< signed short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS3MUC3', True, 'itk::Image< signed short,3 >, itk::Mesh< unsigned char,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS3PSUC3', True, 'itk::Image< signed short,3 >, itk::PointSet< unsigned char,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS3MUS3', True, 'itk::Image< signed short,3 >, itk::Mesh< unsigned short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS3PSUS3', True, 'itk::Image< signed short,3 >, itk::PointSet< unsigned short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS3MF3', True, 'itk::Image< signed short,3 >, itk::Mesh< float,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS3PSF3', True, 'itk::Image< signed short,3 >, itk::PointSet< float,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS3MD3', True, 'itk::Image< signed short,3 >, itk::Mesh< double,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS3PSD3', True, 'itk::Image< signed short,3 >, itk::PointSet< double,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC3MSS3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< signed short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC3PSSS3', True, 'itk::Image< unsigned char,3 >, itk::PointSet< signed short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC3MUC3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< unsigned char,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC3PSUC3', True, 'itk::Image< unsigned char,3 >, itk::PointSet< unsigned char,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC3MUS3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< unsigned short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC3PSUS3', True, 'itk::Image< unsigned char,3 >, itk::PointSet< unsigned short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC3MF3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< float,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC3PSF3', True, 'itk::Image< unsigned char,3 >, itk::PointSet< float,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC3MD3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< double,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC3PSD3', True, 'itk::Image< unsigned char,3 >, itk::PointSet< double,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS3MSS3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< signed short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS3PSSS3', True, 'itk::Image< unsigned short,3 >, itk::PointSet< signed short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS3MUC3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< unsigned char,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS3PSUC3', True, 'itk::Image< unsigned short,3 >, itk::PointSet< unsigned char,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS3MUS3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< unsigned short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS3PSUS3', True, 'itk::Image< unsigned short,3 >, itk::PointSet< unsigned short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS3MF3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< float,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS3PSF3', True, 'itk::Image< unsigned short,3 >, itk::PointSet< float,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS3MD3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< double,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS3PSD3', True, 'itk::Image< unsigned short,3 >, itk::PointSet< double,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF3MSS3', True, 'itk::Image< float,3 >, itk::Mesh< signed short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF3PSSS3', True, 'itk::Image< float,3 >, itk::PointSet< signed short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF3MUC3', True, 'itk::Image< float,3 >, itk::Mesh< unsigned char,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF3PSUC3', True, 'itk::Image< float,3 >, itk::PointSet< unsigned char,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF3MUS3', True, 'itk::Image< float,3 >, itk::Mesh< unsigned short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF3PSUS3', True, 'itk::Image< float,3 >, itk::PointSet< unsigned short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF3MF3', True, 'itk::Image< float,3 >, itk::Mesh< float,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF3PSF3', True, 'itk::Image< float,3 >, itk::PointSet< float,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF3MD3', True, 'itk::Image< float,3 >, itk::Mesh< double,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF3PSD3', True, 'itk::Image< float,3 >, itk::PointSet< double,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID3MSS3', True, 'itk::Image< double,3 >, itk::Mesh< signed short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID3PSSS3', True, 'itk::Image< double,3 >, itk::PointSet< signed short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID3MUC3', True, 'itk::Image< double,3 >, itk::Mesh< unsigned char,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID3PSUC3', True, 'itk::Image< double,3 >, itk::PointSet< unsigned char,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID3MUS3', True, 'itk::Image< double,3 >, itk::Mesh< unsigned short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID3PSUS3', True, 'itk::Image< double,3 >, itk::PointSet< unsigned short,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID3MF3', True, 'itk::Image< double,3 >, itk::Mesh< float,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID3PSF3', True, 'itk::Image< double,3 >, itk::PointSet< float,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID3MD3', True, 'itk::Image< double,3 >, itk::Mesh< double,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID3PSD3', True, 'itk::Image< double,3 >, itk::PointSet< double,3 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS4MSS4', True, 'itk::Image< signed short,4 >, itk::Mesh< signed short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS4PSSS4', True, 'itk::Image< signed short,4 >, itk::PointSet< signed short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS4MUC4', True, 'itk::Image< signed short,4 >, itk::Mesh< unsigned char,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS4PSUC4', True, 'itk::Image< signed short,4 >, itk::PointSet< unsigned char,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS4MUS4', True, 'itk::Image< signed short,4 >, itk::Mesh< unsigned short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS4PSUS4', True, 'itk::Image< signed short,4 >, itk::PointSet< unsigned short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS4MF4', True, 'itk::Image< signed short,4 >, itk::Mesh< float,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS4PSF4', True, 'itk::Image< signed short,4 >, itk::PointSet< float,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS4MD4', True, 'itk::Image< signed short,4 >, itk::Mesh< double,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterISS4PSD4', True, 'itk::Image< signed short,4 >, itk::PointSet< double,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC4MSS4', True, 'itk::Image< unsigned char,4 >, itk::Mesh< signed short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC4PSSS4', True, 'itk::Image< unsigned char,4 >, itk::PointSet< signed short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC4MUC4', True, 'itk::Image< unsigned char,4 >, itk::Mesh< unsigned char,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC4PSUC4', True, 'itk::Image< unsigned char,4 >, itk::PointSet< unsigned char,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC4MUS4', True, 'itk::Image< unsigned char,4 >, itk::Mesh< unsigned short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC4PSUS4', True, 'itk::Image< unsigned char,4 >, itk::PointSet< unsigned short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC4MF4', True, 'itk::Image< unsigned char,4 >, itk::Mesh< float,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC4PSF4', True, 'itk::Image< unsigned char,4 >, itk::PointSet< float,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC4MD4', True, 'itk::Image< unsigned char,4 >, itk::Mesh< double,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC4PSD4', True, 'itk::Image< unsigned char,4 >, itk::PointSet< double,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS4MSS4', True, 'itk::Image< unsigned short,4 >, itk::Mesh< signed short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS4PSSS4', True, 'itk::Image< unsigned short,4 >, itk::PointSet< signed short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS4MUC4', True, 'itk::Image< unsigned short,4 >, itk::Mesh< unsigned char,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS4PSUC4', True, 'itk::Image< unsigned short,4 >, itk::PointSet< unsigned char,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS4MUS4', True, 'itk::Image< unsigned short,4 >, itk::Mesh< unsigned short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS4PSUS4', True, 'itk::Image< unsigned short,4 >, itk::PointSet< unsigned short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS4MF4', True, 'itk::Image< unsigned short,4 >, itk::Mesh< float,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS4PSF4', True, 'itk::Image< unsigned short,4 >, itk::PointSet< float,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS4MD4', True, 'itk::Image< unsigned short,4 >, itk::Mesh< double,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS4PSD4', True, 'itk::Image< unsigned short,4 >, itk::PointSet< double,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF4MSS4', True, 'itk::Image< float,4 >, itk::Mesh< signed short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF4PSSS4', True, 'itk::Image< float,4 >, itk::PointSet< signed short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF4MUC4', True, 'itk::Image< float,4 >, itk::Mesh< unsigned char,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF4PSUC4', True, 'itk::Image< float,4 >, itk::PointSet< unsigned char,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF4MUS4', True, 'itk::Image< float,4 >, itk::Mesh< unsigned short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF4PSUS4', True, 'itk::Image< float,4 >, itk::PointSet< unsigned short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF4MF4', True, 'itk::Image< float,4 >, itk::Mesh< float,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF4PSF4', True, 'itk::Image< float,4 >, itk::PointSet< float,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF4MD4', True, 'itk::Image< float,4 >, itk::Mesh< double,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIF4PSD4', True, 'itk::Image< float,4 >, itk::PointSet< double,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID4MSS4', True, 'itk::Image< double,4 >, itk::Mesh< signed short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID4PSSS4', True, 'itk::Image< double,4 >, itk::PointSet< signed short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID4MUC4', True, 'itk::Image< double,4 >, itk::Mesh< unsigned char,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID4PSUC4', True, 'itk::Image< double,4 >, itk::PointSet< unsigned char,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID4MUS4', True, 'itk::Image< double,4 >, itk::Mesh< unsigned short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID4PSUS4', True, 'itk::Image< double,4 >, itk::PointSet< unsigned short,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID4MF4', True, 'itk::Image< double,4 >, itk::Mesh< float,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID4PSF4', True, 'itk::Image< double,4 >, itk::PointSet< float,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID4MD4', True, 'itk::Image< double,4 >, itk::Mesh< double,4 >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterID4PSD4', True, 'itk::Image< double,4 >, itk::PointSet< double,4 >'),
  ('MeshToMeshFilter', 'itk::MeshToMeshFilter', 'itkMeshToMeshFilterMSS2MSS2', True, 'itk::Mesh< signed short,2 >, itk::Mesh< signed short,2 >'),
  ('MeshToMeshFilter', 'itk::MeshToMeshFilter', 'itkMeshToMeshFilterMUC2MUC2', True, 'itk::Mesh< unsigned char,2 >, itk::Mesh< unsigned char,2 >'),
  ('MeshToMeshFilter', 'itk::MeshToMeshFilter', 'itkMeshToMeshFilterMUS2MUS2', True, 'itk::Mesh< unsigned short,2 >, itk::Mesh< unsigned short,2 >'),
  ('MeshToMeshFilter', 'itk::MeshToMeshFilter', 'itkMeshToMeshFilterMF2MF2', True, 'itk::Mesh< float,2 >, itk::Mesh< float,2 >'),
  ('MeshToMeshFilter', 'itk::MeshToMeshFilter', 'itkMeshToMeshFilterMD2MD2', True, 'itk::Mesh< double,2 >, itk::Mesh< double,2 >'),
  ('MeshToMeshFilter', 'itk::MeshToMeshFilter', 'itkMeshToMeshFilterMSS3MSS3', True, 'itk::Mesh< signed short,3 >, itk::Mesh< signed short,3 >'),
  ('MeshToMeshFilter', 'itk::MeshToMeshFilter', 'itkMeshToMeshFilterMUC3MUC3', True, 'itk::Mesh< unsigned char,3 >, itk::Mesh< unsigned char,3 >'),
  ('MeshToMeshFilter', 'itk::MeshToMeshFilter', 'itkMeshToMeshFilterMUS3MUS3', True, 'itk::Mesh< unsigned short,3 >, itk::Mesh< unsigned short,3 >'),
  ('MeshToMeshFilter', 'itk::MeshToMeshFilter', 'itkMeshToMeshFilterMF3MF3', True, 'itk::Mesh< float,3 >, itk::Mesh< float,3 >'),
  ('MeshToMeshFilter', 'itk::MeshToMeshFilter', 'itkMeshToMeshFilterMD3MD3', True, 'itk::Mesh< double,3 >, itk::Mesh< double,3 >'),
  ('MeshToMeshFilter', 'itk::MeshToMeshFilter', 'itkMeshToMeshFilterMSS4MSS4', True, 'itk::Mesh< signed short,4 >, itk::Mesh< signed short,4 >'),
  ('MeshToMeshFilter', 'itk::MeshToMeshFilter', 'itkMeshToMeshFilterMUC4MUC4', True, 'itk::Mesh< unsigned char,4 >, itk::Mesh< unsigned char,4 >'),
  ('MeshToMeshFilter', 'itk::MeshToMeshFilter', 'itkMeshToMeshFilterMUS4MUS4', True, 'itk::Mesh< unsigned short,4 >, itk::Mesh< unsigned short,4 >'),
  ('MeshToMeshFilter', 'itk::MeshToMeshFilter', 'itkMeshToMeshFilterMF4MF4', True, 'itk::Mesh< float,4 >, itk::Mesh< float,4 >'),
  ('MeshToMeshFilter', 'itk::MeshToMeshFilter', 'itkMeshToMeshFilterMD4MD4', True, 'itk::Mesh< double,4 >, itk::Mesh< double,4 >'),
  ('VTKPolyDataReader', 'itk::VTKPolyDataReader', 'itkVTKPolyDataReaderMF2', True, 'itk::Mesh< float,2 >'),
  ('VTKPolyDataReader', 'itk::VTKPolyDataReader', 'itkVTKPolyDataReaderMD2', True, 'itk::Mesh< double,2 >'),
  ('VTKPolyDataReader', 'itk::VTKPolyDataReader', 'itkVTKPolyDataReaderMF3', True, 'itk::Mesh< float,3 >'),
  ('VTKPolyDataReader', 'itk::VTKPolyDataReader', 'itkVTKPolyDataReaderMD3', True, 'itk::Mesh< double,3 >'),
  ('VTKPolyDataReader', 'itk::VTKPolyDataReader', 'itkVTKPolyDataReaderMF4', True, 'itk::Mesh< float,4 >'),
  ('VTKPolyDataReader', 'itk::VTKPolyDataReader', 'itkVTKPolyDataReaderMD4', True, 'itk::Mesh< double,4 >'),
  ('VTKPolyDataWriter', 'itk::VTKPolyDataWriter', 'itkVTKPolyDataWriterMF2', True, 'itk::Mesh<float,2 >'),
  ('VTKPolyDataWriter', 'itk::VTKPolyDataWriter', 'itkVTKPolyDataWriterMD2', True, 'itk::Mesh<double,2 >'),
  ('VTKPolyDataWriter', 'itk::VTKPolyDataWriter', 'itkVTKPolyDataWriterMF3', True, 'itk::Mesh<float,3 >'),
  ('VTKPolyDataWriter', 'itk::VTKPolyDataWriter', 'itkVTKPolyDataWriterMD3', True, 'itk::Mesh<double,3 >'),
  ('VTKPolyDataWriter', 'itk::VTKPolyDataWriter', 'itkVTKPolyDataWriterMF4', True, 'itk::Mesh<float,4 >'),
  ('VTKPolyDataWriter', 'itk::VTKPolyDataWriter', 'itkVTKPolyDataWriterMD4', True, 'itk::Mesh<double,4 >'),
  ('BinaryMask3DMeshSource', 'itk::BinaryMask3DMeshSource', 'itkBinaryMask3DMeshSourceISS3MSS3', True, 'itk::Image< signed short,3 >, itk::Mesh< signed short,3 >'),
  ('BinaryMask3DMeshSource', 'itk::BinaryMask3DMeshSource', 'itkBinaryMask3DMeshSourceISS3MUC3', True, 'itk::Image< signed short,3 >, itk::Mesh< unsigned char,3 >'),
  ('BinaryMask3DMeshSource', 'itk::BinaryMask3DMeshSource', 'itkBinaryMask3DMeshSourceISS3MUS3', True, 'itk::Image< signed short,3 >, itk::Mesh< unsigned short,3 >'),
  ('BinaryMask3DMeshSource', 'itk::BinaryMask3DMeshSource', 'itkBinaryMask3DMeshSourceISS3MF3', True, 'itk::Image< signed short,3 >, itk::Mesh< float,3 >'),
  ('BinaryMask3DMeshSource', 'itk::BinaryMask3DMeshSource', 'itkBinaryMask3DMeshSourceISS3MD3', True, 'itk::Image< signed short,3 >, itk::Mesh< double,3 >'),
  ('BinaryMask3DMeshSource', 'itk::BinaryMask3DMeshSource', 'itkBinaryMask3DMeshSourceIUC3MSS3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< signed short,3 >'),
  ('BinaryMask3DMeshSource', 'itk::BinaryMask3DMeshSource', 'itkBinaryMask3DMeshSourceIUC3MUC3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< unsigned char,3 >'),
  ('BinaryMask3DMeshSource', 'itk::BinaryMask3DMeshSource', 'itkBinaryMask3DMeshSourceIUC3MUS3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< unsigned short,3 >'),
  ('BinaryMask3DMeshSource', 'itk::BinaryMask3DMeshSource', 'itkBinaryMask3DMeshSourceIUC3MF3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< float,3 >'),
  ('BinaryMask3DMeshSource', 'itk::BinaryMask3DMeshSource', 'itkBinaryMask3DMeshSourceIUC3MD3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< double,3 >'),
  ('BinaryMask3DMeshSource', 'itk::BinaryMask3DMeshSource', 'itkBinaryMask3DMeshSourceIUS3MSS3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< signed short,3 >'),
  ('BinaryMask3DMeshSource', 'itk::BinaryMask3DMeshSource', 'itkBinaryMask3DMeshSourceIUS3MUC3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< unsigned char,3 >'),
  ('BinaryMask3DMeshSource', 'itk::BinaryMask3DMeshSource', 'itkBinaryMask3DMeshSourceIUS3MUS3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< unsigned short,3 >'),
  ('BinaryMask3DMeshSource', 'itk::BinaryMask3DMeshSource', 'itkBinaryMask3DMeshSourceIUS3MF3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< float,3 >'),
  ('BinaryMask3DMeshSource', 'itk::BinaryMask3DMeshSource', 'itkBinaryMask3DMeshSourceIUS3MD3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< double,3 >'),
  ('ConnectedRegionsMeshFilter', 'itk::ConnectedRegionsMeshFilter', 'itkConnectedRegionsMeshFilterMF2MF2', True, 'itk::Mesh< float,2 >, itk::Mesh< float,2 >'),
  ('ConnectedRegionsMeshFilter', 'itk::ConnectedRegionsMeshFilter', 'itkConnectedRegionsMeshFilterMD2MD2', True, 'itk::Mesh< double,2 >, itk::Mesh< double,2 >'),
  ('ConnectedRegionsMeshFilter', 'itk::ConnectedRegionsMeshFilter', 'itkConnectedRegionsMeshFilterMF3MF3', True, 'itk::Mesh< float,3 >, itk::Mesh< float,3 >'),
  ('ConnectedRegionsMeshFilter', 'itk::ConnectedRegionsMeshFilter', 'itkConnectedRegionsMeshFilterMD3MD3', True, 'itk::Mesh< double,3 >, itk::Mesh< double,3 >'),
  ('ConnectedRegionsMeshFilter', 'itk::ConnectedRegionsMeshFilter', 'itkConnectedRegionsMeshFilterMF4MF4', True, 'itk::Mesh< float,4 >, itk::Mesh< float,4 >'),
  ('ConnectedRegionsMeshFilter', 'itk::ConnectedRegionsMeshFilter', 'itkConnectedRegionsMeshFilterMD4MD4', True, 'itk::Mesh< double,4 >, itk::Mesh< double,4 >'),
  ('RegularSphereMeshSource', 'itk::RegularSphereMeshSource', 'itkRegularSphereMeshSourceMF2', True, 'itk::Mesh< float,2 >'),
  ('RegularSphereMeshSource', 'itk::RegularSphereMeshSource', 'itkRegularSphereMeshSourceMD2', True, 'itk::Mesh< double,2 >'),
  ('RegularSphereMeshSource', 'itk::RegularSphereMeshSource', 'itkRegularSphereMeshSourceMF3', True, 'itk::Mesh< float,3 >'),
  ('RegularSphereMeshSource', 'itk::RegularSphereMeshSource', 'itkRegularSphereMeshSourceMD3', True, 'itk::Mesh< double,3 >'),
  ('RegularSphereMeshSource', 'itk::RegularSphereMeshSource', 'itkRegularSphereMeshSourceMF4', True, 'itk::Mesh< float,4 >'),
  ('RegularSphereMeshSource', 'itk::RegularSphereMeshSource', 'itkRegularSphereMeshSourceMD4', True, 'itk::Mesh< double,4 >'),
  ('SphereMeshSource', 'itk::SphereMeshSource', 'itkSphereMeshSourceMF2', True, 'itk::Mesh< float,2 >'),
  ('SphereMeshSource', 'itk::SphereMeshSource', 'itkSphereMeshSourceMD2', True, 'itk::Mesh< double,2 >'),
  ('SphereMeshSource', 'itk::SphereMeshSource', 'itkSphereMeshSourceMF3', True, 'itk::Mesh< float,3 >'),
  ('SphereMeshSource', 'itk::SphereMeshSource', 'itkSphereMeshSourceMD3', True, 'itk::Mesh< double,3 >'),
  ('SphereMeshSource', 'itk::SphereMeshSource', 'itkSphereMeshSourceMF4', True, 'itk::Mesh< float,4 >'),
  ('SphereMeshSource', 'itk::SphereMeshSource', 'itkSphereMeshSourceMD4', True, 'itk::Mesh< double,4 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMSS2MSS2TD22', True, 'itk::Mesh< signed short,2 >, itk::Mesh< signed short,2 >, itk::Transform< double, 2, 2 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMSS2MSS2TF22', True, 'itk::Mesh< signed short,2 >, itk::Mesh< signed short,2 >, itk::Transform< float, 2, 2 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMUC2MUC2TD22', True, 'itk::Mesh< unsigned char,2 >, itk::Mesh< unsigned char,2 >, itk::Transform< double, 2, 2 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMUC2MUC2TF22', True, 'itk::Mesh< unsigned char,2 >, itk::Mesh< unsigned char,2 >, itk::Transform< float, 2, 2 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMUS2MUS2TD22', True, 'itk::Mesh< unsigned short,2 >, itk::Mesh< unsigned short,2 >, itk::Transform< double, 2, 2 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMUS2MUS2TF22', True, 'itk::Mesh< unsigned short,2 >, itk::Mesh< unsigned short,2 >, itk::Transform< float, 2, 2 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMF2MF2TD22', True, 'itk::Mesh< float,2 >, itk::Mesh< float,2 >, itk::Transform< double, 2, 2 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMF2MF2TF22', True, 'itk::Mesh< float,2 >, itk::Mesh< float,2 >, itk::Transform< float, 2, 2 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMD2MD2TD22', True, 'itk::Mesh< double,2 >, itk::Mesh< double,2 >, itk::Transform< double, 2, 2 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMD2MD2TF22', True, 'itk::Mesh< double,2 >, itk::Mesh< double,2 >, itk::Transform< float, 2, 2 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMSS3MSS3TD33', True, 'itk::Mesh< signed short,3 >, itk::Mesh< signed short,3 >, itk::Transform< double, 3, 3 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMSS3MSS3TF33', True, 'itk::Mesh< signed short,3 >, itk::Mesh< signed short,3 >, itk::Transform< float, 3, 3 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMUC3MUC3TD33', True, 'itk::Mesh< unsigned char,3 >, itk::Mesh< unsigned char,3 >, itk::Transform< double, 3, 3 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMUC3MUC3TF33', True, 'itk::Mesh< unsigned char,3 >, itk::Mesh< unsigned char,3 >, itk::Transform< float, 3, 3 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMUS3MUS3TD33', True, 'itk::Mesh< unsigned short,3 >, itk::Mesh< unsigned short,3 >, itk::Transform< double, 3, 3 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMUS3MUS3TF33', True, 'itk::Mesh< unsigned short,3 >, itk::Mesh< unsigned short,3 >, itk::Transform< float, 3, 3 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMF3MF3TD33', True, 'itk::Mesh< float,3 >, itk::Mesh< float,3 >, itk::Transform< double, 3, 3 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMF3MF3TF33', True, 'itk::Mesh< float,3 >, itk::Mesh< float,3 >, itk::Transform< float, 3, 3 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMD3MD3TD33', True, 'itk::Mesh< double,3 >, itk::Mesh< double,3 >, itk::Transform< double, 3, 3 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMD3MD3TF33', True, 'itk::Mesh< double,3 >, itk::Mesh< double,3 >, itk::Transform< float, 3, 3 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMSS4MSS4TD44', True, 'itk::Mesh< signed short,4 >, itk::Mesh< signed short,4 >, itk::Transform< double, 4, 4 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMSS4MSS4TF44', True, 'itk::Mesh< signed short,4 >, itk::Mesh< signed short,4 >, itk::Transform< float, 4, 4 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMUC4MUC4TD44', True, 'itk::Mesh< unsigned char,4 >, itk::Mesh< unsigned char,4 >, itk::Transform< double, 4, 4 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMUC4MUC4TF44', True, 'itk::Mesh< unsigned char,4 >, itk::Mesh< unsigned char,4 >, itk::Transform< float, 4, 4 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMUS4MUS4TD44', True, 'itk::Mesh< unsigned short,4 >, itk::Mesh< unsigned short,4 >, itk::Transform< double, 4, 4 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMUS4MUS4TF44', True, 'itk::Mesh< unsigned short,4 >, itk::Mesh< unsigned short,4 >, itk::Transform< float, 4, 4 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMF4MF4TD44', True, 'itk::Mesh< float,4 >, itk::Mesh< float,4 >, itk::Transform< double, 4, 4 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMF4MF4TF44', True, 'itk::Mesh< float,4 >, itk::Mesh< float,4 >, itk::Transform< float, 4, 4 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMD4MD4TD44', True, 'itk::Mesh< double,4 >, itk::Mesh< double,4 >, itk::Transform< double, 4, 4 >'),
  ('TransformMeshFilter', 'itk::TransformMeshFilter', 'itkTransformMeshFilterMD4MD4TF44', True, 'itk::Mesh< double,4 >, itk::Mesh< double,4 >, itk::Transform< float, 4, 4 >'),
  ('TriangleMeshCurvatureCalculatorEnums', 'itk::TriangleMeshCurvatureCalculatorEnums', 'itkTriangleMeshCurvatureCalculatorEnums', False),
  ('TriangleMeshCurvatureCalculator', 'itk::TriangleMeshCurvatureCalculator', 'itkTriangleMeshCurvatureCalculatorMF3', True, 'itk::Mesh< float, 3 >'),
  ('TriangleMeshCurvatureCalculator', 'itk::TriangleMeshCurvatureCalculator', 'itkTriangleMeshCurvatureCalculatorMD3', True, 'itk::Mesh< double, 3 >'),
  ('Point1D', 'itk::Point1D', 'itkPoint1D', False),
  ('TriangleMeshToBinaryImageFilter', 'itk::TriangleMeshToBinaryImageFilter', 'itkTriangleMeshToBinaryImageFilterMSS3ISS3', True, 'itk::Mesh< signed short,3 >, itk::Image< signed short,3 > '),
  ('TriangleMeshToBinaryImageFilter', 'itk::TriangleMeshToBinaryImageFilter', 'itkTriangleMeshToBinaryImageFilterMUC3IUC3', True, 'itk::Mesh< unsigned char,3 >, itk::Image< unsigned char,3 > '),
  ('TriangleMeshToBinaryImageFilter', 'itk::TriangleMeshToBinaryImageFilter', 'itkTriangleMeshToBinaryImageFilterMUS3IUS3', True, 'itk::Mesh< unsigned short,3 >, itk::Image< unsigned short,3 > '),
  ('TriangleMeshToBinaryImageFilter', 'itk::TriangleMeshToBinaryImageFilter', 'itkTriangleMeshToBinaryImageFilterMF3IF3', True, 'itk::Mesh< float,3 >, itk::Image< float,3 > '),
  ('TriangleMeshToBinaryImageFilter', 'itk::TriangleMeshToBinaryImageFilter', 'itkTriangleMeshToBinaryImageFilterMD3ID3', True, 'itk::Mesh< double,3 >, itk::Image< double,3 > '),
)
factories = ()
