BROADCAST_TEXT = 0x00
DIRECT_TEXT = 0x01
PROD = 0x02
GET_DATA = 0x03
KEY_OFFER = 0x04
KEY_SLICE = 0x05
BROADCAST_TEXT_M = 0x06
DIRECT_TEXT_M = 0x07
IGNORE = 0xFF
ADDRESS_CAST = 0xFE

COMMAND_LABELS = {
    BROADCAST_TEXT: "BROADCAST_TEXT",
    BROADCAST_TEXT_M: "BROADCAST_TEXT_M",
    DIRECT_TEXT: "DIRECT_TEXT",
    DIRECT_TEXT_M: "DIRECT_TEXT_M",
    GET_DATA: "GETDATA",
    KEY_OFFER: "KEY_OFFER",
    KEY_SLICE: "KEY_SLICE",
    PROD: "PROD",
    IGNORE: "IGNORE",
}
