key = """-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIDsVaXxAeTEqnC3V2BjBZepjfx3lG0UNiBb6IGs1nqo5oAoGCCqGSM49
AwEHoUQDQgAExzhLL99T9DDmDW8my+dVvremZ3lYo9l+D6sBkcaD+KxYkd+eHhCp
DBfIKnDILG7XNOpl3PBa4AOC4BkGkrqq0w==
-----END EC PRIVATE KEY-----
"""

cert = """-----BEGIN CERTIFICATE-----
MIIB6TCCAY8CFAIPufXDoRbmCDs53mUkr/QCZ1wnMAoGCCqGSM49BAMCMHcxCzAJ
BgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UE
CgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25hbCBVbml0MRQw
EgYDVQQDDAtDb21tb24gTmFtZTAeFw0yNTA5MjYwOTE4MzhaFw0zNTA5MjQwOTE4
MzhaMHcxCzAJBgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0
eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25h
bCBVbml0MRQwEgYDVQQDDAtDb21tb24gTmFtZTBZMBMGByqGSM49AgEGCCqGSM49
AwEHA0IABMc4Sy/fU/Qw5g1vJsvnVb63pmd5WKPZfg+rAZHGg/isWJHfnh4QqQwX
yCpwyCxu1zTqZdzwWuADguAZBpK6qtMwCgYIKoZIzj0EAwIDSAAwRQIhAMTUyNcu
iVbprDZNcnP58QoqQd3tIyod4eusUqIYjnIUAiAQsnjz0Ffer7IcrXG6pfscfi5O
JbGxeRO0TFgSybUMBg==
-----END CERTIFICATE-----
"""