# Generated by Django 5.2.6 on 2025-09-22 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(help_text='URL to check')),
                ('timeout', models.IntegerField(default=5, help_text='Timeout in seconds')),
                ('expected_status_code', models.IntegerField(default=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Health Check',
                'verbose_name_plural': 'Health Checks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheckAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alert_type', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook'), ('slack', 'Slack'), ('sms', 'SMS')], max_length=20)),
                ('recipients', models.JSONField(default=list, help_text='List of recipients (emails, webhook URLs, etc.)')),
                ('conditions', models.JSONField(default=dict, help_text="Alert conditions (e.g., {'status': 'unhealthy', 'consecutive_failures': 3})")),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Health Check Alert',
                'verbose_name_plural': 'Health Check Alerts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheckMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('metric_unit', models.CharField(default='ms', max_length=20)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Health Check Metric',
                'verbose_name_plural': 'Health Check Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_name', 'timestamp'], name='django_heal_metric__c9c8a5_idx'), models.Index(fields=['timestamp'], name='django_heal_timesta_46c096_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('unhealthy', 'Unhealthy'), ('warning', 'Warning'), ('unknown', 'Unknown')], max_length=20)),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('health_check', models.ForeignKey(blank=True, help_text='Associated health check (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dj_health_checker.healthcheck')),
            ],
            options={
                'verbose_name': 'Health Check Result',
                'verbose_name_plural': 'Health Check Results',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='django_heal_timesta_cf0932_idx'), models.Index(fields=['status'], name='django_heal_status_d6b8b0_idx'), models.Index(fields=['health_check', 'timestamp'], name='django_heal_health__58650c_idx')],
            },
        ),
    ]
