# -*- coding: utf-8 -*-
import os

MOD_NAME = "[MOD_NAME]"
MOD_DIR_NAME = "[MOD_DIR_NAME]"
CLIENT_SYSTEM_NAME = "[CLIENT_SYSTEM_NAME]"
SERVER_SYSTEM_NAME = "[SERVER_SYSTEM_NAME]"
BEHAVIOR_PACK_HEADER_UUID = "[BEHAVIOR_PACK_HEADER_UUID]"
BEHAVIOR_PACK_MODULE_UUID = "[BEHAVIOR_PACK_MODULE_UUID]"
RESOURCE_PACK_HEADER_UUID = "[RESOURCE_PACK_HEADER_UUID]"
RESOURCE_PACK_MODULE_UUID = "[RESOURCE_PACK_MODULE_UUID]"
BEHAVIOR_PACK_FOLDER = "[BEHAVIOR_PACK_FOLDER]"
RESOURCE_PACK_FOLDER = "[RESOURCE_PACK_FOLDER]"
SCRIPTS_FOLDER = "[SCRIPTS_FOLDER]"

CLIENT_SYSTEM_FILE_PATH = "ClientSystem.txt"
SERVER_SYSTEM_FILE_PATH = "ServerSystem.txt"

TEMPLATE_DIR_NAME = "scripts"
PLUGINS_DIR_NAME = "plugins"
FRAMEWORK_TEMPLATE_DIR_NAME = "modsdkspring"
FRAMEWORK_PLUGIN_DIR_NAME = "MODSDKSpring"
