# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.


import collections

from sys import version_info as _version_info
if _version_info < (3, 7, 0):
    raise RuntimeError("Python 3.7 or later required")

from . import _ITKCommonPython


from . import _ITKImageLabelPython



from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _itkBinaryContourImageFilterPython
else:
    import _itkBinaryContourImageFilterPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


if _swig_python_version_info[0:2] >= (3, 3):
    import collections.abc
else:
    import collections

import itk.itkImageRegionPython
import itk.itkSizePython
import itk.pyBasePython
import itk.ITKCommonBasePython
import itk.itkMatrixPython
import itk.itkPointPython
import itk.itkVectorPython
import itk.vnl_vectorPython
import itk.stdcomplexPython
import itk.vnl_matrixPython
import itk.itkFixedArrayPython
import itk.vnl_vector_refPython
import itk.vnl_matrix_fixedPython
import itk.itkCovariantVectorPython
import itk.itkIndexPython
import itk.itkOffsetPython
import itk.itkInPlaceImageFilterAPython
import itk.itkImageToImageFilterBPython
import itk.itkImageSourcePython
import itk.itkImageSourceCommonPython
import itk.itkPhasedArray3DSpecialCoordinatesImagePython
import itk.itkImagePython
import itk.itkRGBAPixelPython
import itk.itkRGBPixelPython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkVectorImagePython
import itk.itkVariableLengthVectorPython
import itk.itkImageToImageFilterCommonPython
import itk.itkImageToImageFilterAPython
import itk.itkScanlineFilterCommonPython

def itkBinaryContourImageFilterID2ID2_New():
    return itkBinaryContourImageFilterID2ID2.New()

class itkBinaryContourImageFilterID2ID2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterID2ID2):
    r"""Proxy of C++ itkBinaryContourImageFilterID2ID2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkBinaryContourImageFilterID2ID2_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID2ID2___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkBinaryContourImageFilterID2ID2_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID2ID2_Clone(self)

    def SetFullyConnected(self, _arg):
        r"""
        SetFullyConnected(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID2ID2_SetFullyConnected(self, _arg)

    def GetFullyConnected(self):
        r"""GetFullyConnected(self) -> bool const &"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID2ID2_GetFullyConnected(self)

    def FullyConnectedOn(self):
        r"""FullyConnectedOn(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID2ID2_FullyConnectedOn(self)

    def FullyConnectedOff(self):
        r"""FullyConnectedOff(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID2ID2_FullyConnectedOff(self)

    def SetBackgroundValue(self, _arg):
        r"""
        SetBackgroundValue(self, _arg)

        Parameters
        ----------
        _arg: double

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID2ID2_SetBackgroundValue(self, _arg)

    def GetBackgroundValue(self):
        r"""GetBackgroundValue(self) -> double"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID2ID2_GetBackgroundValue(self)

    def SetForegroundValue(self, _arg):
        r"""
        SetForegroundValue(self, _arg)

        Parameters
        ----------
        _arg: double

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID2ID2_SetForegroundValue(self, _arg)

    def GetForegroundValue(self):
        r"""GetForegroundValue(self) -> double"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID2ID2_GetForegroundValue(self)
    __swig_destroy__ = _itkBinaryContourImageFilterPython.delete_itkBinaryContourImageFilterID2ID2

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkBinaryContourImageFilterID2ID2

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID2ID2_cast(obj)

    def New(*args, **kargs):
        """New() -> itkBinaryContourImageFilterID2ID2

        Create a new object of the class itkBinaryContourImageFilterID2ID2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryContourImageFilterID2ID2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryContourImageFilterID2ID2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryContourImageFilterID2ID2.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryContourImageFilterID2ID2 in _itkBinaryContourImageFilterPython:
_itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID2ID2_swigregister(itkBinaryContourImageFilterID2ID2)

def itkBinaryContourImageFilterID3ID3_New():
    return itkBinaryContourImageFilterID3ID3.New()

class itkBinaryContourImageFilterID3ID3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterID3ID3):
    r"""Proxy of C++ itkBinaryContourImageFilterID3ID3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkBinaryContourImageFilterID3ID3_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID3ID3___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkBinaryContourImageFilterID3ID3_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID3ID3_Clone(self)

    def SetFullyConnected(self, _arg):
        r"""
        SetFullyConnected(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID3ID3_SetFullyConnected(self, _arg)

    def GetFullyConnected(self):
        r"""GetFullyConnected(self) -> bool const &"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID3ID3_GetFullyConnected(self)

    def FullyConnectedOn(self):
        r"""FullyConnectedOn(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID3ID3_FullyConnectedOn(self)

    def FullyConnectedOff(self):
        r"""FullyConnectedOff(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID3ID3_FullyConnectedOff(self)

    def SetBackgroundValue(self, _arg):
        r"""
        SetBackgroundValue(self, _arg)

        Parameters
        ----------
        _arg: double

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID3ID3_SetBackgroundValue(self, _arg)

    def GetBackgroundValue(self):
        r"""GetBackgroundValue(self) -> double"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID3ID3_GetBackgroundValue(self)

    def SetForegroundValue(self, _arg):
        r"""
        SetForegroundValue(self, _arg)

        Parameters
        ----------
        _arg: double

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID3ID3_SetForegroundValue(self, _arg)

    def GetForegroundValue(self):
        r"""GetForegroundValue(self) -> double"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID3ID3_GetForegroundValue(self)
    __swig_destroy__ = _itkBinaryContourImageFilterPython.delete_itkBinaryContourImageFilterID3ID3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkBinaryContourImageFilterID3ID3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID3ID3_cast(obj)

    def New(*args, **kargs):
        """New() -> itkBinaryContourImageFilterID3ID3

        Create a new object of the class itkBinaryContourImageFilterID3ID3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryContourImageFilterID3ID3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryContourImageFilterID3ID3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryContourImageFilterID3ID3.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryContourImageFilterID3ID3 in _itkBinaryContourImageFilterPython:
_itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID3ID3_swigregister(itkBinaryContourImageFilterID3ID3)

def itkBinaryContourImageFilterID4ID4_New():
    return itkBinaryContourImageFilterID4ID4.New()

class itkBinaryContourImageFilterID4ID4(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterID4ID4):
    r"""Proxy of C++ itkBinaryContourImageFilterID4ID4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkBinaryContourImageFilterID4ID4_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID4ID4___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkBinaryContourImageFilterID4ID4_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID4ID4_Clone(self)

    def SetFullyConnected(self, _arg):
        r"""
        SetFullyConnected(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID4ID4_SetFullyConnected(self, _arg)

    def GetFullyConnected(self):
        r"""GetFullyConnected(self) -> bool const &"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID4ID4_GetFullyConnected(self)

    def FullyConnectedOn(self):
        r"""FullyConnectedOn(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID4ID4_FullyConnectedOn(self)

    def FullyConnectedOff(self):
        r"""FullyConnectedOff(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID4ID4_FullyConnectedOff(self)

    def SetBackgroundValue(self, _arg):
        r"""
        SetBackgroundValue(self, _arg)

        Parameters
        ----------
        _arg: double

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID4ID4_SetBackgroundValue(self, _arg)

    def GetBackgroundValue(self):
        r"""GetBackgroundValue(self) -> double"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID4ID4_GetBackgroundValue(self)

    def SetForegroundValue(self, _arg):
        r"""
        SetForegroundValue(self, _arg)

        Parameters
        ----------
        _arg: double

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID4ID4_SetForegroundValue(self, _arg)

    def GetForegroundValue(self):
        r"""GetForegroundValue(self) -> double"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID4ID4_GetForegroundValue(self)
    __swig_destroy__ = _itkBinaryContourImageFilterPython.delete_itkBinaryContourImageFilterID4ID4

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkBinaryContourImageFilterID4ID4

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID4ID4_cast(obj)

    def New(*args, **kargs):
        """New() -> itkBinaryContourImageFilterID4ID4

        Create a new object of the class itkBinaryContourImageFilterID4ID4 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryContourImageFilterID4ID4.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryContourImageFilterID4ID4.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryContourImageFilterID4ID4.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryContourImageFilterID4ID4 in _itkBinaryContourImageFilterPython:
_itkBinaryContourImageFilterPython.itkBinaryContourImageFilterID4ID4_swigregister(itkBinaryContourImageFilterID4ID4)

def itkBinaryContourImageFilterIF2IF2_New():
    return itkBinaryContourImageFilterIF2IF2.New()

class itkBinaryContourImageFilterIF2IF2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IF2):
    r"""Proxy of C++ itkBinaryContourImageFilterIF2IF2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkBinaryContourImageFilterIF2IF2_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF2IF2___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkBinaryContourImageFilterIF2IF2_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF2IF2_Clone(self)

    def SetFullyConnected(self, _arg):
        r"""
        SetFullyConnected(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF2IF2_SetFullyConnected(self, _arg)

    def GetFullyConnected(self):
        r"""GetFullyConnected(self) -> bool const &"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF2IF2_GetFullyConnected(self)

    def FullyConnectedOn(self):
        r"""FullyConnectedOn(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF2IF2_FullyConnectedOn(self)

    def FullyConnectedOff(self):
        r"""FullyConnectedOff(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF2IF2_FullyConnectedOff(self)

    def SetBackgroundValue(self, _arg):
        r"""
        SetBackgroundValue(self, _arg)

        Parameters
        ----------
        _arg: float

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF2IF2_SetBackgroundValue(self, _arg)

    def GetBackgroundValue(self):
        r"""GetBackgroundValue(self) -> float"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF2IF2_GetBackgroundValue(self)

    def SetForegroundValue(self, _arg):
        r"""
        SetForegroundValue(self, _arg)

        Parameters
        ----------
        _arg: float

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF2IF2_SetForegroundValue(self, _arg)

    def GetForegroundValue(self):
        r"""GetForegroundValue(self) -> float"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF2IF2_GetForegroundValue(self)
    __swig_destroy__ = _itkBinaryContourImageFilterPython.delete_itkBinaryContourImageFilterIF2IF2

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkBinaryContourImageFilterIF2IF2

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF2IF2_cast(obj)

    def New(*args, **kargs):
        """New() -> itkBinaryContourImageFilterIF2IF2

        Create a new object of the class itkBinaryContourImageFilterIF2IF2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryContourImageFilterIF2IF2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryContourImageFilterIF2IF2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryContourImageFilterIF2IF2.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryContourImageFilterIF2IF2 in _itkBinaryContourImageFilterPython:
_itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF2IF2_swigregister(itkBinaryContourImageFilterIF2IF2)

def itkBinaryContourImageFilterIF3IF3_New():
    return itkBinaryContourImageFilterIF3IF3.New()

class itkBinaryContourImageFilterIF3IF3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IF3):
    r"""Proxy of C++ itkBinaryContourImageFilterIF3IF3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkBinaryContourImageFilterIF3IF3_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF3IF3___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkBinaryContourImageFilterIF3IF3_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF3IF3_Clone(self)

    def SetFullyConnected(self, _arg):
        r"""
        SetFullyConnected(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF3IF3_SetFullyConnected(self, _arg)

    def GetFullyConnected(self):
        r"""GetFullyConnected(self) -> bool const &"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF3IF3_GetFullyConnected(self)

    def FullyConnectedOn(self):
        r"""FullyConnectedOn(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF3IF3_FullyConnectedOn(self)

    def FullyConnectedOff(self):
        r"""FullyConnectedOff(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF3IF3_FullyConnectedOff(self)

    def SetBackgroundValue(self, _arg):
        r"""
        SetBackgroundValue(self, _arg)

        Parameters
        ----------
        _arg: float

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF3IF3_SetBackgroundValue(self, _arg)

    def GetBackgroundValue(self):
        r"""GetBackgroundValue(self) -> float"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF3IF3_GetBackgroundValue(self)

    def SetForegroundValue(self, _arg):
        r"""
        SetForegroundValue(self, _arg)

        Parameters
        ----------
        _arg: float

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF3IF3_SetForegroundValue(self, _arg)

    def GetForegroundValue(self):
        r"""GetForegroundValue(self) -> float"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF3IF3_GetForegroundValue(self)
    __swig_destroy__ = _itkBinaryContourImageFilterPython.delete_itkBinaryContourImageFilterIF3IF3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkBinaryContourImageFilterIF3IF3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF3IF3_cast(obj)

    def New(*args, **kargs):
        """New() -> itkBinaryContourImageFilterIF3IF3

        Create a new object of the class itkBinaryContourImageFilterIF3IF3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryContourImageFilterIF3IF3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryContourImageFilterIF3IF3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryContourImageFilterIF3IF3.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryContourImageFilterIF3IF3 in _itkBinaryContourImageFilterPython:
_itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF3IF3_swigregister(itkBinaryContourImageFilterIF3IF3)

def itkBinaryContourImageFilterIF4IF4_New():
    return itkBinaryContourImageFilterIF4IF4.New()

class itkBinaryContourImageFilterIF4IF4(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF4IF4):
    r"""Proxy of C++ itkBinaryContourImageFilterIF4IF4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkBinaryContourImageFilterIF4IF4_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF4IF4___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkBinaryContourImageFilterIF4IF4_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF4IF4_Clone(self)

    def SetFullyConnected(self, _arg):
        r"""
        SetFullyConnected(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF4IF4_SetFullyConnected(self, _arg)

    def GetFullyConnected(self):
        r"""GetFullyConnected(self) -> bool const &"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF4IF4_GetFullyConnected(self)

    def FullyConnectedOn(self):
        r"""FullyConnectedOn(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF4IF4_FullyConnectedOn(self)

    def FullyConnectedOff(self):
        r"""FullyConnectedOff(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF4IF4_FullyConnectedOff(self)

    def SetBackgroundValue(self, _arg):
        r"""
        SetBackgroundValue(self, _arg)

        Parameters
        ----------
        _arg: float

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF4IF4_SetBackgroundValue(self, _arg)

    def GetBackgroundValue(self):
        r"""GetBackgroundValue(self) -> float"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF4IF4_GetBackgroundValue(self)

    def SetForegroundValue(self, _arg):
        r"""
        SetForegroundValue(self, _arg)

        Parameters
        ----------
        _arg: float

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF4IF4_SetForegroundValue(self, _arg)

    def GetForegroundValue(self):
        r"""GetForegroundValue(self) -> float"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF4IF4_GetForegroundValue(self)
    __swig_destroy__ = _itkBinaryContourImageFilterPython.delete_itkBinaryContourImageFilterIF4IF4

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkBinaryContourImageFilterIF4IF4

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF4IF4_cast(obj)

    def New(*args, **kargs):
        """New() -> itkBinaryContourImageFilterIF4IF4

        Create a new object of the class itkBinaryContourImageFilterIF4IF4 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryContourImageFilterIF4IF4.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryContourImageFilterIF4IF4.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryContourImageFilterIF4IF4.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryContourImageFilterIF4IF4 in _itkBinaryContourImageFilterPython:
_itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIF4IF4_swigregister(itkBinaryContourImageFilterIF4IF4)

def itkBinaryContourImageFilterISS2ISS2_New():
    return itkBinaryContourImageFilterISS2ISS2.New()

class itkBinaryContourImageFilterISS2ISS2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2ISS2):
    r"""Proxy of C++ itkBinaryContourImageFilterISS2ISS2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkBinaryContourImageFilterISS2ISS2_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS2ISS2___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkBinaryContourImageFilterISS2ISS2_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS2ISS2_Clone(self)

    def SetFullyConnected(self, _arg):
        r"""
        SetFullyConnected(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS2ISS2_SetFullyConnected(self, _arg)

    def GetFullyConnected(self):
        r"""GetFullyConnected(self) -> bool const &"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS2ISS2_GetFullyConnected(self)

    def FullyConnectedOn(self):
        r"""FullyConnectedOn(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS2ISS2_FullyConnectedOn(self)

    def FullyConnectedOff(self):
        r"""FullyConnectedOff(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS2ISS2_FullyConnectedOff(self)

    def SetBackgroundValue(self, _arg):
        r"""
        SetBackgroundValue(self, _arg)

        Parameters
        ----------
        _arg: short

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS2ISS2_SetBackgroundValue(self, _arg)

    def GetBackgroundValue(self):
        r"""GetBackgroundValue(self) -> short"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS2ISS2_GetBackgroundValue(self)

    def SetForegroundValue(self, _arg):
        r"""
        SetForegroundValue(self, _arg)

        Parameters
        ----------
        _arg: short

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS2ISS2_SetForegroundValue(self, _arg)

    def GetForegroundValue(self):
        r"""GetForegroundValue(self) -> short"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS2ISS2_GetForegroundValue(self)
    __swig_destroy__ = _itkBinaryContourImageFilterPython.delete_itkBinaryContourImageFilterISS2ISS2

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkBinaryContourImageFilterISS2ISS2

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS2ISS2_cast(obj)

    def New(*args, **kargs):
        """New() -> itkBinaryContourImageFilterISS2ISS2

        Create a new object of the class itkBinaryContourImageFilterISS2ISS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryContourImageFilterISS2ISS2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryContourImageFilterISS2ISS2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryContourImageFilterISS2ISS2.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryContourImageFilterISS2ISS2 in _itkBinaryContourImageFilterPython:
_itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS2ISS2_swigregister(itkBinaryContourImageFilterISS2ISS2)

def itkBinaryContourImageFilterISS3ISS3_New():
    return itkBinaryContourImageFilterISS3ISS3.New()

class itkBinaryContourImageFilterISS3ISS3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3ISS3):
    r"""Proxy of C++ itkBinaryContourImageFilterISS3ISS3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkBinaryContourImageFilterISS3ISS3_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS3ISS3___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkBinaryContourImageFilterISS3ISS3_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS3ISS3_Clone(self)

    def SetFullyConnected(self, _arg):
        r"""
        SetFullyConnected(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS3ISS3_SetFullyConnected(self, _arg)

    def GetFullyConnected(self):
        r"""GetFullyConnected(self) -> bool const &"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS3ISS3_GetFullyConnected(self)

    def FullyConnectedOn(self):
        r"""FullyConnectedOn(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS3ISS3_FullyConnectedOn(self)

    def FullyConnectedOff(self):
        r"""FullyConnectedOff(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS3ISS3_FullyConnectedOff(self)

    def SetBackgroundValue(self, _arg):
        r"""
        SetBackgroundValue(self, _arg)

        Parameters
        ----------
        _arg: short

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS3ISS3_SetBackgroundValue(self, _arg)

    def GetBackgroundValue(self):
        r"""GetBackgroundValue(self) -> short"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS3ISS3_GetBackgroundValue(self)

    def SetForegroundValue(self, _arg):
        r"""
        SetForegroundValue(self, _arg)

        Parameters
        ----------
        _arg: short

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS3ISS3_SetForegroundValue(self, _arg)

    def GetForegroundValue(self):
        r"""GetForegroundValue(self) -> short"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS3ISS3_GetForegroundValue(self)
    __swig_destroy__ = _itkBinaryContourImageFilterPython.delete_itkBinaryContourImageFilterISS3ISS3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkBinaryContourImageFilterISS3ISS3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS3ISS3_cast(obj)

    def New(*args, **kargs):
        """New() -> itkBinaryContourImageFilterISS3ISS3

        Create a new object of the class itkBinaryContourImageFilterISS3ISS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryContourImageFilterISS3ISS3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryContourImageFilterISS3ISS3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryContourImageFilterISS3ISS3.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryContourImageFilterISS3ISS3 in _itkBinaryContourImageFilterPython:
_itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS3ISS3_swigregister(itkBinaryContourImageFilterISS3ISS3)

def itkBinaryContourImageFilterISS4ISS4_New():
    return itkBinaryContourImageFilterISS4ISS4.New()

class itkBinaryContourImageFilterISS4ISS4(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS4ISS4):
    r"""Proxy of C++ itkBinaryContourImageFilterISS4ISS4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkBinaryContourImageFilterISS4ISS4_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS4ISS4___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkBinaryContourImageFilterISS4ISS4_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS4ISS4_Clone(self)

    def SetFullyConnected(self, _arg):
        r"""
        SetFullyConnected(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS4ISS4_SetFullyConnected(self, _arg)

    def GetFullyConnected(self):
        r"""GetFullyConnected(self) -> bool const &"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS4ISS4_GetFullyConnected(self)

    def FullyConnectedOn(self):
        r"""FullyConnectedOn(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS4ISS4_FullyConnectedOn(self)

    def FullyConnectedOff(self):
        r"""FullyConnectedOff(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS4ISS4_FullyConnectedOff(self)

    def SetBackgroundValue(self, _arg):
        r"""
        SetBackgroundValue(self, _arg)

        Parameters
        ----------
        _arg: short

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS4ISS4_SetBackgroundValue(self, _arg)

    def GetBackgroundValue(self):
        r"""GetBackgroundValue(self) -> short"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS4ISS4_GetBackgroundValue(self)

    def SetForegroundValue(self, _arg):
        r"""
        SetForegroundValue(self, _arg)

        Parameters
        ----------
        _arg: short

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS4ISS4_SetForegroundValue(self, _arg)

    def GetForegroundValue(self):
        r"""GetForegroundValue(self) -> short"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS4ISS4_GetForegroundValue(self)
    __swig_destroy__ = _itkBinaryContourImageFilterPython.delete_itkBinaryContourImageFilterISS4ISS4

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkBinaryContourImageFilterISS4ISS4

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS4ISS4_cast(obj)

    def New(*args, **kargs):
        """New() -> itkBinaryContourImageFilterISS4ISS4

        Create a new object of the class itkBinaryContourImageFilterISS4ISS4 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryContourImageFilterISS4ISS4.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryContourImageFilterISS4ISS4.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryContourImageFilterISS4ISS4.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryContourImageFilterISS4ISS4 in _itkBinaryContourImageFilterPython:
_itkBinaryContourImageFilterPython.itkBinaryContourImageFilterISS4ISS4_swigregister(itkBinaryContourImageFilterISS4ISS4)

def itkBinaryContourImageFilterIUC2IUC2_New():
    return itkBinaryContourImageFilterIUC2IUC2.New()

class itkBinaryContourImageFilterIUC2IUC2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IUC2):
    r"""Proxy of C++ itkBinaryContourImageFilterIUC2IUC2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkBinaryContourImageFilterIUC2IUC2_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC2IUC2___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkBinaryContourImageFilterIUC2IUC2_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC2IUC2_Clone(self)

    def SetFullyConnected(self, _arg):
        r"""
        SetFullyConnected(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC2IUC2_SetFullyConnected(self, _arg)

    def GetFullyConnected(self):
        r"""GetFullyConnected(self) -> bool const &"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC2IUC2_GetFullyConnected(self)

    def FullyConnectedOn(self):
        r"""FullyConnectedOn(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC2IUC2_FullyConnectedOn(self)

    def FullyConnectedOff(self):
        r"""FullyConnectedOff(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC2IUC2_FullyConnectedOff(self)

    def SetBackgroundValue(self, _arg):
        r"""
        SetBackgroundValue(self, _arg)

        Parameters
        ----------
        _arg: unsigned char

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC2IUC2_SetBackgroundValue(self, _arg)

    def GetBackgroundValue(self):
        r"""GetBackgroundValue(self) -> unsigned char"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC2IUC2_GetBackgroundValue(self)

    def SetForegroundValue(self, _arg):
        r"""
        SetForegroundValue(self, _arg)

        Parameters
        ----------
        _arg: unsigned char

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC2IUC2_SetForegroundValue(self, _arg)

    def GetForegroundValue(self):
        r"""GetForegroundValue(self) -> unsigned char"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC2IUC2_GetForegroundValue(self)
    __swig_destroy__ = _itkBinaryContourImageFilterPython.delete_itkBinaryContourImageFilterIUC2IUC2

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkBinaryContourImageFilterIUC2IUC2

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC2IUC2_cast(obj)

    def New(*args, **kargs):
        """New() -> itkBinaryContourImageFilterIUC2IUC2

        Create a new object of the class itkBinaryContourImageFilterIUC2IUC2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryContourImageFilterIUC2IUC2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryContourImageFilterIUC2IUC2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryContourImageFilterIUC2IUC2.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryContourImageFilterIUC2IUC2 in _itkBinaryContourImageFilterPython:
_itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC2IUC2_swigregister(itkBinaryContourImageFilterIUC2IUC2)

def itkBinaryContourImageFilterIUC3IUC3_New():
    return itkBinaryContourImageFilterIUC3IUC3.New()

class itkBinaryContourImageFilterIUC3IUC3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IUC3):
    r"""Proxy of C++ itkBinaryContourImageFilterIUC3IUC3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkBinaryContourImageFilterIUC3IUC3_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC3IUC3___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkBinaryContourImageFilterIUC3IUC3_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC3IUC3_Clone(self)

    def SetFullyConnected(self, _arg):
        r"""
        SetFullyConnected(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC3IUC3_SetFullyConnected(self, _arg)

    def GetFullyConnected(self):
        r"""GetFullyConnected(self) -> bool const &"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC3IUC3_GetFullyConnected(self)

    def FullyConnectedOn(self):
        r"""FullyConnectedOn(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC3IUC3_FullyConnectedOn(self)

    def FullyConnectedOff(self):
        r"""FullyConnectedOff(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC3IUC3_FullyConnectedOff(self)

    def SetBackgroundValue(self, _arg):
        r"""
        SetBackgroundValue(self, _arg)

        Parameters
        ----------
        _arg: unsigned char

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC3IUC3_SetBackgroundValue(self, _arg)

    def GetBackgroundValue(self):
        r"""GetBackgroundValue(self) -> unsigned char"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC3IUC3_GetBackgroundValue(self)

    def SetForegroundValue(self, _arg):
        r"""
        SetForegroundValue(self, _arg)

        Parameters
        ----------
        _arg: unsigned char

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC3IUC3_SetForegroundValue(self, _arg)

    def GetForegroundValue(self):
        r"""GetForegroundValue(self) -> unsigned char"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC3IUC3_GetForegroundValue(self)
    __swig_destroy__ = _itkBinaryContourImageFilterPython.delete_itkBinaryContourImageFilterIUC3IUC3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkBinaryContourImageFilterIUC3IUC3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC3IUC3_cast(obj)

    def New(*args, **kargs):
        """New() -> itkBinaryContourImageFilterIUC3IUC3

        Create a new object of the class itkBinaryContourImageFilterIUC3IUC3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryContourImageFilterIUC3IUC3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryContourImageFilterIUC3IUC3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryContourImageFilterIUC3IUC3.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryContourImageFilterIUC3IUC3 in _itkBinaryContourImageFilterPython:
_itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC3IUC3_swigregister(itkBinaryContourImageFilterIUC3IUC3)

def itkBinaryContourImageFilterIUC4IUC4_New():
    return itkBinaryContourImageFilterIUC4IUC4.New()

class itkBinaryContourImageFilterIUC4IUC4(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC4IUC4):
    r"""Proxy of C++ itkBinaryContourImageFilterIUC4IUC4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkBinaryContourImageFilterIUC4IUC4_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC4IUC4___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkBinaryContourImageFilterIUC4IUC4_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC4IUC4_Clone(self)

    def SetFullyConnected(self, _arg):
        r"""
        SetFullyConnected(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC4IUC4_SetFullyConnected(self, _arg)

    def GetFullyConnected(self):
        r"""GetFullyConnected(self) -> bool const &"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC4IUC4_GetFullyConnected(self)

    def FullyConnectedOn(self):
        r"""FullyConnectedOn(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC4IUC4_FullyConnectedOn(self)

    def FullyConnectedOff(self):
        r"""FullyConnectedOff(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC4IUC4_FullyConnectedOff(self)

    def SetBackgroundValue(self, _arg):
        r"""
        SetBackgroundValue(self, _arg)

        Parameters
        ----------
        _arg: unsigned char

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC4IUC4_SetBackgroundValue(self, _arg)

    def GetBackgroundValue(self):
        r"""GetBackgroundValue(self) -> unsigned char"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC4IUC4_GetBackgroundValue(self)

    def SetForegroundValue(self, _arg):
        r"""
        SetForegroundValue(self, _arg)

        Parameters
        ----------
        _arg: unsigned char

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC4IUC4_SetForegroundValue(self, _arg)

    def GetForegroundValue(self):
        r"""GetForegroundValue(self) -> unsigned char"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC4IUC4_GetForegroundValue(self)
    __swig_destroy__ = _itkBinaryContourImageFilterPython.delete_itkBinaryContourImageFilterIUC4IUC4

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkBinaryContourImageFilterIUC4IUC4

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC4IUC4_cast(obj)

    def New(*args, **kargs):
        """New() -> itkBinaryContourImageFilterIUC4IUC4

        Create a new object of the class itkBinaryContourImageFilterIUC4IUC4 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryContourImageFilterIUC4IUC4.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryContourImageFilterIUC4IUC4.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryContourImageFilterIUC4IUC4.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryContourImageFilterIUC4IUC4 in _itkBinaryContourImageFilterPython:
_itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUC4IUC4_swigregister(itkBinaryContourImageFilterIUC4IUC4)

def itkBinaryContourImageFilterIUS2IUS2_New():
    return itkBinaryContourImageFilterIUS2IUS2.New()

class itkBinaryContourImageFilterIUS2IUS2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUS2IUS2):
    r"""Proxy of C++ itkBinaryContourImageFilterIUS2IUS2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkBinaryContourImageFilterIUS2IUS2_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS2IUS2___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkBinaryContourImageFilterIUS2IUS2_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS2IUS2_Clone(self)

    def SetFullyConnected(self, _arg):
        r"""
        SetFullyConnected(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS2IUS2_SetFullyConnected(self, _arg)

    def GetFullyConnected(self):
        r"""GetFullyConnected(self) -> bool const &"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS2IUS2_GetFullyConnected(self)

    def FullyConnectedOn(self):
        r"""FullyConnectedOn(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS2IUS2_FullyConnectedOn(self)

    def FullyConnectedOff(self):
        r"""FullyConnectedOff(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS2IUS2_FullyConnectedOff(self)

    def SetBackgroundValue(self, _arg):
        r"""
        SetBackgroundValue(self, _arg)

        Parameters
        ----------
        _arg: unsigned short

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS2IUS2_SetBackgroundValue(self, _arg)

    def GetBackgroundValue(self):
        r"""GetBackgroundValue(self) -> unsigned short"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS2IUS2_GetBackgroundValue(self)

    def SetForegroundValue(self, _arg):
        r"""
        SetForegroundValue(self, _arg)

        Parameters
        ----------
        _arg: unsigned short

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS2IUS2_SetForegroundValue(self, _arg)

    def GetForegroundValue(self):
        r"""GetForegroundValue(self) -> unsigned short"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS2IUS2_GetForegroundValue(self)
    __swig_destroy__ = _itkBinaryContourImageFilterPython.delete_itkBinaryContourImageFilterIUS2IUS2

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkBinaryContourImageFilterIUS2IUS2

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS2IUS2_cast(obj)

    def New(*args, **kargs):
        """New() -> itkBinaryContourImageFilterIUS2IUS2

        Create a new object of the class itkBinaryContourImageFilterIUS2IUS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryContourImageFilterIUS2IUS2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryContourImageFilterIUS2IUS2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryContourImageFilterIUS2IUS2.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryContourImageFilterIUS2IUS2 in _itkBinaryContourImageFilterPython:
_itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS2IUS2_swigregister(itkBinaryContourImageFilterIUS2IUS2)

def itkBinaryContourImageFilterIUS3IUS3_New():
    return itkBinaryContourImageFilterIUS3IUS3.New()

class itkBinaryContourImageFilterIUS3IUS3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUS3IUS3):
    r"""Proxy of C++ itkBinaryContourImageFilterIUS3IUS3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkBinaryContourImageFilterIUS3IUS3_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS3IUS3___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkBinaryContourImageFilterIUS3IUS3_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS3IUS3_Clone(self)

    def SetFullyConnected(self, _arg):
        r"""
        SetFullyConnected(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS3IUS3_SetFullyConnected(self, _arg)

    def GetFullyConnected(self):
        r"""GetFullyConnected(self) -> bool const &"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS3IUS3_GetFullyConnected(self)

    def FullyConnectedOn(self):
        r"""FullyConnectedOn(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS3IUS3_FullyConnectedOn(self)

    def FullyConnectedOff(self):
        r"""FullyConnectedOff(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS3IUS3_FullyConnectedOff(self)

    def SetBackgroundValue(self, _arg):
        r"""
        SetBackgroundValue(self, _arg)

        Parameters
        ----------
        _arg: unsigned short

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS3IUS3_SetBackgroundValue(self, _arg)

    def GetBackgroundValue(self):
        r"""GetBackgroundValue(self) -> unsigned short"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS3IUS3_GetBackgroundValue(self)

    def SetForegroundValue(self, _arg):
        r"""
        SetForegroundValue(self, _arg)

        Parameters
        ----------
        _arg: unsigned short

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS3IUS3_SetForegroundValue(self, _arg)

    def GetForegroundValue(self):
        r"""GetForegroundValue(self) -> unsigned short"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS3IUS3_GetForegroundValue(self)
    __swig_destroy__ = _itkBinaryContourImageFilterPython.delete_itkBinaryContourImageFilterIUS3IUS3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkBinaryContourImageFilterIUS3IUS3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS3IUS3_cast(obj)

    def New(*args, **kargs):
        """New() -> itkBinaryContourImageFilterIUS3IUS3

        Create a new object of the class itkBinaryContourImageFilterIUS3IUS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryContourImageFilterIUS3IUS3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryContourImageFilterIUS3IUS3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryContourImageFilterIUS3IUS3.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryContourImageFilterIUS3IUS3 in _itkBinaryContourImageFilterPython:
_itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS3IUS3_swigregister(itkBinaryContourImageFilterIUS3IUS3)

def itkBinaryContourImageFilterIUS4IUS4_New():
    return itkBinaryContourImageFilterIUS4IUS4.New()

class itkBinaryContourImageFilterIUS4IUS4(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUS4IUS4):
    r"""Proxy of C++ itkBinaryContourImageFilterIUS4IUS4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkBinaryContourImageFilterIUS4IUS4_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS4IUS4___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkBinaryContourImageFilterIUS4IUS4_Pointer"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS4IUS4_Clone(self)

    def SetFullyConnected(self, _arg):
        r"""
        SetFullyConnected(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS4IUS4_SetFullyConnected(self, _arg)

    def GetFullyConnected(self):
        r"""GetFullyConnected(self) -> bool const &"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS4IUS4_GetFullyConnected(self)

    def FullyConnectedOn(self):
        r"""FullyConnectedOn(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS4IUS4_FullyConnectedOn(self)

    def FullyConnectedOff(self):
        r"""FullyConnectedOff(self)"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS4IUS4_FullyConnectedOff(self)

    def SetBackgroundValue(self, _arg):
        r"""
        SetBackgroundValue(self, _arg)

        Parameters
        ----------
        _arg: unsigned short

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS4IUS4_SetBackgroundValue(self, _arg)

    def GetBackgroundValue(self):
        r"""GetBackgroundValue(self) -> unsigned short"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS4IUS4_GetBackgroundValue(self)

    def SetForegroundValue(self, _arg):
        r"""
        SetForegroundValue(self, _arg)

        Parameters
        ----------
        _arg: unsigned short

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS4IUS4_SetForegroundValue(self, _arg)

    def GetForegroundValue(self):
        r"""GetForegroundValue(self) -> unsigned short"""
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS4IUS4_GetForegroundValue(self)
    __swig_destroy__ = _itkBinaryContourImageFilterPython.delete_itkBinaryContourImageFilterIUS4IUS4

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkBinaryContourImageFilterIUS4IUS4

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS4IUS4_cast(obj)

    def New(*args, **kargs):
        """New() -> itkBinaryContourImageFilterIUS4IUS4

        Create a new object of the class itkBinaryContourImageFilterIUS4IUS4 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryContourImageFilterIUS4IUS4.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryContourImageFilterIUS4IUS4.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryContourImageFilterIUS4IUS4.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryContourImageFilterIUS4IUS4 in _itkBinaryContourImageFilterPython:
_itkBinaryContourImageFilterPython.itkBinaryContourImageFilterIUS4IUS4_swigregister(itkBinaryContourImageFilterIUS4IUS4)

from itk.support import helpers
import itk.support.types as itkt
from typing import Union
from collections.abc import Sequence

@helpers.accept_array_like_xarray_torch
def binary_contour_image_filter(*args: itkt.ImageLike,  fully_connected: bool=..., background_value: float=..., foreground_value: float=...,**kwargs)-> itkt.ImageSourceReturn:
    """Functional interface for BinaryContourImageFilter"""
    import itk

    kwarg_typehints = { 'fully_connected':fully_connected,'background_value':background_value,'foreground_value':foreground_value }
    specified_kwarg_typehints = { k:v for (k,v) in kwarg_typehints.items() if kwarg_typehints[k] is not ... }
    kwargs.update(specified_kwarg_typehints)


    instance = itk.BinaryContourImageFilter.New(*args, **kwargs)

    return instance.__internal_call__()

def binary_contour_image_filter_init_docstring():
    import itk
    from itk.support import template_class

    filter_class = itk.ITKImageLabel.BinaryContourImageFilter
    binary_contour_image_filter.process_object = filter_class
    is_template = isinstance(filter_class, template_class.itkTemplate)
    if is_template:
        filter_object = filter_class.values()[0]
    else:
        filter_object = filter_class

    binary_contour_image_filter.__doc__ = filter_object.__doc__



