def call_on_int(cycle: tuple[int, ...], idx: int) -> int: ...
def call_on_str(cycle: tuple[int, ...], string: str) -> str: ...
def int_repr(cycle: tuple[int, ...]) -> int: ...
def inversions(cycle: tuple[int, ...]) -> list[tuple[int, int]]: ...
def map(cycle: tuple[int, ...]) -> dict[int, int]: ...
def repr(cycle: tuple[int, ...]) -> str: ...
def standardization(cycle: tuple[int, ...]) -> tuple[int, ...]: ...
def str(cycle: tuple[int, ...]) -> str: ...
