from setuptools import setup, find_packages

with open('README.md', 'r', encoding='utf-8') as fh:
    long_description = fh.read()

setup(
    name="pywiner",
    version="0.2.2",
    author="GuestRoblox Studios",
    author_email="maria.gomes23.1949@gmail.com",
    description="A Python library for Windows automation and a native window framework.",
    long_description=long_description,
    long_description_content_type='text/markdown',
    url="https://github.com/RoVerify/pywiner",
    packages=find_packages(),
    license='MIT',
    keywords=[
        'windows-automation',
        'pywiner',
        'gui-framework',
        'windows-api',
        'python-windows',
        'system-automation',
        'windows-gui',
        'automation',
        'pyqt6',
        'native-windows',
        'windows-desktop',
        'gui-automation',
        'windows-apps',
        'python-automation',
        'windows-programming',
        'qt6-python',
        'desktop-automation',
        'window-management',
        'process-automation',
        'system-tray',
        'native-gui',
        'cross-platform-gui',
        'ui-automation',
        'windows-services',
        'python-library',
        'development-tools',
        'software-development',
        'api-wrapper',
        'windows-integration',
        'gui-development',
        'automation-tools',
        'python-framework',
        'windows-sdk',
        'desktop-apps',
        'application-framework',
        'robotics-process-automation',
        'rpa-python',
        'batch-automation',
        'task-automation',
        'system-control',
        'windows-control',
        'gui-control',
        'process-control',
        'window-control',
        'desktop-control',
        'automation-library',
        'python3-library',
        'windows-10',
        'windows-11',
        'microsoft-windows',
        'pywiner-library',
        'guestroblox-studios',
        'roverify'
    ],
    classifiers=[
        "Development Status :: 4 - Beta",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "License :: OSI Approved :: MIT License",
        "Operating System :: Microsoft :: Windows",
        "Operating System :: Microsoft :: Windows :: Windows 10",
        "Operating System :: Microsoft :: Windows :: Windows 11",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: System :: Operating System",
        "Topic :: Desktop Environment",
        "Topic :: Software Development :: User Interfaces",
        "Topic :: System :: Systems Administration",
        "Topic :: Utilities",
    ],
    python_requires='>=3.6',
    install_requires=[
        'PyQt6',
        'Pillow'
    ],
    include_package_data=True,
)