# py_outfit/__init__.py

from .py_outfit import (
    PyOutfit,
    Observer,
    IODParams,
    TrajectorySet,
    GaussResult,
    KeplerianElements,
    EquinoctialElements,
    CometaryElements,
    Observations,
    DPI,
    SECONDS_PER_DAY,
    AU,
    EPS,
    T2000,
    JDTOMJD,
    RADEG,
    RADSEC,
    RAD2ARC,
    RADH,
    EARTH_MAJOR_AXIS,
    EARTH_MINOR_AXIS,
    ERAU,
    GAUSS_GRAV,
    GAUSS_GRAV_SQUARED,
    VLIGHT,
    VLIGHT_AU,
)

# 2) Nettoie l'API publique
__all__ = [
    "PyOutfit",
    "Observer",
    "IODParams",
    "TrajectorySet",
    "GaussResult",
    "KeplerianElements",
    "EquinoctialElements",
    "CometaryElements",
    "Observations",
    "DPI",
    "SECONDS_PER_DAY",
    "AU",
    "EPS",
    "T2000",
    "JDTOMJD",
    "RADEG",
    "RADSEC",
    "RAD2ARC",
    "RADH",
    "EARTH_MAJOR_AXIS",
    "EARTH_MINOR_AXIS",
    "ERAU",
    "GAUSS_GRAV",
    "GAUSS_GRAV_SQUARED",
    "VLIGHT",
    "VLIGHT_AU",
]
