"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kintsugi_tax_platform_sdk.types import BaseModel
from kintsugi_tax_platform_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetFilingByIDV1FilingsFilingIDGetRequestTypedDict(TypedDict):
    filing_id: str
    r"""Unique identifier for the filing to retrieve."""


class GetFilingByIDV1FilingsFilingIDGetRequest(BaseModel):
    filing_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique identifier for the filing to retrieve."""
