# Generated by Django 5.2.1 on 2025-09-22 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0207_remove_redundant_indexes'),
        ('netbox_firmware', '0005_alter_firmware_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bios',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveConstraint(
            model_name='bios',
            name='bios_device_type_or_module_type_required',
        ),
        migrations.AlterUniqueTogether(
            name='bios',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bios',
            name='manufacturer',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, related_name='bios', to='dcim.manufacturer'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Firmware', to='dcim.manufacturer'),
        ),
        migrations.RemoveField(
            model_name='bios',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='bios',
            name='module_type',
        ),
        migrations.AddField(
            model_name='bios',
            name='device_type',
            field=models.ManyToManyField(blank=True, related_name='bios', to='dcim.devicetype'),
        ),
        migrations.AddField(
            model_name='bios',
            name='module_type',
            field=models.ManyToManyField(blank=True, related_name='bios', to='dcim.moduletype'),
        ),
    ]
