def validate_permutation(image: tuple[int, ...]) -> None: ...
def validate_cycle(cycle: tuple[int, ...]) -> None: ...
def validate_cycle_decomposition(decomposition: tuple[tuple[int, ...], ...]) -> None: ...
