from .advanced_ml_tab import AdvancedMLTabWithPlots
from .batch_processor_tab import BatchProcessingTab
from .multi_model_tab import MultiModelTab
from .kfold_visualization import plot_kfold_results,integrate_kfold_visualization