# Generated by Django 5.2.5 on 2025-08-21 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
                ("cert_path", models.CharField()),
                ("key_path", models.CharField()),
                ("is_pkcs11", models.BooleanField(default=False)),
                ("expires", models.DateTimeField()),
                ("pkcs11_module", models.CharField(blank=True, null=True)),
                ("ossl_provider", models.CharField(blank=True, null=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TimestampServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
                ("url", models.URLField()),
                ("is_enabled", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SigningProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "certificates",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="signing.certificate"
                    ),
                ),
                (
                    "timestamp_servers",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="signing.timestampserver"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SigningLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("finished", models.DateTimeField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField()),
                ("user_agent", models.CharField(blank=True, null=True)),
                ("client_name", models.CharField()),
                ("signing_profile_name", models.CharField(blank=True, null=True)),
                ("certificate_name", models.CharField(blank=True, null=True)),
                ("description", models.CharField(blank=True, null=True)),
                ("url", models.CharField(blank=True, null=True)),
                ("submitted_file_name", models.CharField(blank=True, null=True)),
                ("in_path", models.CharField(blank=True, null=True)),
                ("in_file_size", models.BigIntegerField(blank=True, null=True)),
                ("in_file_sha256", models.CharField(blank=True, null=True)),
                ("out_path", models.CharField(blank=True, null=True)),
                ("out_file_size", models.BigIntegerField(blank=True, null=True)),
                ("out_file_sha256", models.CharField(blank=True, null=True)),
                ("osslsigncode_returncode", models.IntegerField(blank=True, null=True)),
                ("osslsigncode_stdout", models.TextField(blank=True, null=True)),
                ("osslsigncode_stderr", models.TextField(blank=True, null=True)),
                ("virus_total_url", models.URLField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("sign-error", "Signing Error"),
                            ("no-certs", "No Certificates"),
                            ("av-positive", "AV Positive"),
                            (
                                "unsupported-file-extension",
                                "Unsupported File Extension",
                            ),
                            ("internal-error", "Internal Error"),
                            ("cancelled", "Cancelled"),
                            ("pin-timeout", "PIN Timeout"),
                        ]
                    ),
                ),
                ("exception", models.CharField(blank=True, null=True)),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="signing.certificate",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.client",
                    ),
                ),
                (
                    "signing_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="signing.signingprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["-created"], name="signing_sig_created_2b1a65_idx"
                    ),
                    models.Index(
                        fields=["client_name", "-created"],
                        name="signing_sig_client__3012c4_idx",
                    ),
                    models.Index(
                        fields=["signing_profile_name", "-created"],
                        name="signing_sig_signing_dede49_idx",
                    ),
                ],
            },
        ),
    ]
