{
 "title": "TWST Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "modem",
    "label": "Receiver",
    "query": "SELECT uuid AS __value, COALESCE(name, CONCAT(ip_address, ' Interface ', probe_id)) AS __text FROM castdb.probe_metadata where vendor = 'MicrochipTWST' and probe_id = 'modem'"
   },
   {
    "name": "resolution",
    "label": "Time Interval",
    "query": "1min, 5min, 15min, 1hour, 6hour, 1day"
   },
   {
    "name": "compound_ref",
    "label": "Remote Modem",
    "query": "SELECT pm.uuid AS __value, COALESCE(name, probe_id) AS __text\nFROM castdb.probe_metadata pm\nJOIN castdb.reference r ON pm.uuid = r.compound_reference_uuid\nWHERE r.uuid IN (\n  SELECT DISTINCT reference_uuid\n  FROM castdb.probe_data\n  WHERE probe_uuid = ${modem:sqlstring})"
   },
   {
    "name": "phase_offset_uuid",
    "query": "select uuid from castdb.metric_type where lower(name) = 'phase offset';"
   },
   {
    "name": "ebno_uuid",
    "query": "select uuid from castdb.metric_type where lower(name) = 'eb/no';"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Probe Location Map",
   "type": "geomap",
   "description": "Shows where each of the modems are, with the receiver in blue and the remote modems in green.",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select\n    pm.name as \"Clock\",\n    l.name as \"Location Name\",\n    l.latitude,\n    l.longitude,\n    l.campus\nfrom castdb.campus_locations l left join castdb.probe_metadata pm on l.uuid = pm.location_uuid\nwhere pm.uuid in (${compound_ref:sqlstring});"
    },
    {
     "rawSql": "select\n    pm.name as \"Clock\",\n    l.name as \"Location Name\",\n    l.latitude,\n    l.longitude,\n    l.campus\nfrom castdb.campus_locations l left join castdb.probe_metadata pm on l.uuid = pm.location_uuid\nwhere pm.uuid in (${modem:sqlstring});"
    },
    {
     "rawSql": "select\n    -- pm.name as \"Clock\",\n    l.name as \"Location Name\",\n    l.latitude,\n    l.longitude,\n    l.campus\nfrom castdb.campus_locations l left join castdb.probe_metadata pm on l.uuid = pm.location_uuid\nwhere pm.uuid in (${modem:sqlstring}, ${compound_ref:sqlstring});"
    }
   ]
  },
  {
   "title": "Received Satellite Signal Strength",
   "type": "timeseries",
   "description": "Energy per bit to noise power spectral density ratio measured at the clock probe. Indicates the quality of the received signal relative to noise.",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC') AS time,\n  coalesce(pm.name, pm.probe_id) AS channel,\n  AVG(pd.value::FLOAT) AS value\nFROM \n  get_probe_data_by_probe_and_metric(${modem:sqlstring}, ${ebno_uuid:sqlstring}) pd\nJOIN \n  castdb.reference r ON pd.reference_uuid = r.uuid\nJOIN \n  castdb.probe_metadata pm ON r.compound_reference_uuid = pm.uuid\nWHERE \n  $__timeFilter(pd.time)\n  and r.compound_reference_uuid in (${compound_ref:sqlstring})\nGROUP BY \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC'),\n  pm.name,\n  pm.probe_id\nORDER BY \n  time\n"
    }
   ]
  },
  {
   "title": "Time Offset from Local Time",
   "type": "timeseries",
   "description": "The difference in time readings between indicated modem and chosen receiver",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "select \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC') AS time,\n  COALESCE(pm.name, pm.probe_id) as name,\n  AVG(pd.value::FLOAT) * 1e9 AS value\nFROM \n  get_probe_data_by_probe_and_metric(${modem:sqlstring}, ${phase_offset_uuid:sqlstring}) pd\njoin castdb.reference r on pd.reference_uuid = r.uuid\nJOIN \n  castdb.probe_metadata pm ON r.compound_reference_uuid = pm.uuid\nwhere \n  $__timeFilter(pd.time)\n  and r.compound_reference_uuid in (${compound_ref:sqlstring})\nGROUP BY \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC'),\n  pm.uuid\nORDER BY \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC')"
    }
   ]
  },
  {
   "title": "Max Time Interval Error",
   "type": "timeseries",
   "description": "The maximum time offset from receiver in given time period",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "select \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC') AS time,\n  COALESCE(pm.name, pm.probe_id) as name,\n  (MAX(pd.value::FLOAT) - MIN(pd.value::FLOAT)) * 1e9 AS value\nFROM \n  get_probe_data_by_probe_and_metric(${modem:sqlstring}, ${phase_offset_uuid:sqlstring}) pd\njoin castdb.reference r on pd.reference_uuid = r.uuid\nJOIN \n  castdb.probe_metadata pm ON r.compound_reference_uuid = pm.uuid\nwhere \n  $__timeFilter(pd.time)\n  and r.compound_reference_uuid in (${compound_ref:sqlstring})\nGROUP BY \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC'),\n  pm.uuid\nORDER BY \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC')"
    }
   ]
  },
  { "title": "$modem vs $compound_ref", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "compound_ref" },
  {
   "title": "Probe Location Map",
   "type": "geomap",
   "description": "Shows where each of the modems are, with the receiver in blue and the remote modems in green.",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "select\n    pm.name as \"Clock\",\n    l.name as \"Location Name\",\n    l.latitude,\n    l.longitude,\n    l.campus\nfrom castdb.campus_locations l left join castdb.probe_metadata pm on l.uuid = pm.location_uuid\nwhere pm.uuid in (${compound_ref:sqlstring});"
    },
    {
     "rawSql": "select\n    pm.name as \"Clock\",\n    l.name as \"Location Name\",\n    l.latitude,\n    l.longitude,\n    l.campus\nfrom castdb.campus_locations l left join castdb.probe_metadata pm on l.uuid = pm.location_uuid\nwhere pm.uuid in (${modem:sqlstring});"
    },
    {
     "rawSql": "select\n    -- pm.name as \"Clock\",\n    l.name as \"Location Name\",\n    l.latitude,\n    l.longitude,\n    l.campus\nfrom castdb.campus_locations l left join castdb.probe_metadata pm on l.uuid = pm.location_uuid\nwhere pm.uuid in (${modem:sqlstring}, ${compound_ref:sqlstring});"
    }
   ]
  },
  {
   "title": "Received Satellite Signal Strength",
   "type": "timeseries",
   "description": "Energy per bit to noise power spectral density ratio measured at the clock probe. Indicates the quality of the received signal relative to noise.",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "rawSql": "select \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC') AS time,\n  AVG(pd.value::FLOAT) AS value\nFROM \n  get_probe_data_by_probe_and_metric(${modem:sqlstring}, ${ebno_uuid:sqlstring}) pd\njoin castdb.reference r on pd.reference_uuid = r.uuid\nwhere \n  $__timeFilter(pd.time)\n  AND r.compound_reference_uuid = ${compound_ref:sqlstring}\nGROUP BY \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC'),\n  pd.probe_uuid\nORDER BY \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC')"
    }
   ]
  },
  {
   "title": "Time Offset from Local Time",
   "type": "timeseries",
   "description": "The difference in time readings between indicated modem and chosen receiver",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "select \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC') AS time,\n  AVG(pd.value::FLOAT) * 1e9 AS value\nFROM \n  get_probe_data_by_probe_and_metric(${modem:sqlstring}, ${phase_offset_uuid:sqlstring}) pd\njoin castdb.reference r on pd.reference_uuid = r.uuid\nwhere \n  $__timeFilter(pd.time)\n  AND r.compound_reference_uuid = ${compound_ref:sqlstring}\nGROUP BY \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC'),\n  pd.probe_uuid\nORDER BY \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC')"
    }
   ]
  },
  {
   "title": "Max Time Interval Error",
   "type": "timeseries",
   "description": "The maximum time offset from receiver in given time period",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "select \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC') AS time,\n  (MAX(pd.value::FLOAT) - MIN(pd.value::FLOAT)) * 1e9 AS value\nFROM \n  get_probe_data_by_probe_and_metric(${modem:sqlstring}, ${phase_offset_uuid:sqlstring}) pd\njoin castdb.reference r on pd.reference_uuid = r.uuid\nwhere \n  $__timeFilter(pd.time)\n  AND r.compound_reference_uuid = ${compound_ref:sqlstring}\nGROUP BY \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC'),\n  pd.probe_uuid\nORDER BY \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC')"
    }
   ]
  }
 ]
}