depends = ('ITKPyBase', 'ITKSmoothing', 'ITKImageIntensity', 'ITKImageGrid', )
templates = (  ('TimeVaryingVelocityFieldTransform', 'itk::TimeVaryingVelocityFieldTransform', 'itkTimeVaryingVelocityFieldTransformD2', True, 'double,2'),
  ('TimeVaryingVelocityFieldTransform', 'itk::TimeVaryingVelocityFieldTransform', 'itkTimeVaryingVelocityFieldTransformD3', True, 'double,3'),
  ('TimeVaryingVelocityFieldTransform', 'itk::TimeVaryingVelocityFieldTransform', 'itkTimeVaryingVelocityFieldTransformD4', True, 'double,4'),
  ('BSplineExponentialDiffeomorphicTransform', 'itk::BSplineExponentialDiffeomorphicTransform', 'itkBSplineExponentialDiffeomorphicTransformD2', True, 'double,2'),
  ('BSplineExponentialDiffeomorphicTransform', 'itk::BSplineExponentialDiffeomorphicTransform', 'itkBSplineExponentialDiffeomorphicTransformD3', True, 'double,3'),
  ('BSplineExponentialDiffeomorphicTransform', 'itk::BSplineExponentialDiffeomorphicTransform', 'itkBSplineExponentialDiffeomorphicTransformD4', True, 'double,4'),
  ('BSplineSmoothingOnUpdateDisplacementFieldTransform', 'itk::BSplineSmoothingOnUpdateDisplacementFieldTransform', 'itkBSplineSmoothingOnUpdateDisplacementFieldTransformD2', True, 'double,2'),
  ('BSplineSmoothingOnUpdateDisplacementFieldTransform', 'itk::BSplineSmoothingOnUpdateDisplacementFieldTransform', 'itkBSplineSmoothingOnUpdateDisplacementFieldTransformD3', True, 'double,3'),
  ('BSplineSmoothingOnUpdateDisplacementFieldTransform', 'itk::BSplineSmoothingOnUpdateDisplacementFieldTransform', 'itkBSplineSmoothingOnUpdateDisplacementFieldTransformD4', True, 'double,4'),
  ('ConstantVelocityFieldTransform', 'itk::ConstantVelocityFieldTransform', 'itkConstantVelocityFieldTransformD2', True, 'double,2'),
  ('ConstantVelocityFieldTransform', 'itk::ConstantVelocityFieldTransform', 'itkConstantVelocityFieldTransformD3', True, 'double,3'),
  ('ConstantVelocityFieldTransform', 'itk::ConstantVelocityFieldTransform', 'itkConstantVelocityFieldTransformD4', True, 'double,4'),
  ('DisplacementFieldJacobianDeterminantFilter', 'itk::DisplacementFieldJacobianDeterminantFilter', 'itkDisplacementFieldJacobianDeterminantFilterIVF22F', True, 'itk::Image< itk::Vector< float,2 >,2 >, float'),
  ('DisplacementFieldJacobianDeterminantFilter', 'itk::DisplacementFieldJacobianDeterminantFilter', 'itkDisplacementFieldJacobianDeterminantFilterIVF22D', True, 'itk::Image< itk::Vector< float,2 >,2 >, double'),
  ('DisplacementFieldJacobianDeterminantFilter', 'itk::DisplacementFieldJacobianDeterminantFilter', 'itkDisplacementFieldJacobianDeterminantFilterIVF33F', True, 'itk::Image< itk::Vector< float,3 >,3 >, float'),
  ('DisplacementFieldJacobianDeterminantFilter', 'itk::DisplacementFieldJacobianDeterminantFilter', 'itkDisplacementFieldJacobianDeterminantFilterIVF33D', True, 'itk::Image< itk::Vector< float,3 >,3 >, double'),
  ('DisplacementFieldJacobianDeterminantFilter', 'itk::DisplacementFieldJacobianDeterminantFilter', 'itkDisplacementFieldJacobianDeterminantFilterIVF44F', True, 'itk::Image< itk::Vector< float,4 >,4 >, float'),
  ('DisplacementFieldJacobianDeterminantFilter', 'itk::DisplacementFieldJacobianDeterminantFilter', 'itkDisplacementFieldJacobianDeterminantFilterIVF44D', True, 'itk::Image< itk::Vector< float,4 >,4 >, double'),
  ('DisplacementFieldTransform', 'itk::DisplacementFieldTransform', 'itkDisplacementFieldTransformD2', True, 'double,2'),
  ('DisplacementFieldTransform', 'itk::DisplacementFieldTransform', 'itkDisplacementFieldTransformF2', True, 'float,2'),
  ('DisplacementFieldTransform', 'itk::DisplacementFieldTransform', 'itkDisplacementFieldTransformD3', True, 'double,3'),
  ('DisplacementFieldTransform', 'itk::DisplacementFieldTransform', 'itkDisplacementFieldTransformF3', True, 'float,3'),
  ('DisplacementFieldTransform', 'itk::DisplacementFieldTransform', 'itkDisplacementFieldTransformD4', True, 'double,4'),
  ('DisplacementFieldTransform', 'itk::DisplacementFieldTransform', 'itkDisplacementFieldTransformF4', True, 'float,4'),
  ('GaussianExponentialDiffeomorphicTransform', 'itk::GaussianExponentialDiffeomorphicTransform', 'itkGaussianExponentialDiffeomorphicTransformD2', True, 'double,2'),
  ('GaussianExponentialDiffeomorphicTransform', 'itk::GaussianExponentialDiffeomorphicTransform', 'itkGaussianExponentialDiffeomorphicTransformD3', True, 'double,3'),
  ('GaussianExponentialDiffeomorphicTransform', 'itk::GaussianExponentialDiffeomorphicTransform', 'itkGaussianExponentialDiffeomorphicTransformD4', True, 'double,4'),
  ('GaussianSmoothingOnUpdateDisplacementFieldTransform', 'itk::GaussianSmoothingOnUpdateDisplacementFieldTransform', 'itkGaussianSmoothingOnUpdateDisplacementFieldTransformD2', True, 'double,2'),
  ('GaussianSmoothingOnUpdateDisplacementFieldTransform', 'itk::GaussianSmoothingOnUpdateDisplacementFieldTransform', 'itkGaussianSmoothingOnUpdateDisplacementFieldTransformD3', True, 'double,3'),
  ('GaussianSmoothingOnUpdateDisplacementFieldTransform', 'itk::GaussianSmoothingOnUpdateDisplacementFieldTransform', 'itkGaussianSmoothingOnUpdateDisplacementFieldTransformD4', True, 'double,4'),
  ('GaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransform', 'itk::GaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransform', 'itkGaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransformD2', True, 'double,2'),
  ('GaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransform', 'itk::GaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransform', 'itkGaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransformD3', True, 'double,3'),
  ('GaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransform', 'itk::GaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransform', 'itkGaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransformD4', True, 'double,4'),
  ('TimeVaryingBSplineVelocityFieldTransform', 'itk::TimeVaryingBSplineVelocityFieldTransform', 'itkTimeVaryingBSplineVelocityFieldTransformD2', True, 'double,2'),
  ('TimeVaryingBSplineVelocityFieldTransform', 'itk::TimeVaryingBSplineVelocityFieldTransform', 'itkTimeVaryingBSplineVelocityFieldTransformD3', True, 'double,3'),
  ('TimeVaryingBSplineVelocityFieldTransform', 'itk::TimeVaryingBSplineVelocityFieldTransform', 'itkTimeVaryingBSplineVelocityFieldTransformD4', True, 'double,4'),
  ('TransformToDisplacementFieldFilter', 'itk::TransformToDisplacementFieldFilter', 'itkTransformToDisplacementFieldFilterIVF22F', True, 'itk::Image< itk::Vector< float,2 >,2 >, float'),
  ('TransformToDisplacementFieldFilter', 'itk::TransformToDisplacementFieldFilter', 'itkTransformToDisplacementFieldFilterIVF22D', True, 'itk::Image< itk::Vector< float,2 >,2 >, double'),
  ('TransformToDisplacementFieldFilter', 'itk::TransformToDisplacementFieldFilter', 'itkTransformToDisplacementFieldFilterIVF33F', True, 'itk::Image< itk::Vector< float,3 >,3 >, float'),
  ('TransformToDisplacementFieldFilter', 'itk::TransformToDisplacementFieldFilter', 'itkTransformToDisplacementFieldFilterIVF33D', True, 'itk::Image< itk::Vector< float,3 >,3 >, double'),
  ('TransformToDisplacementFieldFilter', 'itk::TransformToDisplacementFieldFilter', 'itkTransformToDisplacementFieldFilterIVF44F', True, 'itk::Image< itk::Vector< float,4 >,4 >, float'),
  ('TransformToDisplacementFieldFilter', 'itk::TransformToDisplacementFieldFilter', 'itkTransformToDisplacementFieldFilterIVF44D', True, 'itk::Image< itk::Vector< float,4 >,4 >, double'),
  ('TransformToDisplacementFieldFilter', 'itk::TransformToDisplacementFieldFilter', 'itkTransformToDisplacementFieldFilterICVF22F', True, 'itk::Image< itk::CovariantVector< float,2 >,2 >, float'),
  ('TransformToDisplacementFieldFilter', 'itk::TransformToDisplacementFieldFilter', 'itkTransformToDisplacementFieldFilterICVF22D', True, 'itk::Image< itk::CovariantVector< float,2 >,2 >, double'),
  ('TransformToDisplacementFieldFilter', 'itk::TransformToDisplacementFieldFilter', 'itkTransformToDisplacementFieldFilterICVF33F', True, 'itk::Image< itk::CovariantVector< float,3 >,3 >, float'),
  ('TransformToDisplacementFieldFilter', 'itk::TransformToDisplacementFieldFilter', 'itkTransformToDisplacementFieldFilterICVF33D', True, 'itk::Image< itk::CovariantVector< float,3 >,3 >, double'),
  ('TransformToDisplacementFieldFilter', 'itk::TransformToDisplacementFieldFilter', 'itkTransformToDisplacementFieldFilterICVF44F', True, 'itk::Image< itk::CovariantVector< float,4 >,4 >, float'),
  ('TransformToDisplacementFieldFilter', 'itk::TransformToDisplacementFieldFilter', 'itkTransformToDisplacementFieldFilterICVF44D', True, 'itk::Image< itk::CovariantVector< float,4 >,4 >, double'),
  ('VelocityFieldTransform', 'itk::VelocityFieldTransform', 'itkVelocityFieldTransformD2', True, 'double,2'),
  ('VelocityFieldTransform', 'itk::VelocityFieldTransform', 'itkVelocityFieldTransformD3', True, 'double,3'),
  ('VelocityFieldTransform', 'itk::VelocityFieldTransform', 'itkVelocityFieldTransformD4', True, 'double,4'),
)
factories = ()
