depends = ('ITKPyBase', 'ITKImageSources', 'ITKConvolution', )
templates = (  ('IterativeDeconvolutionImageFilter', 'itk::IterativeDeconvolutionImageFilter', 'itkIterativeDeconvolutionImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('IterativeDeconvolutionImageFilter', 'itk::IterativeDeconvolutionImageFilter', 'itkIterativeDeconvolutionImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('IterativeDeconvolutionImageFilter', 'itk::IterativeDeconvolutionImageFilter', 'itkIterativeDeconvolutionImageFilterISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('IterativeDeconvolutionImageFilter', 'itk::IterativeDeconvolutionImageFilter', 'itkIterativeDeconvolutionImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('IterativeDeconvolutionImageFilter', 'itk::IterativeDeconvolutionImageFilter', 'itkIterativeDeconvolutionImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('IterativeDeconvolutionImageFilter', 'itk::IterativeDeconvolutionImageFilter', 'itkIterativeDeconvolutionImageFilterIUC4IUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned char,4 >'),
  ('IterativeDeconvolutionImageFilter', 'itk::IterativeDeconvolutionImageFilter', 'itkIterativeDeconvolutionImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('IterativeDeconvolutionImageFilter', 'itk::IterativeDeconvolutionImageFilter', 'itkIterativeDeconvolutionImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('IterativeDeconvolutionImageFilter', 'itk::IterativeDeconvolutionImageFilter', 'itkIterativeDeconvolutionImageFilterIUS4IUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >'),
  ('IterativeDeconvolutionImageFilter', 'itk::IterativeDeconvolutionImageFilter', 'itkIterativeDeconvolutionImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('IterativeDeconvolutionImageFilter', 'itk::IterativeDeconvolutionImageFilter', 'itkIterativeDeconvolutionImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('IterativeDeconvolutionImageFilter', 'itk::IterativeDeconvolutionImageFilter', 'itkIterativeDeconvolutionImageFilterIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('IterativeDeconvolutionImageFilter', 'itk::IterativeDeconvolutionImageFilter', 'itkIterativeDeconvolutionImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('IterativeDeconvolutionImageFilter', 'itk::IterativeDeconvolutionImageFilter', 'itkIterativeDeconvolutionImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('IterativeDeconvolutionImageFilter', 'itk::IterativeDeconvolutionImageFilter', 'itkIterativeDeconvolutionImageFilterID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('InverseDeconvolutionImageFilter', 'itk::InverseDeconvolutionImageFilter', 'itkInverseDeconvolutionImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('InverseDeconvolutionImageFilter', 'itk::InverseDeconvolutionImageFilter', 'itkInverseDeconvolutionImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('InverseDeconvolutionImageFilter', 'itk::InverseDeconvolutionImageFilter', 'itkInverseDeconvolutionImageFilterISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('InverseDeconvolutionImageFilter', 'itk::InverseDeconvolutionImageFilter', 'itkInverseDeconvolutionImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('InverseDeconvolutionImageFilter', 'itk::InverseDeconvolutionImageFilter', 'itkInverseDeconvolutionImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('InverseDeconvolutionImageFilter', 'itk::InverseDeconvolutionImageFilter', 'itkInverseDeconvolutionImageFilterIUC4IUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned char,4 >'),
  ('InverseDeconvolutionImageFilter', 'itk::InverseDeconvolutionImageFilter', 'itkInverseDeconvolutionImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('InverseDeconvolutionImageFilter', 'itk::InverseDeconvolutionImageFilter', 'itkInverseDeconvolutionImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('InverseDeconvolutionImageFilter', 'itk::InverseDeconvolutionImageFilter', 'itkInverseDeconvolutionImageFilterIUS4IUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >'),
  ('InverseDeconvolutionImageFilter', 'itk::InverseDeconvolutionImageFilter', 'itkInverseDeconvolutionImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('InverseDeconvolutionImageFilter', 'itk::InverseDeconvolutionImageFilter', 'itkInverseDeconvolutionImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('InverseDeconvolutionImageFilter', 'itk::InverseDeconvolutionImageFilter', 'itkInverseDeconvolutionImageFilterIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('InverseDeconvolutionImageFilter', 'itk::InverseDeconvolutionImageFilter', 'itkInverseDeconvolutionImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('InverseDeconvolutionImageFilter', 'itk::InverseDeconvolutionImageFilter', 'itkInverseDeconvolutionImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('InverseDeconvolutionImageFilter', 'itk::InverseDeconvolutionImageFilter', 'itkInverseDeconvolutionImageFilterID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('LandweberDeconvolutionImageFilter', 'itk::LandweberDeconvolutionImageFilter', 'itkLandweberDeconvolutionImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('LandweberDeconvolutionImageFilter', 'itk::LandweberDeconvolutionImageFilter', 'itkLandweberDeconvolutionImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('LandweberDeconvolutionImageFilter', 'itk::LandweberDeconvolutionImageFilter', 'itkLandweberDeconvolutionImageFilterISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('LandweberDeconvolutionImageFilter', 'itk::LandweberDeconvolutionImageFilter', 'itkLandweberDeconvolutionImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('LandweberDeconvolutionImageFilter', 'itk::LandweberDeconvolutionImageFilter', 'itkLandweberDeconvolutionImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('LandweberDeconvolutionImageFilter', 'itk::LandweberDeconvolutionImageFilter', 'itkLandweberDeconvolutionImageFilterIUC4IUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned char,4 >'),
  ('LandweberDeconvolutionImageFilter', 'itk::LandweberDeconvolutionImageFilter', 'itkLandweberDeconvolutionImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('LandweberDeconvolutionImageFilter', 'itk::LandweberDeconvolutionImageFilter', 'itkLandweberDeconvolutionImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('LandweberDeconvolutionImageFilter', 'itk::LandweberDeconvolutionImageFilter', 'itkLandweberDeconvolutionImageFilterIUS4IUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >'),
  ('LandweberDeconvolutionImageFilter', 'itk::LandweberDeconvolutionImageFilter', 'itkLandweberDeconvolutionImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('LandweberDeconvolutionImageFilter', 'itk::LandweberDeconvolutionImageFilter', 'itkLandweberDeconvolutionImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('LandweberDeconvolutionImageFilter', 'itk::LandweberDeconvolutionImageFilter', 'itkLandweberDeconvolutionImageFilterIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('LandweberDeconvolutionImageFilter', 'itk::LandweberDeconvolutionImageFilter', 'itkLandweberDeconvolutionImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('LandweberDeconvolutionImageFilter', 'itk::LandweberDeconvolutionImageFilter', 'itkLandweberDeconvolutionImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('LandweberDeconvolutionImageFilter', 'itk::LandweberDeconvolutionImageFilter', 'itkLandweberDeconvolutionImageFilterID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('ProjectedLandweberDeconvolutionImageFilter', 'itk::ProjectedLandweberDeconvolutionImageFilter', 'itkProjectedLandweberDeconvolutionImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('ProjectedLandweberDeconvolutionImageFilter', 'itk::ProjectedLandweberDeconvolutionImageFilter', 'itkProjectedLandweberDeconvolutionImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('ProjectedLandweberDeconvolutionImageFilter', 'itk::ProjectedLandweberDeconvolutionImageFilter', 'itkProjectedLandweberDeconvolutionImageFilterISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('ProjectedLandweberDeconvolutionImageFilter', 'itk::ProjectedLandweberDeconvolutionImageFilter', 'itkProjectedLandweberDeconvolutionImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ProjectedLandweberDeconvolutionImageFilter', 'itk::ProjectedLandweberDeconvolutionImageFilter', 'itkProjectedLandweberDeconvolutionImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ProjectedLandweberDeconvolutionImageFilter', 'itk::ProjectedLandweberDeconvolutionImageFilter', 'itkProjectedLandweberDeconvolutionImageFilterIUC4IUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned char,4 >'),
  ('ProjectedLandweberDeconvolutionImageFilter', 'itk::ProjectedLandweberDeconvolutionImageFilter', 'itkProjectedLandweberDeconvolutionImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('ProjectedLandweberDeconvolutionImageFilter', 'itk::ProjectedLandweberDeconvolutionImageFilter', 'itkProjectedLandweberDeconvolutionImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('ProjectedLandweberDeconvolutionImageFilter', 'itk::ProjectedLandweberDeconvolutionImageFilter', 'itkProjectedLandweberDeconvolutionImageFilterIUS4IUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >'),
  ('ProjectedLandweberDeconvolutionImageFilter', 'itk::ProjectedLandweberDeconvolutionImageFilter', 'itkProjectedLandweberDeconvolutionImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('ProjectedLandweberDeconvolutionImageFilter', 'itk::ProjectedLandweberDeconvolutionImageFilter', 'itkProjectedLandweberDeconvolutionImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('ProjectedLandweberDeconvolutionImageFilter', 'itk::ProjectedLandweberDeconvolutionImageFilter', 'itkProjectedLandweberDeconvolutionImageFilterIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('ProjectedLandweberDeconvolutionImageFilter', 'itk::ProjectedLandweberDeconvolutionImageFilter', 'itkProjectedLandweberDeconvolutionImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('ProjectedLandweberDeconvolutionImageFilter', 'itk::ProjectedLandweberDeconvolutionImageFilter', 'itkProjectedLandweberDeconvolutionImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('ProjectedLandweberDeconvolutionImageFilter', 'itk::ProjectedLandweberDeconvolutionImageFilter', 'itkProjectedLandweberDeconvolutionImageFilterID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('RichardsonLucyDeconvolutionImageFilter', 'itk::RichardsonLucyDeconvolutionImageFilter', 'itkRichardsonLucyDeconvolutionImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('RichardsonLucyDeconvolutionImageFilter', 'itk::RichardsonLucyDeconvolutionImageFilter', 'itkRichardsonLucyDeconvolutionImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('RichardsonLucyDeconvolutionImageFilter', 'itk::RichardsonLucyDeconvolutionImageFilter', 'itkRichardsonLucyDeconvolutionImageFilterISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('RichardsonLucyDeconvolutionImageFilter', 'itk::RichardsonLucyDeconvolutionImageFilter', 'itkRichardsonLucyDeconvolutionImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('RichardsonLucyDeconvolutionImageFilter', 'itk::RichardsonLucyDeconvolutionImageFilter', 'itkRichardsonLucyDeconvolutionImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('RichardsonLucyDeconvolutionImageFilter', 'itk::RichardsonLucyDeconvolutionImageFilter', 'itkRichardsonLucyDeconvolutionImageFilterIUC4IUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned char,4 >'),
  ('RichardsonLucyDeconvolutionImageFilter', 'itk::RichardsonLucyDeconvolutionImageFilter', 'itkRichardsonLucyDeconvolutionImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('RichardsonLucyDeconvolutionImageFilter', 'itk::RichardsonLucyDeconvolutionImageFilter', 'itkRichardsonLucyDeconvolutionImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('RichardsonLucyDeconvolutionImageFilter', 'itk::RichardsonLucyDeconvolutionImageFilter', 'itkRichardsonLucyDeconvolutionImageFilterIUS4IUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >'),
  ('RichardsonLucyDeconvolutionImageFilter', 'itk::RichardsonLucyDeconvolutionImageFilter', 'itkRichardsonLucyDeconvolutionImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('RichardsonLucyDeconvolutionImageFilter', 'itk::RichardsonLucyDeconvolutionImageFilter', 'itkRichardsonLucyDeconvolutionImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('RichardsonLucyDeconvolutionImageFilter', 'itk::RichardsonLucyDeconvolutionImageFilter', 'itkRichardsonLucyDeconvolutionImageFilterIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('RichardsonLucyDeconvolutionImageFilter', 'itk::RichardsonLucyDeconvolutionImageFilter', 'itkRichardsonLucyDeconvolutionImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('RichardsonLucyDeconvolutionImageFilter', 'itk::RichardsonLucyDeconvolutionImageFilter', 'itkRichardsonLucyDeconvolutionImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('RichardsonLucyDeconvolutionImageFilter', 'itk::RichardsonLucyDeconvolutionImageFilter', 'itkRichardsonLucyDeconvolutionImageFilterID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('TikhonovDeconvolutionImageFilter', 'itk::TikhonovDeconvolutionImageFilter', 'itkTikhonovDeconvolutionImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('TikhonovDeconvolutionImageFilter', 'itk::TikhonovDeconvolutionImageFilter', 'itkTikhonovDeconvolutionImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('TikhonovDeconvolutionImageFilter', 'itk::TikhonovDeconvolutionImageFilter', 'itkTikhonovDeconvolutionImageFilterISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('TikhonovDeconvolutionImageFilter', 'itk::TikhonovDeconvolutionImageFilter', 'itkTikhonovDeconvolutionImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('TikhonovDeconvolutionImageFilter', 'itk::TikhonovDeconvolutionImageFilter', 'itkTikhonovDeconvolutionImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('TikhonovDeconvolutionImageFilter', 'itk::TikhonovDeconvolutionImageFilter', 'itkTikhonovDeconvolutionImageFilterIUC4IUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned char,4 >'),
  ('TikhonovDeconvolutionImageFilter', 'itk::TikhonovDeconvolutionImageFilter', 'itkTikhonovDeconvolutionImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('TikhonovDeconvolutionImageFilter', 'itk::TikhonovDeconvolutionImageFilter', 'itkTikhonovDeconvolutionImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('TikhonovDeconvolutionImageFilter', 'itk::TikhonovDeconvolutionImageFilter', 'itkTikhonovDeconvolutionImageFilterIUS4IUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >'),
  ('TikhonovDeconvolutionImageFilter', 'itk::TikhonovDeconvolutionImageFilter', 'itkTikhonovDeconvolutionImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('TikhonovDeconvolutionImageFilter', 'itk::TikhonovDeconvolutionImageFilter', 'itkTikhonovDeconvolutionImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('TikhonovDeconvolutionImageFilter', 'itk::TikhonovDeconvolutionImageFilter', 'itkTikhonovDeconvolutionImageFilterIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('TikhonovDeconvolutionImageFilter', 'itk::TikhonovDeconvolutionImageFilter', 'itkTikhonovDeconvolutionImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('TikhonovDeconvolutionImageFilter', 'itk::TikhonovDeconvolutionImageFilter', 'itkTikhonovDeconvolutionImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('TikhonovDeconvolutionImageFilter', 'itk::TikhonovDeconvolutionImageFilter', 'itkTikhonovDeconvolutionImageFilterID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('WienerDeconvolutionImageFilter', 'itk::WienerDeconvolutionImageFilter', 'itkWienerDeconvolutionImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('WienerDeconvolutionImageFilter', 'itk::WienerDeconvolutionImageFilter', 'itkWienerDeconvolutionImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('WienerDeconvolutionImageFilter', 'itk::WienerDeconvolutionImageFilter', 'itkWienerDeconvolutionImageFilterISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('WienerDeconvolutionImageFilter', 'itk::WienerDeconvolutionImageFilter', 'itkWienerDeconvolutionImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('WienerDeconvolutionImageFilter', 'itk::WienerDeconvolutionImageFilter', 'itkWienerDeconvolutionImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('WienerDeconvolutionImageFilter', 'itk::WienerDeconvolutionImageFilter', 'itkWienerDeconvolutionImageFilterIUC4IUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned char,4 >'),
  ('WienerDeconvolutionImageFilter', 'itk::WienerDeconvolutionImageFilter', 'itkWienerDeconvolutionImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('WienerDeconvolutionImageFilter', 'itk::WienerDeconvolutionImageFilter', 'itkWienerDeconvolutionImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('WienerDeconvolutionImageFilter', 'itk::WienerDeconvolutionImageFilter', 'itkWienerDeconvolutionImageFilterIUS4IUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >'),
  ('WienerDeconvolutionImageFilter', 'itk::WienerDeconvolutionImageFilter', 'itkWienerDeconvolutionImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('WienerDeconvolutionImageFilter', 'itk::WienerDeconvolutionImageFilter', 'itkWienerDeconvolutionImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('WienerDeconvolutionImageFilter', 'itk::WienerDeconvolutionImageFilter', 'itkWienerDeconvolutionImageFilterIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('WienerDeconvolutionImageFilter', 'itk::WienerDeconvolutionImageFilter', 'itkWienerDeconvolutionImageFilterID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('WienerDeconvolutionImageFilter', 'itk::WienerDeconvolutionImageFilter', 'itkWienerDeconvolutionImageFilterID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('WienerDeconvolutionImageFilter', 'itk::WienerDeconvolutionImageFilter', 'itkWienerDeconvolutionImageFilterID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
)
factories = ()
